'use strict';
const $=id=>document.getElementById(id),C=RailMath,R=RailRoutes,cards=RailCards;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=C.fresh(),entry='',corrupt=false,storageOK=true,conflict=false,lastSaved=null,migrated=false;
try{const raw=localStorage.getItem(C.KEY);lastSaved=raw;if(raw!==null){const parsed=JSON.parse(raw);if(C.valid(parsed))state=parsed;else corrupt=true;}else{const old=localStorage.getItem(C.LEGACY_KEY);if(old!==null){const parsed=C.migrate(JSON.parse(old));if(parsed){state=parsed;migrated=true;}else corrupt=true;}}}catch(e){storageOK=false;corrupt=true;}
if(!corrupt)C.upgradeCards(state);
function save(){if(!corrupt&&!conflict){try{if(localStorage.getItem(C.KEY)!==lastSaved){conflict=true;}else{const encoded=JSON.stringify(state);localStorage.setItem(C.KEY,encoded);lastSaved=encoded;storageOK=true;}}catch(e){storageOK=false;}}
$('save-status').textContent=conflict?'別の画面で記録が更新されました。この画面を再読み込みしてください。':corrupt?'保存記録を読み込めません。元の記録を残して、今回は保存せず遊べます。':!storageOK?'保存できません。閉じる前にバックアップを保存してください。':migrated?'以前の正解数を引き継ぎました。ためた回数で好きな方向へ開通できます。':'✓ つづきは このブラウザに ほぞんされるよ';
$('save-status').hidden=!(conflict||corrupt||!storageOK||migrated);
$('keypad').querySelectorAll('button').forEach(b=>b.disabled=conflict);$('next').disabled=conflict;}
window.addEventListener('storage',e=>{if(e.key===C.KEY&&e.newValue!==lastSaved){conflict=true;save();}});
let camera={x:0,y:0,width:1150,height:700},selected=state.current;
function mapAspect(){const w=$('map-wrap').clientWidth,h=$('map-wrap').clientHeight;return w>0&&h>0?w/h:camera.width/camera.height;}
function centerMap(id=state.current){const s=R.stations[id];const aspect=mapAspect();camera.width=1050;camera.height=camera.width/aspect;camera.x=s.x-camera.width/2;camera.y=s.y-camera.height/2;updateCamera();}
function updateCamera(){const b=R.bounds;camera.x=Math.max(b.x-camera.width/4,Math.min(camera.x,b.x+b.width-camera.width*.75));camera.y=Math.max(b.y-camera.height/4,Math.min(camera.y,b.y+b.height-camera.height*.75));$('map').setAttribute('viewBox',`${camera.x} ${camera.y} ${camera.width} ${camera.height}`);$('map').querySelectorAll('.minor-label').forEach(t=>t.style.display=camera.width>2200?'none':'');$('map').querySelectorAll('.station-reading').forEach(t=>t.style.display=camera.width>1500?'none':'');
const scale=camera.width/Math.max(1,$('map').clientWidth),occupied=[];
const labels=[...$('map').querySelectorAll('.major-label')].sort((a,b)=>{const priority=t=>t.parentNode.dataset.station===state.current?0:cards.some(c=>!c.first&&c.station===t.parentNode.dataset.station)?1:2;return priority(a)-priority(b);});
for(const t of labels){const font=Math.max(27,12*scale);t.setAttribute('font-size',font);t.style.display='';if(camera.width>2200){const x=Number(t.getAttribute('x')),y=Number(t.getAttribute('y')),w=t.textContent.length*font,box={x:x-w/2,y:y-font,w,h:font*1.25};if(occupied.some(b=>box.x<b.x+b.w+8*scale&&box.x+box.w>b.x&&box.y<b.y+b.h+3*scale&&box.y+box.h>b.y)){t.style.display='none';}else occupied.push(box);}}
}

function zoom(f){const w=Math.max(650,Math.min(6500,camera.width*f)),ratio=w/camera.width;camera.x+=camera.width*(1-ratio)/2;camera.y+=camera.height*(1-ratio)/2;camera.height*=ratio;camera.width=w;updateCamera();}
function mapAll(){const pad=110,b={x:R.bounds.x-pad,y:R.bounds.y-pad,width:R.bounds.width+pad*2,height:R.bounds.height+pad*2},aspect=mapAspect();camera.width=Math.max(b.width,b.height*aspect);camera.height=camera.width/aspect;camera.x=b.x+(b.width-camera.width)/2;camera.y=b.y+(b.height-camera.height)/2;updateCamera();}
function renderMap(){const unlocked=new Set(C.opened(state)),major=new Set([...cards.map(c=>c.station),'玖波','大竹','横川','海田市','広島','櫛ケ浜','あき亀山']);
let html='<defs><linearGradient id="sea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#bfe2ec"/><stop offset=".5" stop-color="#9fd0e1"/></linearGradient></defs><rect x="-2000" y="-3000" width="10000" height="7000" fill="#eef0e2"/><path d="M-100 1500 Q1500 1350 2300 1270 T3500 1800 T5700 2000 V3500 H-100Z" fill="url(#sea)" stroke="#fff" stroke-width="6" vector-effect="non-scaling-stroke"/><text x="1600" y="1640" font-size="58" letter-spacing="18" fill="#84a8ad" stroke="none">瀬 戸 内 海</text>';
for(const e of R.edges){const a=R.stations[e.a],b=R.stations[e.b],line=R.lines.find(l=>l.id===e.line),open=state.edges.includes(e.id),target=[e.a,e.b].includes(state.current)&&[e.a,e.b].includes(state.target);html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${line.color}" vector-effect="non-scaling-stroke" stroke-width="${open?4:1.5}" opacity="${open?1:.22}" ${open?'':'stroke-dasharray="8 9"'}/>`;if(target)html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#e3aa40" vector-effect="non-scaling-stroke" stroke-width="7" opacity=".55"/>`;}
for(const s of Object.values(R.stations)){const active=s.id===state.current,open=unlocked.has(s.id),branch=C.adjacent(s.id).length>2,above=['kabe','geibi','gantoku'].some(id=>R.lines.find(l=>l.id===id).stations.slice(1,-1).includes(s.id));
const dy=above?-27:-27;html+=`<g class="station-node" data-station="${s.id}" role="button" tabindex="0" aria-label="${s.name} ${open?'開通済み':'未開通'}"><circle cx="${s.x}" cy="${s.y}" r="30" fill="transparent"/>${active?`<circle class="current-halo" cx="${s.x}" cy="${s.y}" r="27" fill="#f5a524" opacity=".35"/>`:''}<circle cx="${s.x}" cy="${s.y}" r="${branch?13:10}" fill="${open?'#193d47':'#fff'}" stroke="${open?'#193d47':'#a8bbae'}" stroke-width="4"/><text class="${major.has(s.id)?'major-label':'minor-label'}" x="${s.x}" y="${s.y+dy}" text-anchor="middle" font-size="${major.has(s.id)?27:22}" font-weight="${major.has(s.id)?800:600}" fill="${open?'#193d47':'#607b6e'}">${s.name}${cards.some(c=>!c.first&&c.station===s.id)?' ▣':''}</text><text class="station-reading" x="${s.x}" y="${s.y+34}" text-anchor="middle" font-size="12" fill="#728779">${s.reading}</text></g>`;}
html+='<text x="3890" y="70" font-size="20" fill="#8e678a">芸備線は三次方面へつづく（今回は下深川まで）</text>';
$('map').innerHTML=html;updateCamera();$('station-count').textContent=unlocked.size;$('collection-count').textContent=`${C.earned(state).length}/${cards.length}`;showSelection(selected);}
function showSelection(id){selected=id;if(id===state.current){$('map-selection').textContent='';return;}const s=R.stations[id],open=C.opened(state).includes(id),neighbor=C.adjacent(state.current).some(e=>e.to===id&&!state.edges.includes(e.id));$('map-selection').innerHTML=`<strong>${s.name}</strong><span>${s.reading}</span>${open?`<button data-move="${id}">この駅へ もどる</button>`:neighbor?`<button data-target="${id}">この駅へ のばす</button>`:'<span>となりの駅から、順番に開通しよう</span>'}`;}
const rubyWords=Object.fromEntries([...Object.values(R.stations),...R.lines].map(s=>[s.name,s.reading])),rubyRe=new RegExp(Object.keys(rubyWords).sort((a,b)=>b.length-a.length).join('|'),'g');
const ruby=text=>esc(text).replace(rubyRe,w=>`<ruby>${w}<rt>${rubyWords[w]}</rt></ruby>`);
function cardHTML(c,unlocked=true){return `<article class="card ${unlocked?'':'locked'}">${unlocked?`<img src="${c.image}" alt="${esc(c.name)}の実写写真" loading="lazy">`:'<div class="placeholder" aria-hidden="true"><span class="mystery-train">🚃</span><span class="mystery-mark">？</span></div>'}<div class="card-body"><div class="eyebrow">${c.first?'はじめての かいつうの きねんカード':`${ruby(c.station)}えきの きねんカード`}</div><h3>${unlocked?esc(c.name):'？？？？？'}</h3><p>${unlocked?ruby(c.fact):c.first?`ひみつの でんしゃ。${ruby(c.station)}から さいしょの 5もんを とくと あえるよ。`:`ひみつの でんしゃ。${ruby(c.station)}えきまで かいつうすると あえるよ。`}</p>${unlocked?`<p class="credit">写真：${esc(c.credit)} / ${esc(c.license)} · <a href="sources.html#${c.id}" target="_blank" rel="noopener">出典</a></p>`:''}</div></article>`;}
function directionArrow(from,to){const dx=to.x-from.x,dy=to.y-from.y;if(Math.abs(dy)<Math.abs(dx)*.35)return dx>0?'→':'←';if(Math.abs(dx)<Math.abs(dy)*.35)return dy>0?'↓':'↑';return dy>0?(dx>0?'↘':'↙'):(dx>0?'↗':'↖');}
function renderTravel(){const s=R.stations[state.current],line=R.lines.find(l=>l.stations.includes(s.id));$('current-name').textContent=s.name;$('current-reading').textContent=s.reading;$('current-line').style.background=line.color;$('current-line').textContent=line.name;
const options=C.adjacent(s.id);$('directions').innerHTML=options.map(e=>{const open=state.edges.includes(e.id),to=R.stations[e.to],route=R.lines.find(l=>l.id===e.line),active=!open&&state.target===e.to,remaining=C.credits(state)>0?'ためた回数で かいつう':`あと ${5-state.total%5}もん`;return `<button ${state.pending||conflict?'disabled':''} class="direction-choice ${open?'return':'forward'} ${active?'active':''}" style="--route-color:${route.color}" data-${open?'move':'target'}="${e.to}" aria-pressed="${active}"><span class="direction-arrow" aria-hidden="true">${directionArrow(s,to)}</span><span class="direction-name">${esc(to.name)} <span class="direction-action">へ ${open?'もどる':'すすむ'}</span><small>${esc(to.reading)}</small></span><span class="direction-detail">${open?'かいつうずみ':remaining}</span></button>`;}).join('');
const n=C.credits(state);$('build-label').textContent=state.target?(n>0?`${n}えきぶん ためているよ`:`あと ${5-state.total%5}もんで ${state.target}！`):'ろせんずで 開通した駅をえらぼう';$('dots').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<state.total%5?'on':''}"></i>`).join('')+`<b class="dots-train" style="--step:${state.total%5}" aria-hidden="true"><svg viewBox="0 0 34 20"><path d="M3 4h22a8 8 0 0 1 8 8v4H3z" fill="#fff" stroke="#16323c" stroke-width="2" stroke-linejoin="round"/><path d="M3 13h30" stroke="${line.color}" stroke-width="3"/><rect x="7" y="7" width="5" height="4" rx="1" fill="#16323c"/><rect x="15" y="7" width="5" height="4" rx="1" fill="#16323c"/><path d="M24 7h3l3 4h-6z" fill="#16323c"/><circle cx="9" cy="18" r="2" fill="#16323c"/><circle cx="26" cy="18" r="2" fill="#16323c"/></svg></b>`;$('use-credit').hidden=!(n>0&&state.target&&!state.pending);$('use-credit').textContent=`ためた回数で ${state.target}を かいつう`;$('use-credit').disabled=conflict;
const c=C.nearestReward(state,cards,true);$('next-card').innerHTML=c?`<img src="${c.image}" alt="${esc(c.name)}"><div><b>${esc(c.name)}</b><p>${esc(c.station)}駅でゲット<br>あと ${c.remaining}くかん${state.target?'（えらんだ方向）':''}</p></div>`:(C.earned(state).length===cards.length?'<div><b>すべての 車両に あえたね！</b><p>まだ白い駅にも、あいにいこう。</p></div>':'<div><b>この先の駅を つなげよう</b><p>別の方向には、まだ車両カードがあるよ。</p></div>');}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode));b.disabled=!!state.pending||conflict;});$('question').textContent=`${state.problem.a} ${state.mode==='add'?'＋':'−'} ${state.problem.b} =`;$('answer').textContent=state.solved?state.problem.result:(entry||'?');$('keypad').style.visibility=state.solved?'hidden':'visible';$('next').hidden=!state.solved;$('feedback').textContent=state.solved?'せいかい！':'こたえを いれてね';document.querySelector('.exercise').classList.toggle('solved',state.solved);renderTravel();renderMap();save();}
// After a section opens, drive it first (once per opening; `pending.drove` survives a reload), then show the usual reward. The train list is the one from before this opening, so a new card stays a surprise until the reward.
function openDrive(){const p=state.pending,e=C.edgeById[p.edge],from=e.a===p.station?e.b:e.a,next=C.adjacent(p.station).map(x=>x.to).find(id=>id!==from);RailDrive.open({from:R.stations[from],to:R.stations[p.station],next:next?R.stations[next]:null,line:R.lines.find(l=>l.id===e.line),train:C.train(state),owned:C.rideable({...state,edges:state.edges.filter(id=>id!==p.edge)}),cards,onTrain:id=>{state.train=id;save();},onDone:()=>{if(!state.pending)return;state.pending.drove=true;save();showReward();}});}
// The first opening gives the first card (Red Wing) before the drive, so the child sets off in the train they just got.
let giftMode=false;
function showReward(){if(!state.pending)return;const e=C.edgeById[state.pending.edge],earlier={...state,edges:state.edges.filter(id=>id!==e.id)},before=C.earned(earlier),gift=cards.filter(c=>c.first&&C.earned(state).includes(c.id)&&!before.includes(c.id));
if(gift.length&&!state.pending.gift&&!state.pending.drove){giftMode=true;$('reward-title').textContent='はじめての かいつう！';$('reward-text').textContent='でんしゃの カードを ゲット！ この でんしゃで しゅっぱつ しよう！';$('reward-cards').innerHTML=gift.map(c=>cardHTML(c)).join('');$('reward-close').textContent='この でんしゃで しゅっぱつ →';if(!$('reward').open)$('reward').showModal();return;}
giftMode=false;$('reward-close').textContent='つづける →';if(!state.pending.drove&&window.RailDrive){if($('reward').open)$('reward').close();openDrive();return;}const name=state.pending.station;$('reward-title').innerHTML=`<ruby>${esc(name)}<rt>${esc(R.stations[name].reading)}</rt></ruby>駅 かいつう！`;const already=C.opened(earlier).includes(name);const rewards=already?[]:cards.filter(c=>!c.first&&c.station===name);$('reward-text').textContent=rewards.length?'この駅の 車両カードを ゲット！':already?'線路が つながった！ 別のルートでも いけるね。':'またひとつ、行ける場所がふえたね。';$('reward-cards').innerHTML=rewards.map(c=>cardHTML(c)).join('');if(!$('reward').open)$('reward').showModal();}
function key(value){if(state.solved||state.pending||conflict||document.querySelector('dialog[open]'))return;if(value==='clear')entry=entry.slice(0,-1);else if(value==='submit'){if(!entry){$('feedback').textContent='こたえを いれてね。';return;}if(C.solve(state,entry)){selected=state.current;render();if(state.pending)centerMap();showReward();return;}$('feedback').textContent='もういちど やってみよう。だいじょうぶ！';entry='';}else if(entry.length<2)entry=entry==='0'?value:entry+value;$('answer').textContent=entry||'?';}
$('keypad').innerHTML=['1','2','3','4','5','6','7','8','9','clear','0','submit'].map(v=>`<button data-key="${v}" class="${v==='submit'?'action submit':v==='clear'?'action':''}" aria-label="${v==='clear'?'1けた けす':v==='submit'?'けってい':v}">${v==='clear'?'けす':v==='submit'?'けってい':v}</button>`).join('');
$('keypad').onclick=e=>{const b=e.target.closest('[data-key]');if(b)key(b.dataset.key);};
$('next').onclick=()=>{if(conflict||!C.next(state))return;entry='';render();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(conflict||state.pending||state.mode===b.dataset.mode)return;state.mode=b.dataset.mode;state.problem=C.problem(state.mode);state.solved=false;entry='';render();});
function travelClick(e){if(conflict)return;const b=e.target.closest('[data-move],[data-target]');if(!b)return;if(b.dataset.move){if(!C.move(state,b.dataset.move))return;selected=state.current;centerMap();}else{if(!C.choose(state,b.dataset.target))return;selected=b.dataset.target;}render();}
$('directions').onclick=travelClick;$('map-selection').onclick=travelClick;$('use-credit').onclick=()=>{if(conflict||!C.build(state))return;selected=state.current;render();centerMap();showReward();};
function closeReward(){if(giftMode&&state.pending){giftMode=false;state.pending.gift=true;save();$('reward').close();showReward();return;}state.pending=null;$('reward').close();render();if(state.solved)$('next').focus();}
$('reward-close').onclick=closeReward;$('reward').addEventListener('cancel',e=>{e.preventDefault();closeReward();});
$('collection-open').onclick=()=>{const got=C.earned(state);$('collection-grid').innerHTML=cards.map(c=>cardHTML(c,got.includes(c.id))).join('');$('collection-got').textContent=`${got.length} / ${cards.length}`;$('collection').showModal();};$('collection-close').onclick=()=>$('collection').close();
$('parent').onclick=()=>{resetQuiz();$('reset-status').textContent='';$('stats').innerHTML=`<p>たしざん ${state.stats.add}問 ／ ひきざん ${state.stats.sub}問<br>合計 ${state.total}問（答え直しを含む）<br>${C.opened(state).length}駅・${state.edges.length}区間 開通<br>未使用の開通回数：${C.credits(state)}駅分</p>`;$('parents').showModal();};$('parent-close').onclick=()=>$('parents').close();
$('app-version').textContent=document.querySelector('meta[name="app-version"]')?.content||'不明';
$('update-app').onclick=async()=>{
const button=$('update-app');button.disabled=true;$('update-status').textContent='最新版を確認しています…';
try{
const url=new URL('index.html',document.baseURI);url.searchParams.set('update',Date.now().toString());
const response=await fetch(url.href,{cache:'no-store'});
if(!response.ok)throw Error('通信エラー '+response.status);
const html=await response.text();
const version=new DOMParser().parseFromString(html,'text/html').querySelector('meta[name="app-version"]')?.content;
if(!version)throw Error('更新データを確認できませんでした');
$('update-status').textContent='最新版を開きます。記録はそのまま残ります。';
location.replace(url.href);
}catch(error){button.disabled=false;$('update-status').textContent='更新できませんでした：'+error.message+'。通信を確認して、もう一度お試しください。';}
};
let resetAnswer=null;
function resetQuiz(){const a=12+Math.floor(Math.random()*8),b=3+Math.floor(Math.random()*7);resetAnswer=a*b;$('reset-question').textContent=`${a} × ${b} =`;$('reset-answer').value='';let undo=false;try{const raw=localStorage.getItem(C.RESET_KEY);undo=raw!==null&&C.valid(JSON.parse(raw));}catch(e){}$('reset-undo').hidden=!undo;$('reset-app').disabled=$('reset-undo').disabled=conflict;}
$('reset-app').onclick=()=>{if(conflict)return;if(Number($('reset-answer').value)!==resetAnswer||!/^\d+$/.test($('reset-answer').value.trim())){$('reset-status').textContent='確認の答えがちがいます。';resetQuiz();return;}if(!confirm('正解数・開通した駅・車両カードを消して、玖波駅から最初にもどします。よろしいですか？')){resetQuiz();return;}try{localStorage.setItem(C.RESET_KEY,localStorage.getItem(C.KEY)??JSON.stringify(state));}catch(e){$('reset-status').textContent='リセット前の記録を残せないため、リセットを中止しました。先にバックアップを保存してください。';return;}state=C.fresh();corrupt=false;migrated=false;entry='';selected=state.current;render();centerMap();resetQuiz();$('reset-status').textContent='最初からに もどしました。';};
$('reset-undo').onclick=()=>{if(conflict)return;try{const data=JSON.parse(localStorage.getItem(C.RESET_KEY));if(!C.valid(data))throw Error();C.upgradeCards(data);if(!confirm('リセット前の記録に戻しますか？ リセットのあとに進めた分は消えます。'))return;state=data;corrupt=false;entry='';selected=state.current;render();if(!conflict&&storageOK)localStorage.removeItem(C.RESET_KEY);centerMap();$('parents').close();showReward();}catch(e){$('reset-status').textContent='リセット前の記録を読み込めませんでした。';}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='keisan-tetsudo-v2-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('ファイルが大きすぎます。');let data=JSON.parse(await f.text());if(data.version===1)data=C.migrate(data);if(!C.valid(data))throw Error('有効なバックアップではありません。');C.upgradeCards(data);if(!confirm('現在の記録を、このバックアップの記録に置き換えますか？'))return;state=data;corrupt=false;conflict=false;lastSaved=localStorage.getItem(C.KEY);entry='';selected=state.current;render();centerMap();$('parents').close();showReward();}catch(err){$('import-status').textContent='復元できませんでした。'+err.message;}finally{e.target.value='';}};
$('zoom-in').onclick=()=>zoom(.7);$('zoom-out').onclick=()=>zoom(1/.7);$('map-current').onclick=()=>centerMap();$('map-all').onclick=mapAll;
let normalCamera=null;
$('map-full').onclick=()=>{const world=document.querySelector('.world'),on=!world.classList.contains('map-expanded');if(on)normalCamera={...camera};world.classList.toggle('map-expanded',on);$('map-full').textContent=on?'もどす':'大きく見る';if(on)mapAll();else{camera={...normalCamera};normalCamera=null;camera.height=camera.width/mapAspect();updateCamera();}};
const pointers=new Map();let gesture=null,moved=false;
$('map').addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('map').setPointerCapture(e.pointerId);moved=false;gesture={x:e.clientX,y:e.clientY,camera:{...camera},distance:pointers.size===2?Math.hypot(...(()=>{const p=[...pointers.values()];return[p[0].x-p[1].x,p[0].y-p[1].y];})()):null};});
$('map').addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(gesture.distance){zoom(gesture.distance/d);gesture.distance=d;moved=true;}return;}const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;camera.x=gesture.camera.x-dx*camera.width/$('map').clientWidth;camera.y=gesture.camera.y-dy*camera.height/$('map').clientHeight;updateCamera();});
$('map').addEventListener('pointerup',e=>{if(!moved){const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-station]');if(node)showSelection(node.dataset.station);}pointers.delete(e.pointerId);gesture=null;});$('map').addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;});$('map').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.station){e.preventDefault();showSelection(e.target.dataset.station);}});
$('map').addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();zoom(e.deltaY>0?1.08:.92);}},{passive:false});
function resizeMap(){if(document.querySelector('.world').classList.contains('map-expanded'))mapAll();else{const cy=camera.y+camera.height/2;camera.height=camera.width/mapAspect();camera.y=cy-camera.height/2;updateCamera();}}
window.addEventListener('resize',resizeMap);
if(window.visualViewport)window.visualViewport.addEventListener('resize',resizeMap);
new ResizeObserver(resizeMap).observe($('map-wrap'));
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]')||e.target.closest('#map,button,input,a'))return;if(e.key==='Enter'&&state.solved){e.preventDefault();$('next').click();}else if(/^\d$/.test(e.key)){e.preventDefault();key(e.key);}else if(e.key==='Backspace'){e.preventDefault();key('clear');}else if(e.key==='Enter'){e.preventDefault();key('submit');}});
$('legend').innerHTML=R.lines.map(l=>`<span><i style="--line:${l.color}"></i>${l.name}</span>`).join('');centerMap();render();showReward();
