'use strict';
const $=id=>document.getElementById(id),C=RailMath,R=RailRoutes,cards=RailCards;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=C.fresh(),entry='',corrupt=false,storageOK=true,conflict=false,lastSaved=null,migrated=false;
try{const raw=localStorage.getItem(C.KEY);lastSaved=raw;if(raw!==null){const parsed=JSON.parse(raw);if(C.valid(parsed))state=parsed;else corrupt=true;}else{const old=localStorage.getItem(C.LEGACY_KEY);if(old!==null){const parsed=C.migrate(JSON.parse(old));if(parsed){state=parsed;migrated=true;}else corrupt=true;}}}catch(e){storageOK=false;corrupt=true;}
if(!corrupt)C.upgradeCards(state);
function save(){if(!corrupt&&!conflict){try{if(localStorage.getItem(C.KEY)!==lastSaved){conflict=true;}else{const encoded=JSON.stringify(state);localStorage.setItem(C.KEY,encoded);lastSaved=encoded;storageOK=true;}}catch(e){storageOK=false;}}
$('save-status').textContent=conflict?'別の画面で記録が更新されました。この画面を再読み込みしてください。':corrupt?'保存記録を読み込めません。元の記録を残して、今回は保存せず遊べます。':!storageOK?'保存できません。閉じる前にバックアップを保存してください。':migrated?'以前の正解数を引き継ぎました。ためた回数で好きな方向へ開通できます。':'✓ つづきは このブラウザに ほぞんされるよ';
$('save-status').hidden=!(conflict||corrupt||!storageOK||migrated);
$('keypad').querySelectorAll('button').forEach(b=>b.disabled=conflict);$('next').disabled=conflict;}
window.addEventListener('storage',e=>{if(e.key===C.KEY&&e.newValue!==lastSaved){conflict=true;save();}});
let camera={x:0,y:0,width:1150,height:700},selected=state.current;
function mapAspect(){const w=$('map-wrap').clientWidth,h=$('map-wrap').clientHeight;return w>0&&h>0?w/h:camera.width/camera.height;}
function centerMap(id=state.current){const s=R.stations[id];const aspect=mapAspect();camera.width=1050;camera.height=camera.width/aspect;camera.x=s.x-camera.width/2;camera.y=s.y-camera.height/2;updateCamera();}
function updateCamera(){const b=R.bounds;camera.x=Math.max(b.x-camera.width/4,Math.min(camera.x,b.x+b.width-camera.width*.75));camera.y=Math.max(b.y-camera.height/4,Math.min(camera.y,b.y+b.height-camera.height*.75));$('map').setAttribute('viewBox',`${camera.x} ${camera.y} ${camera.width} ${camera.height}`);$('map').querySelectorAll('.minor-label').forEach(t=>t.style.display=camera.width>2200?'none':'');$('map').querySelectorAll('.station-reading').forEach(t=>t.style.display=camera.width>1500?'none':'');
const scale=camera.width/Math.max(1,$('map').clientWidth),occupied=[];
const labels=[...$('map').querySelectorAll('.major-label')].sort((a,b)=>{const priority=t=>t.parentNode.dataset.station===state.current?0:cards.some(c=>!c.first&&c.station===t.parentNode.dataset.station)?1:2;return priority(a)-priority(b);});
for(const t of labels){const font=Math.max(27,12*scale);t.setAttribute('font-size',font);t.style.display='';if(camera.width>2200){const x=Number(t.getAttribute('x')),y=Number(t.getAttribute('y')),w=t.textContent.length*font,box={x:x-w/2,y:y-font,w,h:font*1.25};if(occupied.some(b=>box.x<b.x+b.w+8*scale&&box.x+box.w>b.x&&box.y<b.y+b.h+3*scale&&box.y+box.h>b.y)){t.style.display='none';}else occupied.push(box);}}
}

function zoom(f){const w=Math.max(650,Math.min(6500,camera.width*f)),ratio=w/camera.width;camera.x+=camera.width*(1-ratio)/2;camera.y+=camera.height*(1-ratio)/2;camera.height*=ratio;camera.width=w;updateCamera();}
function mapAll(){const pad=110,b={x:R.bounds.x-pad,y:R.bounds.y-pad,width:R.bounds.width+pad*2,height:R.bounds.height+pad*2},aspect=mapAspect();camera.width=Math.max(b.width,b.height*aspect);camera.height=camera.width/aspect;camera.x=b.x+(b.width-camera.width)/2;camera.y=b.y+(b.height-camera.height)/2;updateCamera();}
function renderMap(){const unlocked=new Set(C.opened(state)),major=new Set([...cards.map(c=>c.station),'玖波','大竹','横川','海田市','広島','櫛ケ浜','あき亀山']);
let html='<defs><linearGradient id="sea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#bfe2ec"/><stop offset=".5" stop-color="#9fd0e1"/></linearGradient></defs><rect x="-2000" y="-3000" width="10000" height="7000" fill="#eef0e2"/><path d="M-100 1500 Q1500 1350 2300 1270 T3500 1800 T5700 2000 V3500 H-100Z" fill="url(#sea)" stroke="#fff" stroke-width="6" vector-effect="non-scaling-stroke"/><text x="1600" y="1640" font-size="58" letter-spacing="18" fill="#84a8ad" stroke="none">瀬 戸 内 海</text>';
for(const e of R.edges){const a=R.stations[e.a],b=R.stations[e.b],line=R.lines.find(l=>l.id===e.line),open=state.edges.includes(e.id),target=[e.a,e.b].includes(state.current)&&[e.a,e.b].includes(state.target);html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${line.color}" vector-effect="non-scaling-stroke" stroke-width="${open?4:1.5}" opacity="${open?1:.22}" ${open?'':'stroke-dasharray="8 9"'}/>`;if(target)html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#e3aa40" vector-effect="non-scaling-stroke" stroke-width="7" opacity=".55"/>`;}
for(const s of Object.values(R.stations)){const active=s.id===state.current,open=unlocked.has(s.id),branch=C.adjacent(s.id).length>2,above=['kabe','geibi','gantoku'].some(id=>R.lines.find(l=>l.id===id).stations.slice(1,-1).includes(s.id));
const dy=above?-27:-27;html+=`<g class="station-node" data-station="${s.id}" role="button" tabindex="0" aria-label="${s.name} ${open?'開通済み':'未開通'}"><circle cx="${s.x}" cy="${s.y}" r="30" fill="transparent"/>${active?`<circle class="current-halo" cx="${s.x}" cy="${s.y}" r="27" fill="#f5a524" opacity=".35"/>`:''}<circle cx="${s.x}" cy="${s.y}" r="${branch?13:10}" fill="${open?'#193d47':'#fff'}" stroke="${open?'#193d47':'#a8bbae'}" stroke-width="4"/><text class="${major.has(s.id)?'major-label':'minor-label'}" x="${s.x}" y="${s.y+dy}" text-anchor="middle" font-size="${major.has(s.id)?27:22}" font-weight="${major.has(s.id)?800:600}" fill="${open?'#193d47':'#607b6e'}">${s.name}${cards.some(c=>!c.first&&c.station===s.id)?' ▣':''}</text><text class="station-reading" x="${s.x}" y="${s.y+34}" text-anchor="middle" font-size="12" fill="#728779">${s.reading}</text></g>`;}
html+='<text x="3890" y="70" font-size="20" fill="#8e678a">芸備線は三次方面へつづく（今回は下深川まで）</text>';
$('map').innerHTML=html;updateCamera();$('station-count').textContent=unlocked.size;$('collection-count').textContent=`${C.earned(state).length}/${cards.length}`;showSelection(selected);}
function showSelection(id){selected=id;if(id===state.current){$('map-selection').textContent='';return;}const s=R.stations[id],open=C.opened(state).includes(id),neighbor=C.adjacent(state.current).some(e=>e.to===id&&!state.edges.includes(e.id));$('map-selection').innerHTML=`<strong>${s.name}</strong><span>${s.reading}</span>${open?`<button data-move="${id}">この駅へ もどる</button>`:neighbor?`<button data-target="${id}">この駅へ のばす</button>`:'<span>となりの駅から、順番に開通しよう</span>'}`;}
const rubyWords=Object.fromEntries([...Object.values(R.stations),...R.lines].map(s=>[s.name,s.reading])),rubyRe=new RegExp(Object.keys(rubyWords).sort((a,b)=>b.length-a.length).join('|'),'g');
const ruby=text=>esc(text).replace(rubyRe,w=>`<ruby>${w}<rt>${rubyWords[w]}</rt></ruby>`);
function cardHTML(c,unlocked=true){return `<article class="card ${unlocked?'':'locked'}">${unlocked?`<img src="${c.image}" alt="${esc(c.name)}の実写写真" loading="lazy">`:'<div class="placeholder" aria-hidden="true"><span class="mystery-train">🚃</span><span class="mystery-mark">？</span></div>'}<div class="card-body"><div class="eyebrow">${c.first?'はじめての かいつうの きねんカード':`${ruby(c.station)}えきの きねんカード`}</div><h3>${unlocked?esc(c.name):'？？？？？'}</h3><p>${unlocked?ruby(c.fact):c.first?`ひみつの でんしゃ。${ruby(c.station)}から さいしょの 5もんを とくと あえるよ。`:`ひみつの でんしゃ。${ruby(c.station)}えきまで かいつうすると あえるよ。`}</p>${unlocked?`<p class="credit">写真：${esc(c.credit)} / ${esc(c.license)} · <a href="sources.html#${c.id}" target="_blank" rel="noopener">出典</a></p>`:''}</div></article>`;}
// Station stamps are drawn in SVG. Look D, chosen on 2026-09-26 from a side-by-side of four: the thick ring of the first version (in the colours of every line through the station) with a big reading and name that stay readable in the stamp book, and the scenery pictures of the retro mock-up underneath. Stations with a landmark get their own picture (STAMP_LANDMARK).
let stampSeq=0;
const STAMP_PAPER='#f7f4ec',STAMP_LANDMARK={'宮島口':'torii','広島':'castle','岩国':'kintai','西岩国':'nishiiwakuni','廿日市':'kendama','呉':'submarine','三原':'tako','竹原':'machiya','忠海':'rabbit','西条':'chimney','柳井':'kingyo','大畠':'ohashi','横川':'bus','徳山':'factory'};
const stampTrain=(x,y,ink)=>`<rect x="${x}" y="${y}" width="50" height="14" rx="2.5" fill="${ink}"/>${[4,14,24].map(d=>`<rect x="${x+d}" y="${y+3}" width="7" height="4.5" rx="1" fill="${STAMP_PAPER}"/>`).join('')}<rect x="${x+34}" y="${y+3}" width="9" height="4.5" rx="1.2" fill="${STAMP_PAPER}"/><path d="M${x+10} ${y}l5-6 5 6" fill="none" stroke="${ink}" stroke-width="1.5"/>`;
const stampRail=ink=>`<path d="M44 78H156" stroke="${ink}" stroke-width="1.8"/><path d="M52 78v3M64 78v3M76 78v3M88 78v3M100 78v3M112 78v3M124 78v3M136 78v3M148 78v3" stroke="${ink}" stroke-width="1.2"/>`;
const STAMP_ART={
sea:ink=>`<path d="M44 70Q58 56 75 66T115 61T145 68T156 74" fill="none" stroke="${ink}" stroke-width="1.5" opacity=".45"/><path d="M40 76Q52 70 66 76T96 76T126 76T156 76" fill="none" stroke="${ink}" stroke-width="1.6" stroke-linecap="round"/><path d="M46 82Q60 77 76 82T108 82T140 82" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>${stampTrain(64,56,ink)}<path d="M74 70v8M104 70v8" stroke="${ink}" stroke-width="1.8"/><path d="M126 48Q130 44 134 48Q138 44 142 48" fill="none" stroke="${ink}" stroke-width="1.3"/>`,
hills:ink=>`<path d="M42 72L60 52 72 62 92 42 112 64 126 54 158 74" fill="none" stroke="${ink}" stroke-width="1.8" stroke-linejoin="round" opacity=".55"/><path d="M86 49l6-7 6 7" fill="none" stroke="${ink}" stroke-width="1.2"/><circle cx="140" cy="44" r="5" fill="none" stroke="${ink}" stroke-width="1.4"/>${stampTrain(75,62,ink)}${stampRail(ink)}`,
town:ink=>`<rect x="44" y="54" width="15" height="24" fill="${ink}" opacity=".8"/><rect x="61" y="60" width="12" height="18" fill="${ink}" opacity=".6"/><rect x="127" y="58" width="13" height="20" fill="${ink}" opacity=".6"/><rect x="142" y="52" width="15" height="26" fill="${ink}" opacity=".8"/>${[50,54,146,150].map(x=>`<rect x="${x}" y="58" width="2.5" height="3" fill="${STAMP_PAPER}"/><rect x="${x}" y="64" width="2.5" height="3" fill="${STAMP_PAPER}"/>`).join('')}${stampTrain(75,62,ink)}${stampRail(ink)}`,
torii:ink=>`<path d="M66 52Q100 47 134 52L132 56Q100 51 68 56Z" fill="${ink}"/><rect x="72" y="58" width="56" height="2.8" fill="${ink}"/><rect x="70" y="66" width="60" height="2.5" fill="${ink}"/><rect x="79" y="57" width="6" height="25" fill="${ink}"/><rect x="115" y="57" width="6" height="25" fill="${ink}"/><rect x="72" y="68" width="4" height="14" fill="${ink}"/><rect x="124" y="68" width="4" height="14" fill="${ink}"/><path d="M45 82Q72 76 100 82T155 82" fill="none" stroke="${ink}" stroke-width="1.8" stroke-linecap="round"/>`,
kintai:ink=>`<path d="M116 54Q136 32 160 50" fill="none" stroke="${ink}" stroke-width="1.6" opacity=".6"/><rect x="135" y="38" width="11" height="5" fill="${ink}" opacity=".8"/><path d="M133 38h15l-3-3.5h-9z" fill="${ink}" opacity=".8"/><rect x="137.5" y="31" width="6" height="3.5" fill="${ink}" opacity=".8"/><path d="M136 31h9l-2-2.5h-5z" fill="${ink}" opacity=".8"/>${[[42,65,68,64,58],[65,88,64,64,38],[88,112,64,64,38],[112,135,64,64,38],[135,158,64,68,58]].map(([a,b,ya,yb,c])=>`<path d="M${a} ${ya}Q${(a+b)/2} ${c} ${b} ${yb}" fill="none" stroke="${ink}" stroke-width="3.2"/><path d="M${a} ${ya-4}Q${(a+b)/2} ${c-4} ${b} ${yb-4}" fill="none" stroke="${ink}" stroke-width="1"/><path d="M${a+2} ${ya+5}Q${(a+b)/2} ${c+7} ${b-2} ${yb+5}" fill="none" stroke="${ink}" stroke-width="1.4"/>${[.2,.35,.5,.65,.8].map(t=>{const q=(y0,y1,k)=>(1-t)*(1-t)*y0+2*t*(1-t)*k+t*t*y1,x=a+(b-a)*t;return `<path d="M${x} ${q(ya,yb,c)}V${q(ya+5,yb+5,c+7)}" stroke="${ink}" stroke-width=".9"/>`;}).join('')}`).join('')}${[65,88,112,135].map(x=>`<path d="M${x-3.5} 64h7l2.5 16h-12z" fill="${ink}"/>`).join('')}<path d="M40 84Q52 79 64 84T88 84T112 84T136 84T160 84" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
nishiiwakuni:ink=>`<path d="M54 58L64 48H136L146 58Z" fill="${ink}"/><path d="M80 48L100 39 120 48Z" fill="${ink}"/><rect x="60" y="58" width="80" height="22" fill="${ink}"/><rect x="58" y="57.3" width="84" height="1.4" fill="${STAMP_PAPER}"/>${[[66,68],[84,63],[95.5,63],[107,63],[125,68]].map(([x,y])=>`<path d="M${x} 80V${y+4.5}a4.5 4.5 0 0 1 9 0V80Z" fill="${STAMP_PAPER}"/>`).join('')}<path d="M44 82H156" stroke="${ink}" stroke-width="1.8"/>`,
kendama:ink=>`<path d="M100 34l2.4 12h-4.8z" fill="${ink}"/><rect x="97" y="46" width="6" height="30" rx="1.5" fill="${ink}"/><rect x="84" y="54" width="32" height="4" rx="2" fill="${ink}"/><path d="M76 49h18a9 9 0 0 1-18 0z" fill="${ink}"/><path d="M108 50h14a7 7 0 0 1-14 0z" fill="${ink}"/><path d="M91 76h18a9 7 0 0 1-18 0z" fill="${ink}"/><path d="M103 66Q128 74 133 53" fill="none" stroke="${ink}" stroke-width="1"/><circle cx="136" cy="44" r="10" fill="${ink}"/><path d="M130.5 40.5a6.5 6.5 0 0 1 5.5-3" fill="none" stroke="${STAMP_PAPER}" stroke-width="2" stroke-linecap="round"/><path d="M58 46l2 5 5 1.5-5 1.5-2 5-2-5-5-1.5 5-1.5z" fill="${ink}" opacity=".6"/><path d="M66 68l1.4 3 3 1-3 1-1.4 3-1.4-3-3-1 3-1z" fill="${ink}" opacity=".45"/>`,submarine:ink=>`<path d="M46 69Q46 61 62 61H132Q146 61 153 66V72Q146 77 132 77H62Q46 77 46 69Z" fill="${ink}"/><path d="M149 65L158 56V81L149 73Z" fill="${ink}"/><path d="M82 61V50Q82 46 86 46H98Q101 46 102 49L105 61Z" fill="${ink}"/><path d="M75 54H109" stroke="${ink}" stroke-width="2.4" stroke-linecap="round"/><path d="M89 46V40M95 46V42" stroke="${ink}" stroke-width="1.4"/><path d="M58 68H140" stroke="${STAMP_PAPER}" stroke-width=".9" opacity=".7"/><path d="M40 83Q52 78 64 83T88 83T112 83T136 83T160 83" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
tako:ink=>`${['M86 62Q72 69 70 79Q76 84 80 77','M91 65Q84 76 88 83','M100 66Q98 78 102 83','M109 65Q116 76 112 83','M114 62Q128 69 130 79Q124 84 120 77'].map(d=>`<path d="${d}" fill="none" stroke="${ink}" stroke-width="5" stroke-linecap="round"/>`).join('')}<ellipse cx="100" cy="52" rx="17" ry="15" fill="${ink}"/><path d="M84 47Q100 41 116 47" fill="none" stroke="${STAMP_PAPER}" stroke-width="2.4"/><circle cx="93" cy="55" r="4" fill="${STAMP_PAPER}"/><circle cx="107" cy="55" r="4" fill="${STAMP_PAPER}"/><circle cx="93.5" cy="56" r="2" fill="${ink}"/><circle cx="107.5" cy="56" r="2" fill="${ink}"/><path d="M97 62q3 2.5 6 0" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.5" stroke-linecap="round"/><path d="M44 82Q54 77 64 82M136 82Q146 77 156 82" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
machiya:ink=>{const grille=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${STAMP_PAPER}"/>${Array.from({length:Math.floor(w/3)},(_,i)=>`<path d="M${x+1.5+i*3} ${y}v${h}" stroke="${ink}" stroke-width="1.1"/>`).join('')}`;return `<path d="M42 60L50 52H74L82 60Z" fill="${ink}"/><rect x="47" y="60" width="30" height="21" fill="${ink}"/>${grille(51,64,12,10)}<path d="M84 48L91 40H109L116 48Z" fill="${ink}"/><rect x="87" y="48" width="26" height="9" fill="${ink}"/>${grille(91,50,18,5)}<path d="M79 61L85 56H115L121 61Z" fill="${ink}"/><rect x="83" y="61" width="34" height="20" fill="${ink}"/>${grille(87,65,15,11)}<path d="M118 60L126 52H150L158 60Z" fill="${ink}"/><rect x="123" y="60" width="30" height="21" fill="${ink}"/>${grille(137,64,12,10)}<path d="M40 82H160" stroke="${ink}" stroke-width="1.8"/>`;},
rabbit:ink=>`<path d="M122 66Q134 48 150 56Q158 60 160 66Z" fill="${ink}" opacity=".45"/><path d="M40 70Q48 66 56 70T72 70M128 70Q136 66 144 70T160 70" fill="none" stroke="${ink}" stroke-width="1.3" opacity=".6"/><ellipse cx="94" cy="70" rx="17" ry="12" fill="${ink}"/><circle cx="111" cy="58" r="9.5" fill="${ink}"/><ellipse cx="106" cy="42" rx="3.6" ry="11" transform="rotate(-12 106 42)" fill="${ink}"/><ellipse cx="114" cy="42" rx="3.6" ry="11" transform="rotate(10 114 42)" fill="${ink}"/><circle cx="114" cy="56" r="1.8" fill="${STAMP_PAPER}"/><circle cx="77" cy="67" r="4" fill="${ink}"/><path d="M40 83H160" stroke="${ink}" stroke-width="1.8"/><path d="M58 82q3-6 6 0M136 82q3-7 6 0M146 82q2-5 4 0" fill="none" stroke="${ink}" stroke-width="1.3"/>`,
chimney:ink=>`${[[64,33],[120,38],[142,46]].map(([x,t])=>`<path d="M${x-4.5} 72L${x-3} ${t}H${x+3}L${x+4.5} 72Z" fill="${ink}"/><path d="M${x-3.3} ${t+4}h6.6M${x-3.6} ${t+10}h7.2" stroke="${STAMP_PAPER}" stroke-width="1"/>`).join('')}<path d="M42 70L50 63H96L104 70Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><rect x="46" y="70" width="54" height="12" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><path d="M104 71L111 65H152L159 71Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><rect x="108" y="71" width="47" height="11" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/>${[46,52,58,64,70,76,82,88,94,108,114,120,126,132,138,144,150].map(x=>`<path d="M${x} 82l5-5M${x} 77l5 5" stroke="${STAMP_PAPER}" stroke-width=".8"/>`).join('')}`,kingyo:ink=>{const fish=t=>`<g transform="${t}"><path d="M96 38V46" stroke="${ink}" stroke-width="1.2"/><path d="M114 60L131 47Q126 60 131 73Z" fill="${ink}"/><path d="M90 47Q97 39 105 47Z" fill="${ink}"/><ellipse cx="96" cy="60" rx="21" ry="14" fill="${ink}"/>${[88,98,108].map(x=>`<path d="M${x} 47Q${x-4} 60 ${x} 73" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.1"/>`).join('')}<circle cx="81" cy="56" r="4" fill="${STAMP_PAPER}"/><circle cx="80.5" cy="56.5" r="2" fill="${ink}"/><path d="M92 74v5M100 74v5" stroke="${ink}" stroke-width="1.4"/></g>`;return `<path d="M44 38Q100 34 156 38" fill="none" stroke="${ink}" stroke-width="1.3"/>${fish('translate(8 0)')}${fish('translate(56 40) scale(.5) translate(-96 -38)')}`;},
ohashi:ink=>`<path d="M132 70Q144 52 162 58V84H132Z" fill="${ink}" opacity=".35"/><path d="M38 70Q44 56 58 60V84H38Z" fill="${ink}" opacity=".35"/><rect x="40" y="55" width="120" height="3" fill="${ink}"/><rect x="40" y="64" width="120" height="2" fill="${ink}"/><path d="M40 64${Array.from({length:15},(_,i)=>`L${44+i*8} ${i%2?64:57}`).join('')}" fill="none" stroke="${ink}" stroke-width="1.3"/>${[70,100,130].map(x=>`<path d="M${x-2.5} 66h5l1.5 17h-8z" fill="${ink}"/>`).join('')}<path d="M40 84Q52 79 64 84T88 84T112 84T136 84T160 84" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
bus:ink=>`<path d="M60 44H138Q142 44 142 47V49H58V47Q58 44 60 44Z" fill="${ink}"/>${[62,84,106,128,140].map(x=>`<path d="M${x} 49V62" stroke="${ink}" stroke-width="2"/>`).join('')}<path d="M66 60h14M88 60h14M110 60h14" stroke="${ink}" stroke-width="2.4"/><path d="M56 62H144V71Q144 73 142 73H58Q56 73 56 71Z" fill="${ink}"/><path d="M44 63H56V73H46Q44 73 44 71Z" fill="${ink}"/><path d="M56 55l6 5" stroke="${ink}" stroke-width="1.6"/>${[70,128].map(x=>`<circle cx="${x}" cy="76" r="8" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2.4"/>${[0,45,90,135].map(a=>`<path d="M${x} 69V83" stroke="${ink}" stroke-width="1" transform="rotate(${a} ${x} 76)"/>`).join('')}<circle cx="${x}" cy="76" r="2" fill="${ink}"/>`).join('')}<path d="M40 84.5H160" stroke="${ink}" stroke-width="1.4"/>`,
factory:ink=>`<path d="M58 40a7 7 0 1 0 8 9a5.5 5.5 0 1 1-8-9z" fill="${ink}"/><path d="M80 42l1 2 2 1-2 1-1 2-1-2-2-1 2-1z" fill="${ink}" opacity=".6"/><path d="M138 40q4-4 0-8t2-8" fill="none" stroke="${ink}" stroke-width="1.4" opacity=".55"/><rect x="136" y="42" width="4" height="40" fill="${ink}"/><rect x="70" y="46" width="7" height="36" fill="${ink}"/><rect x="117" y="52" width="6" height="30" fill="${ink}"/><rect x="42" y="64" width="30" height="18" fill="${ink}"/><path d="M79 82V66a10 6 0 0 1 20 0V82Z" fill="${ink}"/><path d="M99 82V70a8 5 0 0 1 16 0V82Z" fill="${ink}"/><rect x="123" y="62" width="34" height="20" fill="${ink}"/><path d="M40 60H160" stroke="${ink}" stroke-width="1"/><path d="M70 52h7M70 58h7M70 64h7M117 58h6M117 64h6" stroke="${STAMP_PAPER}" stroke-width=".9"/>${[[47,68],[53,68],[59,68],[65,68],[50,74],[62,74],[73.5,50],[73.5,70],[86,70],[92,74],[89,78],[105,74],[110,78],[120,56],[120,70],[138,48],[138,60],[128,66],[134,66],[146,66],[152,66],[128,74],[140,74],[150,74]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="1.1" fill="${STAMP_PAPER}"/>`).join('')}`,
castle:ink=>`<path d="M82 52H118L114 46H86Z" fill="${ink}"/><path d="M88 46H112L108 40H92Z" fill="${ink}"/><path d="M95 40H105L100 35Z" fill="${ink}"/><rect x="78" y="52" width="44" height="18" fill="${ink}"/><rect x="85" y="56" width="4.5" height="5" fill="${STAMP_PAPER}"/><rect x="97.5" y="56" width="5" height="5" fill="${STAMP_PAPER}"/><rect x="110" y="56" width="4.5" height="5" fill="${STAMP_PAPER}"/><rect x="44" y="58" width="15" height="24" fill="${ink}" opacity=".8"/><rect x="61" y="64" width="12" height="18" fill="${ink}" opacity=".6"/><rect x="127" y="62" width="13" height="20" fill="${ink}" opacity=".6"/><rect x="142" y="56" width="15" height="26" fill="${ink}" opacity=".8"/><rect x="89" y="72" width="22" height="10" rx="2" fill="${ink}"/>`};
function stampSVG(id){const s=R.stations[id],lines=R.lines.filter(l=>l.stations.includes(id)),ink=lines[0].color,scene=STAMP_LANDMARK[id]||(window.RailDrive?RailDrive.stationScene(id,lines.map(l=>l.id)):'sea'),key=`stamp-${++stampSeq}`,ring=2*Math.PI*90,fs=Math.min(44,132/s.name.length),rs=Math.min(18,84/s.reading.length);
return `<svg class="stamp-art" viewBox="0 0 200 200" aria-hidden="true"><defs><clipPath id="${key}"><circle cx="100" cy="100" r="76"/></clipPath></defs><g transform="rotate(${s.name.charCodeAt(0)%7-3} 100 100)">${lines.map((l,i)=>`<circle cx="100" cy="100" r="90" fill="none" stroke="${l.color}" stroke-width="12" stroke-dasharray="${ring/lines.length} ${ring}" stroke-dashoffset="${-i*ring/lines.length}" transform="rotate(-90 100 100)"/>`).join('')}<circle cx="100" cy="100" r="78" fill="none" stroke="${ink}" stroke-width="3"/>
<text x="100" y="50" text-anchor="middle" font-size="${rs}" font-weight="800" fill="${ink}">${esc(s.reading)}</text><text x="100" y="${80+fs/2.8}" text-anchor="middle" font-size="${fs}" font-weight="900" fill="${ink}">${esc(s.name)}</text><g clip-path="url(#${key})"><g transform="translate(100 110) scale(.98) translate(-100 -35)">${STAMP_ART[scene](ink)}</g></g></g></svg>`;}
// The press (as in the mock-up): the stamp comes down from large to its place in 0.3s and lands at about 0.2s, the page gives, then sparks; drive.js pon() plays the stamp sound file on the landing and the キラーン with the sparks (loaded ahead while the pad waits).
function stampBurst(id){const colors=[...R.lines.filter(l=>l.stations.includes(id)).map(l=>l.color),'#f5a524'];return Array.from({length:12},(_,i)=>`<i class="stamp-spark${i%2?' star':''}" aria-hidden="true" style="--a:${i*30+8}deg;--d:${i%3?112:132}px;--c:${colors[i%colors.length]}"></i>`).join('');}
function stampDay(id){const d=state.stamps?.[id];if(d){const [,m,day]=d.split('-').map(Number);return `${m}がつ ${day}にち`;}return id===C.opened(state)[0]?'しゅっぱつの えき':'まえに きたよ';}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function directionArrow(from,to){const dx=to.x-from.x,dy=to.y-from.y;if(Math.abs(dy)<Math.abs(dx)*.35)return dx>0?'→':'←';if(Math.abs(dx)<Math.abs(dy)*.35)return dy>0?'↓':'↑';return dy>0?(dx>0?'↘':'↙'):(dx>0?'↗':'↖');}
function renderTravel(){const s=R.stations[state.current],line=R.lines.find(l=>l.stations.includes(s.id));$('current-name').textContent=s.name;$('current-reading').textContent=s.reading;$('current-line').style.background=line.color;$('current-line').textContent=line.name;
const options=C.adjacent(s.id);$('directions').innerHTML=options.map(e=>{const open=state.edges.includes(e.id),to=R.stations[e.to],route=R.lines.find(l=>l.id===e.line),active=!open&&state.target===e.to,remaining=C.credits(state)>0?'ためた回数で かいつう':`あと ${5-state.total%5}もん`;return `<button ${state.pending||conflict?'disabled':''} class="direction-choice ${open?'return':'forward'} ${active?'active':''}" style="--route-color:${route.color}" data-${open?'move':'target'}="${e.to}" aria-pressed="${active}"><span class="direction-arrow" aria-hidden="true">${directionArrow(s,to)}</span><span class="direction-name">${esc(to.name)} <span class="direction-action">へ ${open?'もどる':'すすむ'}</span><small>${esc(to.reading)}</small></span><span class="direction-detail">${open?'かいつうずみ':remaining}</span></button>`;}).join('');
const n=C.credits(state);$('build-label').textContent=state.target?(n>0?`${n}えきぶん ためているよ`:`あと ${5-state.total%5}もんで ${state.target}！`):'ろせんずで 開通した駅をえらぼう';$('dots').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<state.total%5?'on':''}"></i>`).join('')+`<b class="dots-train" style="--step:${state.total%5}" aria-hidden="true"><svg viewBox="0 0 34 20"><path d="M3 4h22a8 8 0 0 1 8 8v4H3z" fill="#fff" stroke="#16323c" stroke-width="2" stroke-linejoin="round"/><path d="M3 13h30" stroke="${line.color}" stroke-width="3"/><rect x="7" y="7" width="5" height="4" rx="1" fill="#16323c"/><rect x="15" y="7" width="5" height="4" rx="1" fill="#16323c"/><path d="M24 7h3l3 4h-6z" fill="#16323c"/><circle cx="9" cy="18" r="2" fill="#16323c"/><circle cx="26" cy="18" r="2" fill="#16323c"/></svg></b>`;$('use-credit').hidden=!(n>0&&state.target&&!state.pending);$('use-credit').textContent=`ためた回数で ${state.target}を かいつう`;$('use-credit').disabled=conflict;
const c=C.nearestReward(state,cards,true);$('next-card').innerHTML=c?`<img src="${c.image}" alt="${esc(c.name)}"><div><b>${esc(c.name)}</b><p>${esc(c.station)}駅でゲット<br>あと ${c.remaining}くかん${state.target?'（えらんだ方向）':''}</p></div>`:(C.earned(state).length===cards.length?'<div><b>すべての 車両に あえたね！</b><p>まだ白い駅にも、あいにいこう。</p></div>':'<div><b>この先の駅を つなげよう</b><p>別の方向には、まだ車両カードがあるよ。</p></div>');}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode));b.disabled=!!state.pending||conflict;});$('question').textContent=`${state.problem.a} ${state.mode==='add'?'＋':'−'} ${state.problem.b} =`;$('answer').textContent=state.solved?state.problem.result:(entry||'?');$('keypad').style.visibility=state.solved?'hidden':'visible';$('next').hidden=!state.solved;$('feedback').textContent=state.solved?'せいかい！':'こたえを いれてね';document.querySelector('.exercise').classList.toggle('solved',state.solved);renderTravel();renderMap();save();}
// After a section opens, drive it first (once per opening; `pending.drove` survives a reload), then show the usual reward. The train list is the one from before this opening, so a new card stays a surprise until the reward.
function openDrive(){const p=state.pending,e=C.edgeById[p.edge],from=e.a===p.station?e.b:e.a,next=C.adjacent(p.station).map(x=>x.to).find(id=>id!==from);RailDrive.open({from:R.stations[from],to:R.stations[p.station],next:next?R.stations[next]:null,line:R.lines.find(l=>l.id===e.line),train:C.train(state),owned:C.rideable({...state,edges:state.edges.filter(id=>id!==p.edge)}),cards,onTrain:id=>{state.train=id;save();},onDone:()=>{if(!state.pending)return;state.pending.drove=true;save();showReward();}});}
// The first opening gives the first card (Red Wing) before the drive, so the child sets off in the train they just got.
// A new station's stamp waits for the child to tap it ("ポン！"); the card and つづける come after.
let giftMode=false;
function showReward(justStamped=false){if(!state.pending)return;const e=C.edgeById[state.pending.edge],earlier={...state,edges:state.edges.filter(id=>id!==e.id)},before=C.earned(earlier),gift=cards.filter(c=>c.first&&C.earned(state).includes(c.id)&&!before.includes(c.id));
if(gift.length&&!state.pending.gift&&!state.pending.drove){giftMode=true;$('reward-title').textContent='はじめての かいつう！';$('reward-text').textContent='でんしゃの カードを ゲット！ この でんしゃで しゅっぱつ しよう！';$('reward-cards').innerHTML=gift.map(c=>cardHTML(c)).join('');$('reward-close').textContent='この でんしゃで しゅっぱつ →';$('reward-stamp').innerHTML='';$('reward-close').hidden=false;if(!$('reward').open)$('reward').showModal();return;}
giftMode=false;$('reward-close').textContent='つづける →';if(!state.pending.drove&&window.RailDrive){if($('reward').open)$('reward').close();openDrive();return;}const name=state.pending.station;$('reward-title').innerHTML=`<ruby>${esc(name)}<rt>${esc(R.stations[name].reading)}</rt></ruby>駅 かいつう！`;const already=C.opened(earlier).includes(name);const rewards=already?[]:cards.filter(c=>!c.first&&c.station===name),pressing=C.needsStamp(state);$('reward-stamp').innerHTML=already?'':pressing?`<button class="stamp-page stamp-pad" aria-label="${esc(name)}えきの スタンプを おす"><span class="stamp-hint"><span class="stamp-finger" aria-hidden="true">👆</span>ここを タップして<br>ポン！</span></button>`:`<div class="stamp-page">${justStamped?stampBurst(name):''}<div class="stamp-inked">${stampSVG(name)}</div></div><p class="stamp-day">${stampDay(name)}</p>`;$('reward-close').hidden=pressing;if(pressing)window.RailDrive?.loadSfx();$('reward').classList.toggle('stamping',justStamped);$('reward-text').textContent=pressing?'えきスタンプを おそう！':rewards.length?'この駅の 車両カードを ゲット！':already?'線路が つながった！ 別のルートでも いけるね。':'またひとつ、行ける場所がふえたね。';const cardsHTML=pressing?'':rewards.map(c=>cardHTML(c)).join('');$('reward-cards').innerHTML=justStamped?'':cardsHTML;if(!$('reward').open)$('reward').showModal();if(justStamped){const at=state.pending;setTimeout(()=>{if(state.pending!==at)return;$('reward-cards').innerHTML=cardsHTML;$('reward-close').focus({preventScroll:true});},600);}}
function key(value){if(state.solved||state.pending||conflict||document.querySelector('dialog[open]'))return;window.RailDrive?.loadSfx();if(value==='clear')entry=entry.slice(0,-1);else if(value==='submit'){if(!entry){$('feedback').textContent='こたえを いれてね。';return;}if(C.solve(state,entry)){window.RailDrive?.seikai();selected=state.current;render();if(state.pending)centerMap();showReward();return;}window.RailDrive?.retry();$('feedback').textContent='もういちど やってみよう。だいじょうぶ！';entry='';}else if(entry.length<2)entry=entry==='0'?value:entry+value;$('answer').textContent=entry||'?';}
$('keypad').innerHTML=['1','2','3','4','5','6','7','8','9','clear','0','submit'].map(v=>`<button data-key="${v}" class="${v==='submit'?'action submit':v==='clear'?'action':''}" aria-label="${v==='clear'?'1けた けす':v==='submit'?'けってい':v}">${v==='clear'?'けす':v==='submit'?'けってい':v}</button>`).join('');
$('keypad').onclick=e=>{const b=e.target.closest('[data-key]');if(b)key(b.dataset.key);};
$('next').onclick=()=>{if(conflict||!C.next(state))return;entry='';render();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(conflict||state.pending||state.mode===b.dataset.mode)return;state.mode=b.dataset.mode;state.problem=C.problem(state.mode);state.solved=false;entry='';render();});
function travelClick(e){if(conflict)return;const b=e.target.closest('[data-move],[data-target]');if(!b)return;if(b.dataset.move){if(!C.move(state,b.dataset.move))return;selected=state.current;centerMap();}else{if(!C.choose(state,b.dataset.target))return;selected=b.dataset.target;}render();}
$('directions').onclick=travelClick;$('map-selection').onclick=travelClick;$('use-credit').onclick=()=>{if(conflict||!C.build(state))return;selected=state.current;render();centerMap();showReward();};
function closeReward(){if(!giftMode&&C.needsStamp(state))return;$('reward').classList.remove('stamping');if(giftMode&&state.pending){giftMode=false;state.pending.gift=true;save();$('reward').close();showReward();return;}state.pending=null;$('reward').close();render();if(state.solved)$('next').focus();}
$('sound-test').onclick=async()=>{$('sound-test-status').textContent=window.RailDrive?await RailDrive.soundTest():'おとの しくみが 読みこめていません';};$('sound-toggle').onclick=()=>window.RailDrive?.toggleSound();$('reward-close').onclick=closeReward;$('reward-stamp').onclick=e=>{if(conflict||!e.target.closest('.stamp-pad')||!C.stamp(state,today()))return;save();window.RailDrive?.pon(R.stations[state.pending.station].reading);showReward(true);};$('reward').addEventListener('cancel',e=>{e.preventDefault();closeReward();});
$('collection-open').onclick=()=>{const got=C.earned(state);$('collection-grid').innerHTML=cards.map(c=>cardHTML(c,got.includes(c.id))).join('');$('collection-got').textContent=`${got.length} / ${cards.length}`;$('collection').showModal();};$('collection-close').onclick=()=>$('collection').close();
$('stamps-open').onclick=()=>{const got=new Set(C.opened(state)),seen=new Set();$('stamps-book').innerHTML=R.lines.map(l=>{const ids=l.stations.filter(id=>!seen.has(id)&&seen.add(id));return `<section class="stamp-line" style="--line:${l.color}"><h3>${ruby(l.name)} <small>${ids.filter(id=>got.has(id)).length} / ${ids.length}</small></h3><div class="stamp-grid">${ids.map(id=>got.has(id)?`<figure class="stamp-slot got"><div class="stamp-inked">${stampSVG(id)}</div><figcaption>${stampDay(id)}</figcaption></figure>`:`<figure class="stamp-slot"><div class="stamp-empty"><ruby>${esc(R.stations[id].name)}<rt>${esc(R.stations[id].reading)}</rt></ruby></div><figcaption>まだ</figcaption></figure>`).join('')}</div></section>`;}).join('');$('stamps-got').textContent=`${got.size} / ${Object.keys(R.stations).length}`;$('stampbook').showModal();};$('stamps-close').onclick=()=>$('stampbook').close();
$('parent').onclick=()=>{resetQuiz();$('reset-status').textContent='';$('stats').innerHTML=`<p>たしざん ${state.stats.add}問 ／ ひきざん ${state.stats.sub}問<br>合計 ${state.total}問（答え直しを含む）<br>${C.opened(state).length}駅・${state.edges.length}区間 開通<br>未使用の開通回数：${C.credits(state)}駅分</p>`;$('parents').showModal();};$('parent-close').onclick=()=>$('parents').close();
$('app-version').textContent=document.querySelector('meta[name="app-version"]')?.content||'不明';
$('update-app').onclick=async()=>{
const button=$('update-app');button.disabled=true;$('update-status').textContent='最新版を確認しています…';
try{
const url=new URL('index.html',document.baseURI);url.searchParams.set('update',Date.now().toString());
const response=await fetch(url.href,{cache:'no-store'});
if(!response.ok)throw Error('通信エラー '+response.status);
const html=await response.text();
const version=new DOMParser().parseFromString(html,'text/html').querySelector('meta[name="app-version"]')?.content;
if(!version)throw Error('更新データを確認できませんでした');
$('update-status').textContent='最新版を開きます。記録はそのまま残ります。';
location.replace(url.href);
}catch(error){button.disabled=false;$('update-status').textContent='更新できませんでした：'+error.message+'。通信を確認して、もう一度お試しください。';}
};
let resetAnswer=null;
function resetQuiz(){const a=12+Math.floor(Math.random()*8),b=3+Math.floor(Math.random()*7);resetAnswer=a*b;$('reset-question').textContent=`${a} × ${b} =`;$('reset-answer').value='';let undo=false;try{const raw=localStorage.getItem(C.RESET_KEY);undo=raw!==null&&C.valid(JSON.parse(raw));}catch(e){}$('reset-undo').hidden=!undo;$('reset-app').disabled=$('reset-undo').disabled=conflict;}
$('reset-app').onclick=()=>{if(conflict)return;if(Number($('reset-answer').value)!==resetAnswer||!/^\d+$/.test($('reset-answer').value.trim())){$('reset-status').textContent='確認の答えがちがいます。';resetQuiz();return;}if(!confirm('正解数・開通した駅・車両カードを消して、玖波駅から最初にもどします。よろしいですか？')){resetQuiz();return;}try{localStorage.setItem(C.RESET_KEY,localStorage.getItem(C.KEY)??JSON.stringify(state));}catch(e){$('reset-status').textContent='リセット前の記録を残せないため、リセットを中止しました。先にバックアップを保存してください。';return;}state=C.fresh();corrupt=false;migrated=false;entry='';selected=state.current;render();centerMap();resetQuiz();$('reset-status').textContent='最初からに もどしました。';};
$('reset-undo').onclick=()=>{if(conflict)return;try{const data=JSON.parse(localStorage.getItem(C.RESET_KEY));if(!C.valid(data))throw Error();C.upgradeCards(data);if(!confirm('リセット前の記録に戻しますか？ リセットのあとに進めた分は消えます。'))return;state=data;corrupt=false;entry='';selected=state.current;render();if(!conflict&&storageOK)localStorage.removeItem(C.RESET_KEY);centerMap();$('parents').close();showReward();}catch(e){$('reset-status').textContent='リセット前の記録を読み込めませんでした。';}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='keisan-tetsudo-v2-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('ファイルが大きすぎます。');let data=JSON.parse(await f.text());if(data.version===1)data=C.migrate(data);if(!C.valid(data))throw Error('有効なバックアップではありません。');C.upgradeCards(data);if(!confirm('現在の記録を、このバックアップの記録に置き換えますか？'))return;state=data;corrupt=false;conflict=false;lastSaved=localStorage.getItem(C.KEY);entry='';selected=state.current;render();centerMap();$('parents').close();showReward();}catch(err){$('import-status').textContent='復元できませんでした。'+err.message;}finally{e.target.value='';}};
$('zoom-in').onclick=()=>zoom(.7);$('zoom-out').onclick=()=>zoom(1/.7);$('map-current').onclick=()=>centerMap();$('map-all').onclick=mapAll;
let normalCamera=null;
$('map-full').onclick=()=>{const world=document.querySelector('.world'),on=!world.classList.contains('map-expanded');if(on)normalCamera={...camera};world.classList.toggle('map-expanded',on);$('map-full').textContent=on?'もどす':'大きく見る';if(on)mapAll();else{camera={...normalCamera};normalCamera=null;camera.height=camera.width/mapAspect();updateCamera();}};
const pointers=new Map();let gesture=null,moved=false;
$('map').addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('map').setPointerCapture(e.pointerId);moved=false;gesture={x:e.clientX,y:e.clientY,camera:{...camera},distance:pointers.size===2?Math.hypot(...(()=>{const p=[...pointers.values()];return[p[0].x-p[1].x,p[0].y-p[1].y];})()):null};});
$('map').addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(gesture.distance){zoom(gesture.distance/d);gesture.distance=d;moved=true;}return;}const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;camera.x=gesture.camera.x-dx*camera.width/$('map').clientWidth;camera.y=gesture.camera.y-dy*camera.height/$('map').clientHeight;updateCamera();});
$('map').addEventListener('pointerup',e=>{if(!moved){const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-station]');if(node)showSelection(node.dataset.station);}pointers.delete(e.pointerId);gesture=null;});$('map').addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;});$('map').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.station){e.preventDefault();showSelection(e.target.dataset.station);}});
$('map').addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();zoom(e.deltaY>0?1.08:.92);}},{passive:false});
function resizeMap(){if(document.querySelector('.world').classList.contains('map-expanded'))mapAll();else{const cy=camera.y+camera.height/2;camera.height=camera.width/mapAspect();camera.y=cy-camera.height/2;updateCamera();}}
window.addEventListener('resize',resizeMap);
if(window.visualViewport)window.visualViewport.addEventListener('resize',resizeMap);
new ResizeObserver(resizeMap).observe($('map-wrap'));
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]')||e.target.closest('#map,button,input,a'))return;if(e.key==='Enter'&&state.solved){e.preventDefault();$('next').click();}else if(/^\d$/.test(e.key)){e.preventDefault();key(e.key);}else if(e.key==='Backspace'){e.preventDefault();key('clear');}else if(e.key==='Enter'){e.preventDefault();key('submit');}});
$('legend').innerHTML=R.lines.map(l=>`<span><i style="--line:${l.color}"></i>${l.name}</span>`).join('');centerMap();render();showReward();
