'use strict';
const $=id=>document.getElementById(id),C=RailMath,R=RailRoutes,cards=RailCards;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// People: the profile list (names set in おうちの方へ, and this device's id) is kept apart from each person's record. Every launch asks だれが あそぶ？. Colors belong to the five places, not to names. A broken list is left as it is and not overwritten.
const COLORS={p1:'#2f7fd8',p2:'#ec6fa3',p3:'#f2c230',p4:'#b49be0',guest:'#3fae6a'},OP_LABELS={plus:['＋','たしざん'],minus:['−','ひきざん'],times:['×','かけざん'],divide:['÷','わりざん']};
const KIND_NAMES={add5:'5までの たしざん',sub5:'5までの ひきざん',add:'10までの たしざん',sub:'10までの ひきざん',add20:'くりあがりの たしざん（20まで）',sub20:'くりさがりの ひきざん（20まで）',add2:'2けたの たしざん',sub2:'2けたの ひきざん',mul:'くく（かけざん）',mul21:'2けた×1けたの かけざん',div:'わりざん（くくの ぎゃく）'};
let profiles=C.freshProfiles(),profilesBroken=false,profilesRaw=null;
try{profilesRaw=localStorage.getItem(C.PROFILES_KEY);}catch(e){}
if(profilesRaw!==null){let parsed=null;try{parsed=JSON.parse(profilesRaw);}catch(e){}if(C.validProfiles(parsed))profiles=parsed;else profilesBroken=true;}else saveProfiles();
function saveProfiles(){if(profilesBroken)return false;try{localStorage.setItem(C.PROFILES_KEY,JSON.stringify(profiles));return true;}catch(e){return false;}}
// Save keeper: the chosen person's record, the copy kept before a reset and the backup file name go through here (the sound setting in drive.js is per device and stays out). The old v2 record is not read or changed.
const store={who:null,get key(){return C.recordKey(this.who);},get resetKey(){return C.resetKey(this.who);},get backupName(){return `keisan-tetsudo-${this.who}-backup.json`;},read(){return localStorage.getItem(this.key);},write(s){const encoded=JSON.stringify(s);localStorage.setItem(this.key,encoded);return encoded;},mine(e){return e.key===this.key;},keepBeforeReset(fallback){localStorage.setItem(this.resetKey,this.read()??fallback);},beforeReset(){const data=JSON.parse(localStorage.getItem(this.resetKey));return C.valid(data)&&data.version===3?data:null;},dropBeforeReset(){localStorage.removeItem(this.resetKey);}};
// Until someone is chosen, the screen shows an unsaved fresh record behind だれが あそぶ？.
let state=C.freshRecord('guest'),entry='',corrupt=false,storageOK=true,conflict=false,lastSaved=null;
function load(who){store.who=who;loadRest(who);streak={mode:null,n:0};usedAt={};sections=0;transferDue=false;state=C.freshRecord(who);entry='';corrupt=false;conflict=false;storageOK=true;lastSaved=null;try{const raw=store.read();lastSaved=raw;if(raw!==null){const parsed=JSON.parse(raw);if(C.valid(parsed)&&parsed.version===3)state=parsed;else corrupt=true;}}catch(e){storageOK=false;corrupt=true;}if(!corrupt){C.upgradeCards(state);if(state.target===null&&!state.pending)C.aim(state,null);}selected=state.current;}
function save(){if(store.who&&!corrupt&&!conflict){try{if(store.read()!==lastSaved){conflict=true;}else{if(JSON.stringify(state)!==lastSaved)state.at=Date.now();lastSaved=store.write(state);storageOK=true;}}catch(e){storageOK=false;}}
$('save-status').textContent=conflict?'別の画面で記録が更新されました。この画面を再読み込みしてください。':corrupt?'保存記録を読み込めません。元の記録を残して、今回は保存せず遊べます。':!storageOK?'保存できません。閉じる前にバックアップを保存してください。':profilesBroken?'なまえの記録を読み込めません。元の記録を残して、なまえは仮のまま遊べます。':'✓ つづきは このブラウザに ほぞんされるよ';
$('save-status').hidden=!(conflict||corrupt||!storageOK||profilesBroken);
$('keypad').querySelectorAll('button').forEach(b=>b.disabled=conflict);$('next').disabled=conflict;}
window.addEventListener('storage',e=>{if(store.who&&store.mine(e)&&e.newValue!==lastSaved){conflict=true;save();}if(e.key===C.PROFILES_KEY&&!profilesBroken){try{const p=JSON.parse(e.newValue);if(C.validProfiles(p)&&p.device===profiles.device){profiles=p;renderBadge();}}catch(err){}}});
let camera={x:0,y:0,width:1150,height:700},selected=state.current;
function mapAspect(){const w=$('map-wrap').clientWidth,h=$('map-wrap').clientHeight;return w>0&&h>0?w/h:camera.width/camera.height;}
function centerMap(id=state.current){const s=R.stations[id];const aspect=mapAspect();camera.width=1050;camera.height=camera.width/aspect;camera.x=s.x-camera.width/2;camera.y=s.y-camera.height/2;updateCamera();}
function updateCamera(){const b=R.bounds;camera.x=Math.max(b.x-camera.width/4,Math.min(camera.x,b.x+b.width-camera.width*.75));camera.y=Math.max(b.y-camera.height/4,Math.min(camera.y,b.y+b.height-camera.height*.75));$('map').setAttribute('viewBox',`${camera.x} ${camera.y} ${camera.width} ${camera.height}`);$('map').querySelectorAll('.minor-label').forEach(t=>t.style.display=camera.width>2200?'none':'');$('map').querySelectorAll('.station-reading').forEach(t=>t.style.display=camera.width>1500?'none':'');
const scale=camera.width/Math.max(1,$('map').clientWidth),occupied=[];
const labels=[...$('map').querySelectorAll('.major-label')].sort((a,b)=>{const priority=t=>t.parentNode.dataset.station===state.current?0:cards.some(c=>!c.first&&c.station===t.parentNode.dataset.station)?1:2;return priority(a)-priority(b);});
for(const t of labels){const font=Math.max(27,12*scale);t.setAttribute('font-size',font);t.style.display='';if(camera.width>2200){const x=Number(t.getAttribute('x')),y=Number(t.getAttribute('y')),w=t.textContent.length*font,box={x:x-w/2,y:y-font,w,h:font*1.25};if(occupied.some(b=>box.x<b.x+b.w+8*scale&&box.x+box.w>b.x&&box.y<b.y+b.h+3*scale&&box.y+box.h>b.y)){t.style.display='none';}else occupied.push(box);}}
}

function zoom(f){const w=Math.max(650,Math.min(6500,camera.width*f)),ratio=w/camera.width;camera.x+=camera.width*(1-ratio)/2;camera.y+=camera.height*(1-ratio)/2;camera.height*=ratio;camera.width=w;updateCamera();}
function mapAll(){const pad=110,b={x:R.bounds.x-pad,y:R.bounds.y-pad,width:R.bounds.width+pad*2,height:R.bounds.height+pad*2},aspect=mapAspect();camera.width=Math.max(b.width,b.height*aspect);camera.height=camera.width/aspect;camera.x=b.x+(b.width-camera.width)/2;camera.y=b.y+(b.height-camera.height)/2;updateCamera();}
function renderMap(){const unlocked=new Set(C.opened(state)),major=new Set([...cards.map(c=>c.station),'玖波','大竹','横川','海田市','広島','櫛ケ浜','あき亀山']);
let html='<defs><linearGradient id="sea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#bfe2ec"/><stop offset=".5" stop-color="#9fd0e1"/></linearGradient></defs><rect x="-2000" y="-3000" width="10000" height="7000" fill="#eef0e2"/><path d="M-100 1500 Q1500 1350 2300 1270 T3500 1800 T5700 2000 V3500 H-100Z" fill="url(#sea)" stroke="#fff" stroke-width="6" vector-effect="non-scaling-stroke"/><text x="1600" y="1640" font-size="58" letter-spacing="18" fill="#84a8ad" stroke="none">瀬 戸 内 海</text>';
for(const e of R.edges){const a=R.stations[e.a],b=R.stations[e.b],line=R.lines.find(l=>l.id===e.line),open=state.edges.includes(e.id),target=[e.a,e.b].includes(state.current)&&[e.a,e.b].includes(state.target);html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${line.color}" vector-effect="non-scaling-stroke" stroke-width="${open?4:1.5}" opacity="${open?1:.22}" ${open?'':'stroke-dasharray="8 9"'}/>`;if(target)html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#e3aa40" vector-effect="non-scaling-stroke" stroke-width="7" opacity=".55"/>`;}
for(const s of Object.values(R.stations)){const active=s.id===state.current,open=unlocked.has(s.id),branch=C.adjacent(s.id).length>2,above=['kabe','geibi','gantoku'].some(id=>R.lines.find(l=>l.id===id).stations.slice(1,-1).includes(s.id));
const dy=above?-27:-27;html+=`<g class="station-node" data-station="${s.id}" role="button" tabindex="0" aria-label="${s.name} ${open?'開通済み':'未開通'}"><circle cx="${s.x}" cy="${s.y}" r="30" fill="transparent"/>${active?`<circle class="current-halo" cx="${s.x}" cy="${s.y}" r="27" fill="#f5a524" opacity=".35"/>`:''}<circle cx="${s.x}" cy="${s.y}" r="${branch?13:10}" fill="${open?'#193d47':'#fff'}" stroke="${open?'#193d47':'#a8bbae'}" stroke-width="4"/><text class="${major.has(s.id)?'major-label':'minor-label'}" x="${s.x}" y="${s.y+dy}" text-anchor="middle" font-size="${major.has(s.id)?27:22}" font-weight="${major.has(s.id)?800:600}" fill="${open?'#193d47':'#607b6e'}">${s.name}${cards.some(c=>!c.first&&c.station===s.id)?' ▣':''}</text><text class="station-reading" x="${s.x}" y="${s.y+34}" text-anchor="middle" font-size="12" fill="#728779">${s.reading}</text></g>`;}
html+='<text x="3890" y="70" font-size="20" fill="#8e678a">芸備線は三次方面へつづく（今回は下深川まで）</text>';
$('map').innerHTML=html;updateCamera();$('station-count').textContent=unlocked.size;$('collection-count').textContent=`${C.earned(state).length}/${cards.length}`;showSelection(selected);}
function showSelection(id){selected=id;if(id===state.current){$('map-selection').textContent='';return;}const s=R.stations[id],open=C.opened(state).includes(id),next=C.adjacent(state.current).some(e=>e.to===id);$('map-selection').innerHTML=`<strong>${s.name}</strong><span>${s.reading}</span>${open&&next?`<button data-target="${id}">この駅へ すすむ</button>`:''}${open?`<button data-move="${id}">この駅へ ワープ</button>`:next?`<button data-target="${id}">この駅へ のばす</button>`:'<span>となりの駅から、順番に開通しよう</span>'}`;}
const rubyWords=Object.fromEntries([...Object.values(R.stations),...R.lines].map(s=>[s.name,s.reading])),rubyRe=new RegExp(Object.keys(rubyWords).sort((a,b)=>b.length-a.length).join('|'),'g');
const ruby=text=>esc(text).replace(rubyRe,w=>`<ruby>${w}<rt>${rubyWords[w]}</rt></ruby>`);
function cardHTML(c,unlocked=true){return `<article class="card ${unlocked?'':'locked'}">${unlocked?`<img src="${c.image}" alt="${esc(c.name)}の実写写真" loading="lazy">`:'<div class="placeholder" aria-hidden="true"><span class="mystery-train">🚃</span><span class="mystery-mark">？</span></div>'}<div class="card-body"><div class="eyebrow">${c.first?'はじめての かいつうの きねんカード':`${ruby(c.station)}えきの きねんカード`}</div><h3>${unlocked?esc(c.name):'？？？？？'}</h3><p>${unlocked?ruby(c.fact):c.first?`ひみつの でんしゃ。${ruby(c.station)}から さいしょの 5もんを とくと あえるよ。`:`ひみつの でんしゃ。${ruby(c.station)}えきまで かいつうすると あえるよ。`}</p>${unlocked?`<p class="credit">写真：${esc(c.credit)} / ${esc(c.license)} · <a href="sources.html#${c.id}" target="_blank" rel="noopener">出典</a></p>`:''}</div></article>`;}
// Station stamps are drawn in SVG. Look D, chosen on 2026-09-26 from a side-by-side of four: the thick ring of the first version (in the colours of every line through the station) with a big reading and name that stay readable in the stamp book, and the scenery pictures of the retro mock-up underneath. Stations with a landmark get their own picture (STAMP_LANDMARK).
let stampSeq=0;
const STAMP_PAPER='#f7f4ec',STAMP_LANDMARK={'宮島口':'torii','広島':'castle','岩国':'hebi','川西':'kintai','西岩国':'nishiiwakuni','廿日市':'kendama','呉':'submarine','三原':'tako','竹原':'machiya','忠海':'rabbit','西条':'taru','柳井':'kingyo','大畠':'ohashi','横川':'bus','徳山':'factory','和木':'hachi','玖波':'ie','向洋':'car','海田市':'kaidou','瀬野':'hoki','白市':'akagawara','本郷':'hikouki','櫛ケ浜':'fune','周防花岡':'kitsune','生野屋':'michishirube','周防久保':'shukuba','大河内':'tanbo','勝間':'yama','高水':'tsuru','米川':'kawa','周防高森':'ushi','玖珂':'shiro','欽明路':'touge','柱野':'yamakawa'};
const stampTrain=(x,y,ink)=>`<rect x="${x}" y="${y}" width="50" height="14" rx="2.5" fill="${ink}"/>${[4,14,24].map(d=>`<rect x="${x+d}" y="${y+3}" width="7" height="4.5" rx="1" fill="${STAMP_PAPER}"/>`).join('')}<rect x="${x+34}" y="${y+3}" width="9" height="4.5" rx="1.2" fill="${STAMP_PAPER}"/><path d="M${x+10} ${y}l5-6 5 6" fill="none" stroke="${ink}" stroke-width="1.5"/>`;
const stampRail=ink=>`<path d="M44 78H156" stroke="${ink}" stroke-width="1.8"/><path d="M52 78v3M64 78v3M76 78v3M88 78v3M100 78v3M112 78v3M124 78v3M136 78v3M148 78v3" stroke="${ink}" stroke-width="1.2"/>`;
const stampGrille=ink=>(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${STAMP_PAPER}"/>${Array.from({length:Math.floor(w/3)},(_,i)=>`<path d="M${x+1.5+i*3} ${y}v${h}" stroke="${ink}" stroke-width="1.1"/>`).join('')}`;
const STAMP_ART={
sea:ink=>`<path d="M44 70Q58 56 75 66T115 61T145 68T156 74" fill="none" stroke="${ink}" stroke-width="1.5" opacity=".45"/><path d="M40 76Q52 70 66 76T96 76T126 76T156 76" fill="none" stroke="${ink}" stroke-width="1.6" stroke-linecap="round"/><path d="M46 82Q60 77 76 82T108 82T140 82" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>${stampTrain(64,56,ink)}<path d="M74 70v8M104 70v8" stroke="${ink}" stroke-width="1.8"/><path d="M126 48Q130 44 134 48Q138 44 142 48" fill="none" stroke="${ink}" stroke-width="1.3"/>`,
hills:ink=>`<path d="M42 72L60 52 72 62 92 42 112 64 126 54 158 74" fill="none" stroke="${ink}" stroke-width="1.8" stroke-linejoin="round" opacity=".55"/><path d="M86 49l6-7 6 7" fill="none" stroke="${ink}" stroke-width="1.2"/><circle cx="140" cy="44" r="5" fill="none" stroke="${ink}" stroke-width="1.4"/>${stampTrain(75,62,ink)}${stampRail(ink)}`,
town:ink=>`<rect x="44" y="54" width="15" height="24" fill="${ink}" opacity=".8"/><rect x="61" y="60" width="12" height="18" fill="${ink}" opacity=".6"/><rect x="127" y="58" width="13" height="20" fill="${ink}" opacity=".6"/><rect x="142" y="52" width="15" height="26" fill="${ink}" opacity=".8"/>${[50,54,146,150].map(x=>`<rect x="${x}" y="58" width="2.5" height="3" fill="${STAMP_PAPER}"/><rect x="${x}" y="64" width="2.5" height="3" fill="${STAMP_PAPER}"/>`).join('')}${stampTrain(75,62,ink)}${stampRail(ink)}`,
torii:ink=>`<path d="M66 52Q100 47 134 52L132 56Q100 51 68 56Z" fill="${ink}"/><rect x="72" y="58" width="56" height="2.8" fill="${ink}"/><rect x="70" y="66" width="60" height="2.5" fill="${ink}"/><rect x="79" y="57" width="6" height="25" fill="${ink}"/><rect x="115" y="57" width="6" height="25" fill="${ink}"/><rect x="72" y="68" width="4" height="14" fill="${ink}"/><rect x="124" y="68" width="4" height="14" fill="${ink}"/><path d="M45 82Q72 76 100 82T155 82" fill="none" stroke="${ink}" stroke-width="1.8" stroke-linecap="round"/>`,
kintai:ink=>`<path d="M116 54Q136 32 160 50" fill="none" stroke="${ink}" stroke-width="1.6" opacity=".6"/><rect x="135" y="38" width="11" height="5" fill="${ink}" opacity=".8"/><path d="M133 38h15l-3-3.5h-9z" fill="${ink}" opacity=".8"/><rect x="137.5" y="31" width="6" height="3.5" fill="${ink}" opacity=".8"/><path d="M136 31h9l-2-2.5h-5z" fill="${ink}" opacity=".8"/>${[[42,65,68,64,58],[65,88,64,64,38],[88,112,64,64,38],[112,135,64,64,38],[135,158,64,68,58]].map(([a,b,ya,yb,c])=>`<path d="M${a} ${ya}Q${(a+b)/2} ${c} ${b} ${yb}" fill="none" stroke="${ink}" stroke-width="3.2"/><path d="M${a} ${ya-4}Q${(a+b)/2} ${c-4} ${b} ${yb-4}" fill="none" stroke="${ink}" stroke-width="1"/><path d="M${a+2} ${ya+5}Q${(a+b)/2} ${c+7} ${b-2} ${yb+5}" fill="none" stroke="${ink}" stroke-width="1.4"/>${[.2,.35,.5,.65,.8].map(t=>{const q=(y0,y1,k)=>(1-t)*(1-t)*y0+2*t*(1-t)*k+t*t*y1,x=a+(b-a)*t;return `<path d="M${x} ${q(ya,yb,c)}V${q(ya+5,yb+5,c+7)}" stroke="${ink}" stroke-width=".9"/>`;}).join('')}`).join('')}${[65,88,112,135].map(x=>`<path d="M${x-3.5} 64h7l2.5 16h-12z" fill="${ink}"/>`).join('')}<path d="M40 84Q52 79 64 84T88 84T112 84T136 84T160 84" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
nishiiwakuni:ink=>`<path d="M54 58L64 48H136L146 58Z" fill="${ink}"/><path d="M80 48L100 39 120 48Z" fill="${ink}"/><rect x="60" y="58" width="80" height="22" fill="${ink}"/><rect x="58" y="57.3" width="84" height="1.4" fill="${STAMP_PAPER}"/>${[[66,68],[84,63],[95.5,63],[107,63],[125,68]].map(([x,y])=>`<path d="M${x} 80V${y+4.5}a4.5 4.5 0 0 1 9 0V80Z" fill="${STAMP_PAPER}"/>`).join('')}<path d="M44 82H156" stroke="${ink}" stroke-width="1.8"/>`,
kendama:ink=>`<path d="M100 34l2.4 12h-4.8z" fill="${ink}"/><rect x="97" y="46" width="6" height="30" rx="1.5" fill="${ink}"/><rect x="84" y="54" width="32" height="4" rx="2" fill="${ink}"/><path d="M76 49h18a9 9 0 0 1-18 0z" fill="${ink}"/><path d="M108 50h14a7 7 0 0 1-14 0z" fill="${ink}"/><path d="M91 76h18a9 7 0 0 1-18 0z" fill="${ink}"/><path d="M103 66Q128 74 133 53" fill="none" stroke="${ink}" stroke-width="1"/><circle cx="136" cy="44" r="10" fill="${ink}"/><path d="M130.5 40.5a6.5 6.5 0 0 1 5.5-3" fill="none" stroke="${STAMP_PAPER}" stroke-width="2" stroke-linecap="round"/><path d="M58 46l2 5 5 1.5-5 1.5-2 5-2-5-5-1.5 5-1.5z" fill="${ink}" opacity=".6"/><path d="M66 68l1.4 3 3 1-3 1-1.4 3-1.4-3-3-1 3-1z" fill="${ink}" opacity=".45"/>`,submarine:ink=>`<path d="M46 69Q46 61 62 61H132Q146 61 153 66V72Q146 77 132 77H62Q46 77 46 69Z" fill="${ink}"/><path d="M149 65L158 56V81L149 73Z" fill="${ink}"/><path d="M82 61V50Q82 46 86 46H98Q101 46 102 49L105 61Z" fill="${ink}"/><path d="M75 54H109" stroke="${ink}" stroke-width="2.4" stroke-linecap="round"/><path d="M89 46V40M95 46V42" stroke="${ink}" stroke-width="1.4"/><path d="M58 68H140" stroke="${STAMP_PAPER}" stroke-width=".9" opacity=".7"/><path d="M40 83Q52 78 64 83T88 83T112 83T136 83T160 83" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
tako:ink=>`${['M86 62Q72 69 70 79Q76 84 80 77','M91 65Q84 76 88 83','M100 66Q98 78 102 83','M109 65Q116 76 112 83','M114 62Q128 69 130 79Q124 84 120 77'].map(d=>`<path d="${d}" fill="none" stroke="${ink}" stroke-width="5" stroke-linecap="round"/>`).join('')}<ellipse cx="100" cy="52" rx="17" ry="15" fill="${ink}"/><path d="M84 47Q100 41 116 47" fill="none" stroke="${STAMP_PAPER}" stroke-width="2.4"/><circle cx="93" cy="55" r="4" fill="${STAMP_PAPER}"/><circle cx="107" cy="55" r="4" fill="${STAMP_PAPER}"/><circle cx="93.5" cy="56" r="2" fill="${ink}"/><circle cx="107.5" cy="56" r="2" fill="${ink}"/><path d="M97 62q3 2.5 6 0" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.5" stroke-linecap="round"/><path d="M44 82Q54 77 64 82M136 82Q146 77 156 82" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
machiya:ink=>{const grille=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${STAMP_PAPER}"/>${Array.from({length:Math.floor(w/3)},(_,i)=>`<path d="M${x+1.5+i*3} ${y}v${h}" stroke="${ink}" stroke-width="1.1"/>`).join('')}`;return `<path d="M42 60L50 52H74L82 60Z" fill="${ink}"/><rect x="47" y="60" width="30" height="21" fill="${ink}"/>${grille(51,64,12,10)}<path d="M84 48L91 40H109L116 48Z" fill="${ink}"/><rect x="87" y="48" width="26" height="9" fill="${ink}"/>${grille(91,50,18,5)}<path d="M79 61L85 56H115L121 61Z" fill="${ink}"/><rect x="83" y="61" width="34" height="20" fill="${ink}"/>${grille(87,65,15,11)}<path d="M118 60L126 52H150L158 60Z" fill="${ink}"/><rect x="123" y="60" width="30" height="21" fill="${ink}"/>${grille(137,64,12,10)}<path d="M40 82H160" stroke="${ink}" stroke-width="1.8"/>`;},
rabbit:ink=>`<path d="M122 66Q134 48 150 56Q158 60 160 66Z" fill="${ink}" opacity=".45"/><path d="M40 70Q48 66 56 70T72 70M128 70Q136 66 144 70T160 70" fill="none" stroke="${ink}" stroke-width="1.3" opacity=".6"/><ellipse cx="94" cy="70" rx="17" ry="12" fill="${ink}"/><circle cx="111" cy="58" r="9.5" fill="${ink}"/><ellipse cx="106" cy="42" rx="3.6" ry="11" transform="rotate(-12 106 42)" fill="${ink}"/><ellipse cx="114" cy="42" rx="3.6" ry="11" transform="rotate(10 114 42)" fill="${ink}"/><circle cx="114" cy="56" r="1.8" fill="${STAMP_PAPER}"/><circle cx="77" cy="67" r="4" fill="${ink}"/><path d="M40 83H160" stroke="${ink}" stroke-width="1.8"/><path d="M58 82q3-6 6 0M136 82q3-7 6 0M146 82q2-5 4 0" fill="none" stroke="${ink}" stroke-width="1.3"/>`,
kingyo:ink=>{const fish=t=>`<g transform="${t}"><path d="M96 38V46" stroke="${ink}" stroke-width="1.2"/><path d="M114 60L131 47Q126 60 131 73Z" fill="${ink}"/><path d="M90 47Q97 39 105 47Z" fill="${ink}"/><ellipse cx="96" cy="60" rx="21" ry="14" fill="${ink}"/>${[88,98,108].map(x=>`<path d="M${x} 47Q${x-4} 60 ${x} 73" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.1"/>`).join('')}<circle cx="81" cy="56" r="4" fill="${STAMP_PAPER}"/><circle cx="80.5" cy="56.5" r="2" fill="${ink}"/><path d="M92 74v5M100 74v5" stroke="${ink}" stroke-width="1.4"/></g>`;return `<path d="M44 38Q100 34 156 38" fill="none" stroke="${ink}" stroke-width="1.3"/>${fish('translate(8 0)')}${fish('translate(56 40) scale(.5) translate(-96 -38)')}`;},
ohashi:ink=>`<path d="M132 70Q144 52 162 58V84H132Z" fill="${ink}" opacity=".35"/><path d="M38 70Q44 56 58 60V84H38Z" fill="${ink}" opacity=".35"/><rect x="40" y="55" width="120" height="3" fill="${ink}"/><rect x="40" y="64" width="120" height="2" fill="${ink}"/><path d="M40 64${Array.from({length:15},(_,i)=>`L${44+i*8} ${i%2?64:57}`).join('')}" fill="none" stroke="${ink}" stroke-width="1.3"/>${[70,100,130].map(x=>`<path d="M${x-2.5} 66h5l1.5 17h-8z" fill="${ink}"/>`).join('')}<path d="M40 84Q52 79 64 84T88 84T112 84T136 84T160 84" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
bus:ink=>`<path d="M60 44H138Q142 44 142 47V49H58V47Q58 44 60 44Z" fill="${ink}"/>${[62,84,106,128,140].map(x=>`<path d="M${x} 49V62" stroke="${ink}" stroke-width="2"/>`).join('')}<path d="M66 60h14M88 60h14M110 60h14" stroke="${ink}" stroke-width="2.4"/><path d="M56 62H144V71Q144 73 142 73H58Q56 73 56 71Z" fill="${ink}"/><path d="M44 63H56V73H46Q44 73 44 71Z" fill="${ink}"/><path d="M56 55l6 5" stroke="${ink}" stroke-width="1.6"/>${[70,128].map(x=>`<circle cx="${x}" cy="76" r="8" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2.4"/>${[0,45,90,135].map(a=>`<path d="M${x} 69V83" stroke="${ink}" stroke-width="1" transform="rotate(${a} ${x} 76)"/>`).join('')}<circle cx="${x}" cy="76" r="2" fill="${ink}"/>`).join('')}<path d="M40 84.5H160" stroke="${ink}" stroke-width="1.4"/>`,
factory:ink=>`<path d="M58 40a7 7 0 1 0 8 9a5.5 5.5 0 1 1-8-9z" fill="${ink}"/><path d="M80 42l1 2 2 1-2 1-1 2-1-2-2-1 2-1z" fill="${ink}" opacity=".6"/><path d="M138 40q4-4 0-8t2-8" fill="none" stroke="${ink}" stroke-width="1.4" opacity=".55"/><rect x="136" y="42" width="4" height="40" fill="${ink}"/><rect x="70" y="46" width="7" height="36" fill="${ink}"/><rect x="117" y="52" width="6" height="30" fill="${ink}"/><rect x="42" y="64" width="30" height="18" fill="${ink}"/><path d="M79 82V66a10 6 0 0 1 20 0V82Z" fill="${ink}"/><path d="M99 82V70a8 5 0 0 1 16 0V82Z" fill="${ink}"/><rect x="123" y="62" width="34" height="20" fill="${ink}"/><path d="M40 60H160" stroke="${ink}" stroke-width="1"/><path d="M70 52h7M70 58h7M70 64h7M117 58h6M117 64h6" stroke="${STAMP_PAPER}" stroke-width=".9"/>${[[47,68],[53,68],[59,68],[65,68],[50,74],[62,74],[73.5,50],[73.5,70],[86,70],[92,74],[89,78],[105,74],[110,78],[120,56],[120,70],[138,48],[138,60],[128,66],[134,66],[146,66],[152,66],[128,74],[140,74],[150,74]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="1.1" fill="${STAMP_PAPER}"/>`).join('')}`,
hachi:ink=>`<ellipse cx="97" cy="46" rx="8" ry="12" transform="rotate(-22 97 46)" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2"/><ellipse cx="111" cy="47" rx="7" ry="10.5" transform="rotate(18 111 47)" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2"/><path d="M121 62l8 2.5-8 3z" fill="${ink}"/><ellipse cx="102" cy="64" rx="20" ry="14" fill="${ink}"/><path d="M96 51Q92 64 96 77M108 51Q104 64 108 77" fill="none" stroke="${STAMP_PAPER}" stroke-width="3.2"/><path d="M78 51Q74 41 68 39M84 50Q87 40 93 37" fill="none" stroke="${ink}" stroke-width="1.6" stroke-linecap="round"/><circle cx="68" cy="39" r="2.6" fill="${ink}"/><circle cx="93" cy="37" r="2.6" fill="${ink}"/><circle cx="80" cy="61" r="11" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1.5"/><circle cx="76.5" cy="59" r="3.6" fill="${STAMP_PAPER}"/><circle cx="76" cy="59.5" r="1.8" fill="${ink}"/><path d="M75 66q3 2.5 6 0" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.5" stroke-linecap="round"/><path d="M132 50q8-9 18-2" fill="none" stroke="${ink}" stroke-width="1.3" stroke-dasharray="2 3" opacity=".6"/>${[0,72,144,216,288].map(a=>`<circle cx="143" cy="67" r="3" transform="rotate(${a} 143 71)" fill="${ink}" opacity=".6"/>`).join('')}<circle cx="143" cy="71" r="2" fill="${STAMP_PAPER}"/><path d="M143 75v8" stroke="${ink}" stroke-width="1.3"/><path d="M44 83Q56 79 68 83M132 83Q144 79 156 83" fill="none" stroke="${ink}" stroke-width="1.5" stroke-linecap="round"/>`,
ie:ink=>`<path d="M126 40q4-4 0-8t2-8" fill="none" stroke="${ink}" stroke-width="1.4" opacity=".55"/><rect x="118" y="38" width="8" height="14" fill="${ink}"/><path d="M60 58L100 32 140 58Z" fill="${ink}"/><circle cx="100" cy="47" r="4.5" fill="${STAMP_PAPER}"/><path d="M95.5 47h9M100 42.5v9" stroke="${ink}" stroke-width="1"/><rect x="68" y="57" width="64" height="25" fill="${ink}"/><path d="M66 58.6H134" stroke="${STAMP_PAPER}" stroke-width="1.2"/>${[75,113].map(x=>`<rect x="${x}" y="63" width="12" height="10" rx="1" fill="${STAMP_PAPER}"/><path d="M${x+6} 63v10M${x} 68h12" stroke="${ink}" stroke-width="1.2"/>`).join('')}<path d="M93 82V71a7 7 0 0 1 14 0V82Z" fill="${STAMP_PAPER}"/><circle cx="103.5" cy="76" r="1.3" fill="${ink}"/><circle cx="50" cy="62" r="9" fill="${ink}" opacity=".6"/><rect x="48.5" y="68" width="3" height="14" fill="${ink}" opacity=".6"/><path d="M146 44l-4-4a2.4 2.4 0 0 1 4-3.2a2.4 2.4 0 0 1 4 3.2z" fill="${ink}" opacity=".6"/><path d="M40 82.5H160" stroke="${ink}" stroke-width="1.8"/>`,
car:ink=>`<path d="M40 58h10M38 66h12M42 74h8" stroke="${ink}" stroke-width="1.8" stroke-linecap="round" opacity=".5"/><path d="M54 72Q54 64 62 63L76 61L88 50Q91 47 96 47H118Q124 47 128 51L138 61L150 63Q156 64 156 70V74Q156 76 154 76H56Q54 76 54 74Z" fill="${ink}"/><path d="M92 60L99 52H108V60Z" fill="${STAMP_PAPER}"/><path d="M112 52H118Q121 52 124 55L129 60H112Z" fill="${STAMP_PAPER}"/><path d="M110 62v11" stroke="${STAMP_PAPER}" stroke-width="1"/><path d="M100 65h5M116 65h5" stroke="${STAMP_PAPER}" stroke-width="1.4" stroke-linecap="round"/><rect x="149" y="65" width="5" height="3" rx="1" fill="${STAMP_PAPER}"/>${[76,136].map(x=>`<circle cx="${x}" cy="76" r="8" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="3"/><circle cx="${x}" cy="76" r="2.4" fill="${ink}"/>`).join('')}<path d="M40 85H160" stroke="${ink}" stroke-width="1.4"/>`,
kaidou:ink=>{const grille=stampGrille(ink);return `<path d="M44 50L52 42H96L104 50Z" fill="${ink}"/><rect x="48" y="50" width="52" height="10" fill="${ink}"/>${[54,67,80].map(x=>`<rect x="${x}" y="52.5" width="10" height="5" rx="2.5" fill="${STAMP_PAPER}"/>${[2.5,5,7.5].map(d=>`<path d="M${x+d} 52.5v5" stroke="${ink}" stroke-width=".9"/>`).join('')}`).join('')}<path d="M42 64L48 59H100L106 64Z" fill="${ink}"/><rect x="46" y="64" width="56" height="18" fill="${ink}"/>${grille(50,67,21,12)}<rect x="76" y="67" width="10" height="15" fill="${STAMP_PAPER}"/><path d="M76 67h10v5l-2.5-2-2.5 2-2.5-2-2.5 2z" fill="${ink}" opacity=".7"/>${grille(89,67,9,12)}<path d="M107 82V64l3-3 3 3V82Z" fill="${ink}"/><path d="M114 58L120 51H150L156 58Z" fill="${ink}"/><rect x="117" y="58" width="36" height="24" fill="${ink}"/>${grille(121,62,15,16)}<rect x="140" y="62" width="9" height="20" fill="${STAMP_PAPER}"/><path d="M40 82H160" stroke="${ink}" stroke-width="1.8"/>`;},
hoki:ink=>`<g transform="rotate(-8.5 100 70)"><path d="M30 84H170V104H30Z" fill="${ink}" opacity=".25"/><path d="M30 84H170" stroke="${ink}" stroke-width="1.8"/><path d="M78 50l7-8 7 8M81 42h8" fill="none" stroke="${ink}" stroke-width="1.4"/><path d="M110 50l7-8 7 8M113 42h8" fill="none" stroke="${ink}" stroke-width="1.4"/><rect x="56" y="50" width="92" height="24" rx="3" fill="${ink}"/><rect x="60" y="54" width="11" height="8" rx="1.5" fill="${STAMP_PAPER}"/><rect x="133" y="54" width="11" height="8" rx="1.5" fill="${STAMP_PAPER}"/><rect x="78" y="55" width="48" height="6" fill="${STAMP_PAPER}"/>${[82,86,90,94,98,102,106,110,114,118,122].map(x=>`<path d="M${x} 55v6" stroke="${ink}" stroke-width="1.3"/>`).join('')}<path d="M58 67H146" stroke="${STAMP_PAPER}" stroke-width="1.6"/>${[68,80,124,136].map(x=>`<circle cx="${x}" cy="77" r="5.5" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2.4"/><circle cx="${x}" cy="77" r="1.5" fill="${ink}"/>`).join('')}<path d="M40 56l6 5-6 5M47 56l6 5-6 5" fill="none" stroke="${ink}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></g>`,
taru:ink=>`<path d="M136 34q4-4 0-8t2-8" fill="none" stroke="${ink}" stroke-width="1.4" opacity=".55"/><path d="M131.5 72L133 36H139L140.5 72Z" fill="${ink}"/><path d="M133.2 40h5.6M133 46h6" stroke="${STAMP_PAPER}" stroke-width="1"/><path d="M42 66L48 60H78L84 66Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><rect x="45" y="66" width="36" height="16" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><path d="M116 67L122 62H152L158 67Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><rect x="119" y="67" width="36" height="15" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/>${[45,51,57,63,69,75,119,125,131,137,143,149].map(x=>`<path d="M${x} 82l5-5M${x} 77l5 5" stroke="${STAMP_PAPER}" stroke-width=".8"/>`).join('')}<path d="M81 49Q77 66 81 83H119Q123 66 119 49Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1.5"/><ellipse cx="100" cy="49" rx="19" ry="4.5" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2"/><path d="M79.5 56Q100 60 120.5 56M79.5 77Q100 81 120.5 77" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.6"/><rect x="91" y="61" width="18" height="13" rx="1.5" fill="${STAMP_PAPER}"/><text x="100" y="71.5" text-anchor="middle" font-size="11" font-weight="900" fill="${ink}">酒</text>`,
akagawara:ink=>{const tile='#b4472c',grille=stampGrille(ink),rows=(y0,y1,x0,x1)=>Array.from({length:Math.floor((x1-x0)/4)},(_,i)=>`<path d="M${x0+2+i*4} ${y0}V${y1}" stroke="${STAMP_PAPER}" stroke-width=".8"/>`).join('');return `<rect x="54" y="36" width="92" height="4" fill="${tile}"/><path d="M52 34h6v6h-6zM142 34h6v6h-6z" fill="${tile}"/><path d="M44 53L58 40H142L156 53Z" fill="${tile}"/>${rows(41,52,56,144)}<path d="M52 46.5H148" stroke="${STAMP_PAPER}" stroke-width=".9"/><rect x="50" y="53" width="100" height="29" fill="${ink}"/>${[60,78,114,132].map(x=>`<rect x="${x}" y="55" width="10" height="4.5" rx="2.2" fill="${STAMP_PAPER}"/>${[2.5,5,7.5].map(d=>`<path d="M${x+d} 55v4.5" stroke="${ink}" stroke-width=".9"/>`).join('')}`).join('')}<path d="M46 66L52 61H148L154 66Z" fill="${tile}"/>${rows(62,65.5,52,148)}${grille(55,68,33,14)}<rect x="93" y="68" width="14" height="14" fill="${STAMP_PAPER}"/><path d="M93 68h14v5l-3.5-2-3.5 2-3.5-2-3.5 2z" fill="${ink}" opacity=".7"/>${grille(112,68,33,14)}<path d="M40 82H160" stroke="${ink}" stroke-width="1.8"/>`;},
hikouki:ink=>`<path d="M44 44q3-5 8-3q3-5 9-2q5 0 5 5z" fill="none" stroke="${ink}" stroke-width="1.3" opacity=".55"/><path d="M130 82q3-5 8-3q3-5 9-2q5 0 5 5z" fill="none" stroke="${ink}" stroke-width="1.3" opacity=".55"/><g transform="rotate(-14 100 60)"><path d="M104 57L88 36H96L124 57Z" fill="${ink}"/><path d="M104 63L88 84H96L124 63Z" fill="${ink}"/><rect x="95" y="43" width="9" height="4" rx="2" fill="${ink}"/><rect x="95" y="73" width="9" height="4" rx="2" fill="${ink}"/><path d="M60 58L52 47H58L72 58Z" fill="${ink}"/><path d="M60 62L52 73H58L72 62Z" fill="${ink}"/><path d="M50 60Q50 56 58 56H138Q150 56 157 60Q150 64 138 64H58Q50 64 50 60Z" fill="${ink}"/><path d="M146 58.2q5 .5 7.5 1.8" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.3" stroke-linecap="round"/><path d="M50 60h-8M48 57h-5M48 63h-5" stroke="${ink}" stroke-width="1.2" opacity=".5"/></g>`,
fune:ink=>`<path d="M128 42q4-4 8 0q4-4 8 0" fill="none" stroke="${ink}" stroke-width="1.3" opacity=".6"/><path d="M80 66V36" stroke="${ink}" stroke-width="2"/><path d="M81 37l15 5-15 5z" fill="${ink}"/><rect x="94" y="50" width="28" height="16" rx="2" fill="${ink}"/>${[98,108].map(x=>`<rect x="${x}" y="54" width="7" height="6" rx="1" fill="${STAMP_PAPER}"/>`).join('')}<path d="M116 50V42h4v8" fill="${ink}"/><path d="M56 65H146L134 80H70Z" fill="${ink}"/><path d="M60 70H140" stroke="${STAMP_PAPER}" stroke-width="1.6"/><circle cx="130" cy="74" r="2" fill="${STAMP_PAPER}"/><path d="M40 80Q52 75 64 80T88 80T112 80T136 80T160 80" fill="none" stroke="${ink}" stroke-width="1.8" stroke-linecap="round"/><path d="M48 86Q58 82 68 86T88 86M112 86Q122 82 132 86T152 86" fill="none" stroke="${ink}" stroke-width="1.4" stroke-linecap="round" opacity=".6"/>`,
kitsune:ink=>`<path d="M75 52L79 29L95 44Z" fill="${ink}"/><path d="M125 52L121 29L105 44Z" fill="${ink}"/><path d="M80 45L81.5 35L89 43Z" fill="${STAMP_PAPER}"/><path d="M120 45L118.5 35L111 43Z" fill="${STAMP_PAPER}"/><path d="M70 50Q100 34 130 50Q128 68 100 83Q72 68 70 50Z" fill="${ink}"/><path d="M84 65Q100 58 116 65Q108 80 100 83Q92 80 84 65Z" fill="${STAMP_PAPER}"/><circle cx="100" cy="78" r="2.8" fill="${ink}"/><path d="M83 56q5-5 10 0M107 56q5-5 10 0" fill="none" stroke="${STAMP_PAPER}" stroke-width="2.2" stroke-linecap="round"/><path d="M100 44l1.5 3 3 .5-2.2 2 .6 3-2.9-1.5-2.9 1.5.6-3-2.2-2 3-.5z" fill="${STAMP_PAPER}"/>${[[52,1],[148,-1]].map(([x,f])=>`<path d="M${x} 84Q${x-2*f} 66 ${x+8*f} 52" fill="none" stroke="${ink}" stroke-width="1.4"/>${[0,1,2,3].map(i=>`<ellipse cx="${x+(1+i*2)*f}" cy="${70-i*5}" rx="1.8" ry="3" transform="rotate(${30*f} ${x+(1+i*2)*f} ${70-i*5})" fill="${ink}"/>`).join('')}`).join('')}`,
michishirube:ink=>`<path d="M40 66L64 44L84 58L108 38L134 60L160 48" fill="none" stroke="${ink}" stroke-width="1.8" stroke-linejoin="round" opacity=".45"/><path d="M84 86Q96 74 110 68T124 54M114 86Q118 76 124 70T130 54" fill="none" stroke="${ink}" stroke-width="1.6"/><path d="M100 80l4-2M114 70l3-1.5M122 60l2-1" stroke="${ink}" stroke-width="1" opacity=".6"/><path d="M60 84V54L67 47L74 54V84Z" fill="${ink}"/><path d="M67 56v22" stroke="${STAMP_PAPER}" stroke-width="1.8" stroke-dasharray="3 1.6"/><path d="M142 84V74" stroke="${ink}" stroke-width="3"/><path d="M142 50L132 62H152ZM142 56L130 70H154Z" fill="${ink}"/><path d="M44 84q2-5 4 0M50 84q2-6 4 0M80 84q2-5 4 0M150 84q2-5 4 0" fill="none" stroke="${ink}" stroke-width="1.2"/><path d="M40 84.5H160" stroke="${ink}" stroke-width="1.4"/>`,
shukuba:ink=>{const grille=stampGrille(ink);return `<path d="M42 60L49 53H77L84 60Z" fill="${ink}"/><rect x="46" y="60" width="34" height="22" fill="${ink}"/>${grille(50,64,15,14)}<rect x="68" y="64" width="9" height="18" fill="${STAMP_PAPER}"/><path d="M80 48L88 40H112L120 48Z" fill="${ink}"/><rect x="84" y="48" width="32" height="8" fill="${ink}"/>${grille(88,50,24,4)}<path d="M79 60L85 55H115L121 60Z" fill="${ink}"/><rect x="83" y="60" width="34" height="22" fill="${ink}"/><rect x="89" y="64" width="22" height="18" fill="${STAMP_PAPER}"/><path d="M89 64h22v7l-3.7-2-3.6 2-3.7-2-3.7 2-3.6-2-3.7 2z" fill="${ink}" opacity=".75"/><rect x="94.5" y="72" width="11" height="9" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="1.2"/><text x="100" y="79.6" text-anchor="middle" font-size="7.5" font-weight="900" fill="${ink}">宿</text><path d="M120 60L127 53H151L158 60Z" fill="${ink}"/><rect x="123" y="60" width="31" height="22" fill="${ink}"/>${grille(135,64,15,14)}<rect x="126" y="64" width="7" height="18" fill="${STAMP_PAPER}"/><path d="M83 62v3" stroke="${ink}" stroke-width="1"/><ellipse cx="83" cy="69" rx="3.5" ry="4.5" fill="${ink}"/><path d="M79.5 69h7" stroke="${STAMP_PAPER}" stroke-width=".8"/><path d="M40 82H160" stroke="${ink}" stroke-width="1.8"/>`;},
tanbo:ink=>`<circle cx="140" cy="40" r="6" fill="none" stroke="${ink}" stroke-width="1.4"/><path d="M40 60Q70 46 100 56T160 52" fill="none" stroke="${ink}" stroke-width="1.6" opacity=".45"/><path d="M40 63H160M40 73H160M40 83H160" stroke="${ink}" stroke-width="1.4"/><path d="M110 63L106 73M104 73L100 83" stroke="${ink}" stroke-width="1.2"/>${[[68,8],[78,9]].map(([y,s])=>Array.from({length:Math.floor(80/s)},(_,i)=>{const x=78+i*s;return `<path d="M${x} ${y+2}v-5M${x} ${y+2}l-2.5-4M${x} ${y+2}l2.5-4" stroke="${ink}" stroke-width="1.1" stroke-linecap="round"/>`;}).join('')).join('')}<path d="M60 84Q58 62 74 46" fill="none" stroke="${ink}" stroke-width="1.8"/><path d="M58 84Q54 70 46 64" fill="none" stroke="${ink}" stroke-width="1.4"/>${[[66,54],[69,51],[72,48.5],[63,58],[62,62]].map(([x,y],i)=>`<ellipse cx="${x+3}" cy="${y+2}" rx="2" ry="3.4" transform="rotate(40 ${x+3} ${y+2})" fill="${ink}"/><ellipse cx="${x-2}" cy="${y-1}" rx="2" ry="3.4" transform="rotate(-20 ${x-2} ${y-1})" fill="${ink}"/>`).join('')}`,
yama:ink=>`<circle cx="62" cy="40" r="5.5" fill="none" stroke="${ink}" stroke-width="1.4"/><path d="M40 82L66 54L82 66L106 40L130 62L144 52L160 66V82Z" fill="${ink}" opacity=".4"/><path d="M60 82L98 44L136 82Z" fill="${ink}"/><path d="M89 53L98 44L107 53L102 51L98 55L94 51Z" fill="${STAMP_PAPER}"/>${[[50,64],[60,68],[144,66]].map(([x,y])=>`<path d="M${x} ${y-12}L${x-7} ${y}H${x+7}Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><path d="M${x} ${y-6}L${x-9} ${y+8}H${x+9}Z" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/><rect x="${x-1.5}" y="${y+8}" width="3" height="${82-y-8}" fill="${ink}"/>`).join('')}<circle cx="128" cy="68" r="8" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1.2"/><rect x="126.5" y="75" width="3" height="7" fill="${ink}"/><path d="M114 44q3-3 6 0q3-3 6 0" fill="none" stroke="${ink}" stroke-width="1.2"/><path d="M40 82.5H160" stroke="${ink}" stroke-width="1.8"/>`,
tsuru:ink=>`<path d="M63 57Q56 60 54 68Q60 64 66 64Z" fill="${ink}"/><ellipse cx="78" cy="60" rx="15" ry="9" transform="rotate(-12 78 60)" fill="${ink}"/><path d="M88 55Q95 46 92 36" fill="none" stroke="${ink}" stroke-width="5.5" stroke-linecap="round"/><path d="M89 54Q95 46 92 38" fill="none" stroke="${STAMP_PAPER}" stroke-width="2.4" stroke-linecap="round"/><circle cx="93" cy="35" r="4.6" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="1.6"/><path d="M93.5 30.8a2 2 0 0 1 2 1.6" stroke="#c8412e" stroke-width="2" fill="none"/><path d="M97 35.5l8 1.5-8 1z" fill="${ink}"/><circle cx="94" cy="34.5" r="1" fill="${ink}"/><path d="M76 68V82M82 67V82" stroke="${ink}" stroke-width="1.6"/><path d="M72 82h8M78 82h8" stroke="${ink}" stroke-width="1.2"/><path d="M60 84Q72 80 84 84T108 84" fill="none" stroke="${ink}" stroke-width="1.3" opacity=".6"/><path d="M114 70Q114 82 132 82Q150 82 150 70" fill="none" stroke="${ink}" stroke-width="3" stroke-linecap="round"/><ellipse cx="132" cy="70" rx="18" ry="5" fill="none" stroke="${ink}" stroke-width="3"/>${[124,132,140].map((x,i)=>`<path d="M${x} 62q-4-5 0-10t0-10" fill="none" stroke="${ink}" stroke-width="2.4" stroke-linecap="round" opacity="${i==1?1:.8}"/>`).join('')}`,
kawa:ink=>`<path d="M40 56L62 40L80 52L104 36L126 50L142 42L160 54" fill="none" stroke="${ink}" stroke-width="1.6" stroke-linejoin="round" opacity=".45"/><path d="M98 50Q86 60 100 68Q114 76 90 88H128Q126 74 112 68Q100 62 106 50Z" fill="${ink}"/><path d="M100 56q-3 4 3 7M106 70q5 3 0 8M112 78q4 3 1 7" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.3" stroke-linecap="round"/>${[[58,64],[72,74],[140,62],[150,76]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="7" fill="${ink}" opacity=".85"/><rect x="${x-1.2}" y="${y+5}" width="2.4" height="${84-y-5}" fill="${ink}"/>`).join('')}<path d="M122 42q3-3 6 0q3-3 6 0" fill="none" stroke="${ink}" stroke-width="1.2"/><path d="M40 84H90M128 84H160" stroke="${ink}" stroke-width="1.6"/><path d="M80 84q2-5 4 0M132 84q2-6 4 0" fill="none" stroke="${ink}" stroke-width="1.2"/>`,
ushi:ink=>`<path d="M86 42Q78 34 83 28M114 42Q122 34 117 28" fill="none" stroke="${ink}" stroke-width="4" stroke-linecap="round"/><path d="M86 42Q79 35 83 29M114 42Q121 35 117 29" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.6" stroke-linecap="round"/><ellipse cx="76" cy="50" rx="9" ry="4.5" transform="rotate(-18 76 50)" fill="${ink}"/><ellipse cx="124" cy="50" rx="9" ry="4.5" transform="rotate(18 124 50)" fill="${ink}"/><path d="M83 46Q83 36 100 36Q117 36 117 46L116 66H84Z" fill="${ink}"/><path d="M96 38q4 4 8 0" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.6" stroke-linecap="round"/><circle cx="92" cy="52" r="3.4" fill="${STAMP_PAPER}"/><circle cx="108" cy="52" r="3.4" fill="${STAMP_PAPER}"/><circle cx="92.5" cy="52.8" r="1.7" fill="${ink}"/><circle cx="107.5" cy="52.8" r="1.7" fill="${ink}"/><ellipse cx="100" cy="70" rx="16" ry="10.5" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2.4"/><ellipse cx="94" cy="69" rx="2.2" ry="3" fill="${ink}"/><ellipse cx="106" cy="69" rx="2.2" ry="3" fill="${ink}"/><path d="M95 75.5q5 3 10 0" fill="none" stroke="${ink}" stroke-width="1.4" stroke-linecap="round"/><path d="M48 84q2-6 4 0M54 84q2-5 4 0M142 84q2-6 4 0M148 84q2-5 4 0" fill="none" stroke="${ink}" stroke-width="1.2"/><path d="M40 84.5H160" stroke="${ink}" stroke-width="1.4"/>`,
shiro:ink=>`<path d="M40 84Q100 36 160 84Z" fill="${ink}" opacity=".3"/><path d="M84 52L90 46H110L116 52Z" fill="${ink}"/><path d="M92 46L96 42H104L108 46Z" fill="${ink}"/><rect x="87" y="52" width="26" height="10" fill="${ink}"/><rect x="92" y="55" width="4" height="4" fill="${STAMP_PAPER}"/><rect x="104" y="55" width="4" height="4" fill="${STAMP_PAPER}"/><path d="M68 84L74 62H126L132 84Z" fill="${ink}"/>${[[76,67,20],[98,67,24],[72,74,14],[88,74,22],[112,74,16],[70,80,20],[92,80,18],[112,80,18]].map(([x,y,w])=>`<path d="M${x} ${y}h${w}" stroke="${STAMP_PAPER}" stroke-width=".9"/>`).join('')}${[[56,1],[144,-1]].map(([x,f])=>`<path d="M${x} 84V38" stroke="${ink}" stroke-width="1.6"/><path d="M${x} 40h${9*f}" stroke="${ink}" stroke-width="1.2"/><rect x="${f>0?x+.8:x-9.8}" y="41" width="9" height="24" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="1.6"/><circle cx="${x+4.5*f}" cy="50" r="2.8" fill="${ink}"/>`).join('')}`,
touge:ink=>`<path d="M40 64L66 38L94 54L100 50L106 54L134 36L160 62V86H40Z" fill="${ink}" opacity=".35"/><path d="M62 88Q126 80 118 70T86 62T106 52" fill="none" stroke="${ink}" stroke-width="7" stroke-linecap="round"/><path d="M62 88Q126 80 118 70T86 62T106 52" fill="none" stroke="${STAMP_PAPER}" stroke-width="1.2" stroke-dasharray="3 3"/><path d="M110 50V40" stroke="${ink}" stroke-width="1.4"/><rect x="104" y="34" width="16" height="7" rx="1" fill="${ink}"/><text x="112" y="39.8" text-anchor="middle" font-size="5.6" font-weight="900" fill="${STAMP_PAPER}">とうげ</text>${[[50,70],[146,72],[62,58]].map(([x,y])=>`<path d="M${x} ${y-9}L${x-6} ${y+2}H${x+6}Z" fill="${ink}"/><rect x="${x-1}" y="${y+2}" width="2" height="4" fill="${ink}"/>`).join('')}`,
yamakawa:ink=>`<path d="M40 70L64 44L80 56L102 34L128 60L142 50L160 64V72H40Z" fill="${ink}"/><path d="M95 41L102 34L109 41L105 40L102 43L99 40Z" fill="${STAMP_PAPER}"/><path d="M64 44L58 52M102 34L96 46M142 50L138 56" stroke="${STAMP_PAPER}" stroke-width="1" opacity=".7"/><path d="M40 72H160" stroke="${STAMP_PAPER}" stroke-width="1.5"/><path d="M40 73H160V86H40Z" fill="${ink}" opacity=".35"/><path d="M46 78Q56 75 66 78T86 78M100 82Q110 79 120 82T140 82M120 76Q128 73 136 76" fill="none" stroke="${ink}" stroke-width="1.4" stroke-linecap="round"/>${[[52,62],[150,64]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="6" fill="${ink}" stroke="${STAMP_PAPER}" stroke-width="1"/>`).join('')}<path d="M120 36q3-3 6 0q3-3 6 0" fill="none" stroke="${ink}" stroke-width="1.2"/>`,
hebi:ink=>`<path d="M52 78Q60 82 72 74Q88 62 100 72Q112 82 124 70Q134 60 130 50" fill="none" stroke="${ink}" stroke-width="12" stroke-linecap="round"/><path d="M52 78Q60 82 72 74Q88 62 100 72Q112 82 124 70Q134 60 130 50" fill="none" stroke="${STAMP_PAPER}" stroke-width="8" stroke-linecap="round"/><path d="M44 80Q48 80 52 78" fill="none" stroke="${ink}" stroke-width="1.6" stroke-linecap="round"/><ellipse cx="129" cy="45" rx="11" ry="8.5" fill="${STAMP_PAPER}" stroke="${ink}" stroke-width="2"/><circle cx="125" cy="43" r="2.2" fill="#c8412e"/><circle cx="134" cy="43" r="2.2" fill="#c8412e"/><circle cx="125.6" cy="42.4" r=".7" fill="${STAMP_PAPER}"/><circle cx="134.6" cy="42.4" r=".7" fill="${STAMP_PAPER}"/><path d="M127 48.5q2.5 2 5 0" fill="none" stroke="${ink}" stroke-width="1.2" stroke-linecap="round"/><path d="M129.5 53.5v5l-2 2.5M129.5 58.5l2 2.5" fill="none" stroke="#c8412e" stroke-width="1.2" stroke-linecap="round"/><ellipse cx="121" cy="47.5" rx="2" ry="1.2" fill="${ink}" opacity=".3"/><ellipse cx="138" cy="47.5" rx="2" ry="1.2" fill="${ink}" opacity=".3"/>${[[84,70],[98,74],[112,74]].map(([x,y])=>`<path d="M${x-2} ${y}q2-2 4 0" fill="none" stroke="${ink}" stroke-width=".9" opacity=".5"/>`).join('')}<path d="M60 48l1.6 3.6 3.6 1.4-3.6 1.4-1.6 3.6-1.6-3.6-3.6-1.4 3.6-1.4z" fill="${ink}" opacity=".55"/><path d="M78 40l1 2.2 2.2 1-2.2 1-1 2.2-1-2.2-2.2-1 2.2-1z" fill="${ink}" opacity=".45"/><path d="M40 86H160" stroke="${ink}" stroke-width="1.4"/>`,
castle:ink=>`<path d="M82 52H118L114 46H86Z" fill="${ink}"/><path d="M88 46H112L108 40H92Z" fill="${ink}"/><path d="M95 40H105L100 35Z" fill="${ink}"/><rect x="78" y="52" width="44" height="18" fill="${ink}"/><rect x="85" y="56" width="4.5" height="5" fill="${STAMP_PAPER}"/><rect x="97.5" y="56" width="5" height="5" fill="${STAMP_PAPER}"/><rect x="110" y="56" width="4.5" height="5" fill="${STAMP_PAPER}"/><rect x="44" y="58" width="15" height="24" fill="${ink}" opacity=".8"/><rect x="61" y="64" width="12" height="18" fill="${ink}" opacity=".6"/><rect x="127" y="62" width="13" height="20" fill="${ink}" opacity=".6"/><rect x="142" y="56" width="15" height="26" fill="${ink}" opacity=".8"/><rect x="89" y="72" width="22" height="10" rx="2" fill="${ink}"/>`};
function stampSVG(id){const s=R.stations[id],lines=R.lines.filter(l=>l.stations.includes(id)),ink=lines[0].color,scene=STAMP_LANDMARK[id]||(window.RailDrive?RailDrive.stationScene(id,lines.map(l=>l.id)):'sea'),key=`stamp-${++stampSeq}`,ring=2*Math.PI*90,fs=Math.min(44,132/s.name.length),rs=Math.min(18,84/s.reading.length);
return `<svg class="stamp-art" viewBox="0 0 200 200" aria-hidden="true"><defs><clipPath id="${key}"><circle cx="100" cy="100" r="76"/></clipPath></defs><g transform="rotate(${s.name.charCodeAt(0)%7-3} 100 100)">${lines.map((l,i)=>`<circle cx="100" cy="100" r="90" fill="none" stroke="${l.color}" stroke-width="12" stroke-dasharray="${ring/lines.length} ${ring}" stroke-dashoffset="${-i*ring/lines.length}" transform="rotate(-90 100 100)"/>`).join('')}<circle cx="100" cy="100" r="78" fill="none" stroke="${ink}" stroke-width="3"/>
<text x="100" y="50" text-anchor="middle" font-size="${rs}" font-weight="800" fill="${ink}">${esc(s.reading)}</text><text x="100" y="${80+fs/2.8}" text-anchor="middle" font-size="${fs}" font-weight="900" fill="${ink}">${esc(s.name)}</text><g clip-path="url(#${key})"><g transform="translate(100 110) scale(.98) translate(-100 -35)">${STAMP_ART[scene](ink)}</g></g></g></svg>`;}
// The press (as in the mock-up): the stamp comes down from large to its place in 0.3s and lands at about 0.2s, the page gives, then sparks; drive.js pon() plays the stamp sound file on the landing and the キラーン with the sparks (loaded ahead while the pad waits).
function stampBurst(id){const colors=[...R.lines.filter(l=>l.stations.includes(id)).map(l=>l.color),'#f5a524'];return Array.from({length:12},(_,i)=>`<i class="stamp-spark${i%2?' star':''}" aria-hidden="true" style="--a:${i*30+8}deg;--d:${i%3?112:132}px;--c:${colors[i%colors.length]}"></i>`).join('');}
function stampDay(id){const d=state.stamps?.[id];if(d){const [,m,day]=d.split('-').map(Number);return `${m}がつ ${day}にち`;}return id===C.opened(state)[0]?'しゅっぱつの えき':'まえに きたよ';}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function directionArrow(from,to){const dx=to.x-from.x,dy=to.y-from.y;if(Math.abs(dy)<Math.abs(dx)*.35)return dx>0?'→':'←';if(Math.abs(dx)<Math.abs(dy)*.35)return dy>0?'↓':'↑';return dy>0?(dx>0?'↘':'↙'):(dx>0?'↗':'↖');}
function renderTravel(){const s=R.stations[state.current],line=R.lines.find(l=>l.stations.includes(s.id));$('current-name').textContent=s.name;$('current-reading').textContent=s.reading;$('current-line').style.background=line.color;$('current-line').textContent=line.name;
const options=C.adjacent(s.id);$('directions').innerHTML=options.map(e=>{const open=state.edges.includes(e.id),to=R.stations[e.to],route=R.lines.find(l=>l.id===e.line),active=state.target===e.to,remaining=C.credits(state)>0?'ためた回数で しゅっぱつ':`あと ${5-C.paid(state)%5}もん`;return `<button ${state.pending||conflict?'disabled':''} class="direction-choice forward ${open?'opened':''} ${active?'active':''}" style="--route-color:${route.color}" data-target="${e.to}" aria-pressed="${active}"><span class="direction-arrow" aria-hidden="true">${directionArrow(s,to)}</span><span class="direction-name">${esc(to.name)} <span class="direction-action">へ すすむ</span><small>${esc(to.reading)}</small></span><span class="direction-detail">${open?'かいつうずみ':remaining}</span></button>`;}).join('');
const n=C.credits(state);$('build-label').textContent=state.target?(n>0?`${n}えきぶん ためているよ`:`あと ${5-C.paid(state)%5}もんで ${state.target}！`):'ろせんずで 開通した駅をえらぼう';$('dots').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<C.paid(state)%5?'on':''}"></i>`).join('')+`<b class="dots-train" style="--step:${C.paid(state)%5}" aria-hidden="true"><svg viewBox="0 0 34 20"><path d="M3 4h22a8 8 0 0 1 8 8v4H3z" fill="#fff" stroke="#16323c" stroke-width="2" stroke-linejoin="round"/><path d="M3 13h30" stroke="${line.color}" stroke-width="3"/><rect x="7" y="7" width="5" height="4" rx="1" fill="#16323c"/><rect x="15" y="7" width="5" height="4" rx="1" fill="#16323c"/><path d="M24 7h3l3 4h-6z" fill="#16323c"/><circle cx="9" cy="18" r="2" fill="#16323c"/><circle cx="26" cy="18" r="2" fill="#16323c"/></svg></b>`;$('use-credit').hidden=!(n>0&&state.target&&!state.pending);$('use-credit').textContent=`ためた回数で ${state.target}へ しゅっぱつ`;$('use-credit').disabled=conflict;$('quiz-goal').textContent=$('build-label').textContent;$('quiz-dots').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<C.paid(state)%5?'on':''}"></i>`).join('');$('quiz-start').disabled=!!state.pending||conflict;
const c=C.nearestReward(state,cards,true);$('next-card').innerHTML=c?`<img src="${c.image}" alt="${esc(c.name)}"><div><b>${esc(c.name)}</b><p>${esc(c.station)}駅でゲット<br>あと ${c.remaining}くかん${state.target?'（えらんだ方向）':''}</p></div>`:(C.earned(state).length===cards.length?'<div><b>すべての 車両に あえたね！</b><p>まだ白い駅にも、あいにいこう。</p></div>':'<div><b>この先の駅を つなげよう</b><p>別の方向には、まだ車両カードがあるよ。</p></div>');}
// The buttons are the operations this person has kinds for (set in おうちの方へ).
function render(){$('mode-tabs').innerHTML=C.modes(state).map(m=>`<button data-mode="${m}" class="${m===state.mode?'active':''}" aria-pressed="${m===state.mode}"${state.pending||conflict?' disabled':''}>${OP_LABELS[m].join(' ')}</button>`).join('');$('mode-tabs').classList.toggle('many',C.modes(state).length>2);$('question').textContent=`${state.problem.a} ${OP_LABELS[state.mode][0]} ${state.problem.b} =`;$('answer').textContent=state.solved?state.problem.result:(entry||'?');$('keypad').style.visibility=state.solved?'hidden':'visible';$('next').hidden=!state.solved;$('feedback').textContent=state.solved?'せいかい！':'こたえを いれてね';document.querySelector('.exercise').classList.toggle('solved',state.solved);renderTravel();renderMap();save();}
// After a section opens, drive it first (once per opening; `pending.drove` survives a reload), then show the usual reward. A trip on an opened section (`pending.ride`) is the drive alone: no stamp, card or reward screen. The train list is the one from before this opening, so a new card stays a surprise until the reward.
function openDrive(){const p=state.pending,e=C.edgeById[p.edge],from=e.a===p.station?e.b:e.a,next=C.adjacent(p.station).map(x=>x.to).find(id=>id!==from);RailDrive.open({from:R.stations[from],to:R.stations[p.station],next:next?R.stations[next]:null,line:R.lines.find(l=>l.id===e.line),train:C.train(state),ride:!!p.ride,owned:C.rideable(p.ride?state:{...state,edges:state.edges.filter(id=>id!==p.edge)}),cards,onTrain:id=>{state.train=id;save();},onDone:()=>{if(!state.pending)return;state.pending.drove=true;save();showReward();}});}
// The first opening gives the first card (Red Wing) before the drive, so the child sets off in the train they just got.
// A new station's stamp waits for the child to tap it ("ポン！"); the card and つぎへ come after.
let giftMode=false;
function showReward(justStamped=false){if(!state.pending)return;const e=C.edgeById[state.pending.edge],earlier=state.pending.ride?state:{...state,edges:state.edges.filter(id=>id!==e.id)},before=C.earned(earlier),gift=cards.filter(c=>c.first&&C.earned(state).includes(c.id)&&!before.includes(c.id));
if(gift.length&&!state.pending.gift&&!state.pending.drove){giftMode=true;$('reward-title').textContent='はじめての かいつう！';$('reward-text').textContent='でんしゃの カードを ゲット！ この でんしゃで しゅっぱつ しよう！';$('reward-cards').innerHTML=gift.map(c=>cardHTML(c)).join('');$('reward-close').textContent='この でんしゃで しゅっぱつ →';$('reward-stamp').innerHTML='';$('reward-close').hidden=false;if(!$('reward').open)$('reward').showModal();return;}
giftMode=false;$('reward-close').textContent='つぎへ →';if(!state.pending.drove&&window.RailDrive){if($('reward').open)$('reward').close();openDrive();return;}if(state.pending.ride){closeReward();return;}const name=state.pending.station;$('reward-title').innerHTML=`<ruby>${esc(name)}<rt>${esc(R.stations[name].reading)}</rt></ruby>駅 かいつう！`;const already=C.opened(earlier).includes(name);const rewards=already?[]:cards.filter(c=>!c.first&&c.station===name),pressing=C.needsStamp(state);$('reward-stamp').innerHTML=already?'':pressing?`<button class="stamp-page stamp-pad" aria-label="${esc(name)}えきの スタンプを おす"><span class="stamp-hint" style="--c:${R.lines.find(l=>l.stations.includes(name)).color}"><span class="stamp-pulse" aria-hidden="true"></span><span class="stamp-target" aria-hidden="true"></span><span class="stamp-cta"><small>タップして</small>ポン！</span></span></button>`:`<div class="stamp-page">${justStamped?stampBurst(name):''}<div class="stamp-inked">${stampSVG(name)}</div></div><p class="stamp-day">${stampDay(name)}</p>`;$('reward-close').hidden=pressing;if(pressing)window.RailDrive?.loadSfx();$('reward').classList.toggle('stamping',justStamped);$('reward-text').textContent=pressing?'えきスタンプを おそう！':rewards.length?'この駅の 車両カードを ゲット！':already?'線路が つながった！ 別のルートでも いけるね。':'またひとつ、行ける場所がふえたね。';const cardsHTML=pressing?'':rewards.map(c=>cardHTML(c)).join('');$('reward-cards').innerHTML=justStamped?'':cardsHTML;if(!$('reward').open)$('reward').showModal();if(justStamped){const at=state.pending;setTimeout(()=>{if(state.pending!==at)return;$('reward-cards').innerHTML=cardsHTML;$('reward-close').focus({preventScroll:true});},600);}}
function key(value){if(state.solved||state.pending||conflict||document.querySelector('dialog[open]'))return;if(C.paid(state)%5===0&&showRest())return;window.RailDrive?.loadSfx();if(value==='clear')entry=entry.slice(0,-1);else if(value==='submit'){if(!entry){$('feedback').textContent='こたえを いれてね。';return;}if(C.solve(state,entry,profiles.device)){rest.n++;saveRest();window.RailDrive?.seikai();selected=state.current;render();if(state.pending){countSection(state.mode);setQuiz(false);centerMap();}showReward();return;}window.RailDrive?.retry();$('feedback').textContent='もういちど やってみよう。だいじょうぶ！';entry='';}else if(entry.length<3)entry=entry==='0'?value:entry+value;$('answer').textContent=entry||'?';}
$('keypad').innerHTML=['1','2','3','4','5','6','7','8','9','clear','0','submit'].map(v=>`<button data-key="${v}" class="${v==='submit'?'action submit':v==='clear'?'action':''}" aria-label="${v==='clear'?'1けた けす':v==='submit'?'けってい':v}">${v==='clear'?'けす':v==='submit'?'けってい':v}</button>`).join('');
$('keypad').onclick=e=>{const b=e.target.closest('[data-key]');if(b)key(b.dataset.key);};
// On a phone the problem and keypad get the whole screen (body.quiz, see style.css); the route map comes back when five answers open a section.
function setQuiz(on){document.body.classList.toggle('quiz',on);}
$('quiz-start').onclick=()=>{if(conflict||state.pending||showRest())return;if(state.solved&&C.next(state)){entry='';render();}setQuiz(true);};$('quiz-back').onclick=()=>setQuiz(false);
$('next').onclick=()=>{if(conflict||!C.next(state))return;entry='';render();};
$('mode-tabs').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b||conflict||!C.setMode(state,b.dataset.mode))return;entry='';render();};
function travelClick(e){if(conflict)return;const b=e.target.closest('[data-move],[data-target]');if(!b)return;if(b.dataset.move){if(!C.move(state,b.dataset.move))return;selected=state.current;centerMap();}else{if(!C.choose(state,b.dataset.target))return;selected=b.dataset.target;}render();}
$('directions').onclick=travelClick;$('map-selection').onclick=travelClick;$('use-credit').onclick=()=>{if(conflict||showRest()||!C.build(state,profiles.device))return;selected=state.current;render();centerMap();showReward();};
function closeReward(){if(!giftMode&&C.needsStamp(state))return;$('reward').classList.remove('stamping');if(giftMode&&state.pending){giftMode=false;state.pending.gift=true;save();$('reward').close();showReward();return;}state.pending=null;$('reward').close();render();if(state.solved)$('next').focus();if(!showRest()&&!showTransfer())showNews();}
$('sound-test').onclick=async()=>{$('sound-test-status').textContent=window.RailDrive?await RailDrive.soundTest():'おとの しくみが 読みこめていません';};$('sound-toggle').onclick=()=>window.RailDrive?.toggleSound();$('reward-close').onclick=closeReward;$('reward-stamp').onclick=e=>{if(conflict||!e.target.closest('.stamp-pad')||!C.stamp(state,today()))return;save();const st=R.stations[state.pending.station];window.RailDrive?.pon(st.say||st.reading);showReward(true);};$('reward').addEventListener('cancel',e=>{e.preventDefault();closeReward();});
$('collection-open').onclick=()=>{const got=C.earned(state);$('collection-grid').innerHTML=cards.map(c=>cardHTML(c,got.includes(c.id))).join('');$('collection-got').textContent=`${got.length} / ${cards.length}`;$('collection').showModal();};$('collection-close').onclick=()=>$('collection').close();
$('stamps-open').onclick=()=>{const got=new Set(C.opened(state)),seen=new Set();$('stamps-book').innerHTML=R.lines.map(l=>{const ids=l.stations.filter(id=>!seen.has(id)&&seen.add(id));return `<section class="stamp-line" style="--line:${l.color}"><h3>${ruby(l.name)} <small>${ids.filter(id=>got.has(id)).length} / ${ids.length}</small></h3><div class="stamp-grid">${ids.map(id=>got.has(id)?`<figure class="stamp-slot got"><div class="stamp-inked">${stampSVG(id)}</div><figcaption>${stampDay(id)}</figcaption></figure>`:`<figure class="stamp-slot"><div class="stamp-empty"><ruby>${esc(R.stations[id].name)}<rt>${esc(R.stations[id].reading)}</rt></ruby></div><figcaption>まだ</figcaption></figure>`).join('')}</div></section>`;}).join('');$('stamps-got').textContent=`${got.size} / ${Object.keys(R.stations).length}`;$('stampbook').showModal();};$('stamps-close').onclick=()=>$('stampbook').close();
$('parent').onclick=()=>{resetQuiz();$('reset-status').textContent='';$('who-status').textContent='';renderPeople();$('parents').showModal();};$('parent-close').onclick=$('parent-close-top').onclick=()=>$('parents').close();$('parents').addEventListener('close',()=>showNews());
// おうちの方へ: this person's record and kinds, everyone's names, and the guest's easy clear.
function renderPeople(){const counts=C.stats(state),name=profiles.names[store.who]||'';$('who-now').textContent=name;$('who-now').style.setProperty('--who',COLORS[store.who]);$('stats').innerHTML=`<p>${Object.keys(C.KINDS).filter(k=>counts[k]).map(k=>`${esc(KIND_NAMES[k])} ${counts[k]}問`).join(' ／ ')||'まだ 答えていません'}<br>合計 ${C.total(state)}問（答え直しを含む）<br>${C.opened(state).length}駅・${state.edges.length}区間 開通<br>開通済みの区間を走った回数：${C.ridden(state)}回<br>未使用の開通回数：${C.credits(state)}駅分</p>`;$('kind-list').innerHTML=C.OPS.map(op=>`<fieldset><legend>${OP_LABELS[op].join(' ')}</legend>${Object.keys(C.KINDS).filter(k=>C.KINDS[k]===op).map(k=>`<label><input type="checkbox" value="${k}"${state.kinds.includes(k)?' checked':''}${conflict?' disabled':''}> ${esc(KIND_NAMES[k])}</label>`).join('')}</fieldset>`).join('');$('name-list').innerHTML=C.PROFILES.map(p=>`<label style="--who:${COLORS[p.id]}"><i aria-hidden="true"></i><input data-name="${p.id}" value="${esc(profiles.names[p.id])}" maxlength="10" autocomplete="off" aria-label="${p.id==='guest'?'ゲスト':'なまえ'+p.id.slice(1)}の なまえ"></label>`).join('');$('guest-clear').hidden=store.who!=='guest';$('rest-on').checked=rest.on;$('rest-play').innerHTML=C.REST_PLAY.map(m=>`<option value="${m}"${m===rest.play?' selected':''}>${m}分</option>`).join('');$('rest-len').innerHTML=C.REST_LEN.map(m=>`<option value="${m}"${m===rest.rest?' selected':''}>${m}分</option>`).join('');$('rest-now').textContent=`いま続けて遊んでいる時間：約${Math.floor(rest.used/REST_UNIT)}分`;$('guest-clear').disabled=$('kinds-all').disabled=$('kinds-first').disabled=conflict;}
function applyKinds(kinds){if(conflict||!C.setKinds(state,kinds,Date.now())){$('who-status').textContent='計算の種類は 1つ以上 えらんでください。';renderPeople();return;}$('who-status').textContent='計算の種類を 保存しました。';entry='';render();renderPeople();}
$('kind-list').onchange=()=>applyKinds([...$('kind-list').querySelectorAll('input:checked')].map(i=>i.value));$('kinds-all').onclick=()=>applyKinds(Object.keys(C.KINDS));$('kinds-first').onclick=()=>applyKinds(C.FIRST_KINDS);
$('names-save').onclick=()=>{const next={...profiles,names:{...profiles.names}};for(const input of $('name-list').querySelectorAll('[data-name]'))if(!C.rename(next,input.dataset.name,input.value)){$('who-status').textContent='なまえは 1〜10文字で 入れてください。';return;}if(profilesBroken){$('who-status').textContent='なまえの記録が読み込めないため、保存できません。';return;}profiles=next;$('who-status').textContent=saveProfiles()?'なまえを 保存しました。':'なまえを 保存できませんでした。';renderBadge();renderPeople();};
$('guest-clear').onclick=()=>{if(conflict||store.who!=='guest'||!confirm('ゲストの記録（正解数・開通した駅・車両カード）を消して、玖波駅からはじめますか？'))return;if(!restart()){$('who-status').textContent='消す前の記録を残せないため、中止しました。';return;}$('who-status').textContent='ゲストの記録を 消しました。';renderPeople();};
// Starting over keeps this person's kinds and one copy of the record before (for 取り消し). It begins a new life, so merging with another device never brings the old record back; taking the copy back makes its life the newest.
function restart(){const kinds=state.kinds;try{store.keepBeforeReset(JSON.stringify(state));}catch(e){return false;}state=C.freshRecord(store.who);C.newLife(state,Date.now());C.setKinds(state,kinds);state.news=[];corrupt=false;entry='';selected=state.current;render();centerMap();return true;}
// だれが あそぶ？ comes up on every launch; from the header it can be closed to keep playing.
function renderBadge(){const name=profiles.names[store.who]||'';$('who-open').style.setProperty('--who',COLORS[store.who]||'#fff');$('who-name').textContent=name;$('who-open').querySelector('i').textContent=[...name][0]||'';$('who-open').setAttribute('aria-label',`${name}（あそぶ人を かえる）`);}
function openWho(){$('who-list').innerHTML=C.PROFILES.map(p=>{let got='はじめて';try{const rec=JSON.parse(localStorage.getItem(C.recordKey(p.id)));if(C.valid(rec)&&rec.version===3)got=`🚩 ${C.opened(rec).length}えき`;}catch(e){}return `<button data-who="${p.id}" style="--who:${COLORS[p.id]}"><i aria-hidden="true">${esc([...profiles.names[p.id]][0])}</i><b>${esc(profiles.names[p.id])}</b><small>${got}</small></button>`;}).join('');$('who-close').hidden=!store.who;$('who').showModal();}
function pickWho(id){if(!C.PROFILES.some(p=>p.id===id))return;load(id);$('who').close();setQuiz(false);renderBadge();render();centerMap();showReward();if(!showRest())showNews();}
$('who-list').onclick=e=>{const b=e.target.closest('[data-who]');if(b)pickWho(b.dataset.who);};$('who-open').onclick=openWho;$('who-close').onclick=()=>$('who').close();$('who').addEventListener('cancel',e=>{if(!store.who)e.preventDefault();});$('who').addEventListener('close',()=>showRest());
// のりかえ案内 (trying it out locally, 2026-09-28): after three sections in a row answered with the same button, suggest another button (the one unused longest) once, with このまま to stay. Counted only while the page is open, per person; nothing is saved. ?norikae=1 suggests it after every section, for trying it out.
const TRANSFER_AFTER=/[?&]norikae=1(&|$)/.test(location.search)?1:3;let streak={mode:null,n:0},usedAt={},sections=0,transferDue=false,transferTo=null;
function countSection(mode){usedAt[mode]=++sections;streak=streak.mode===mode?{mode,n:streak.n+1}:{mode,n:1};if(streak.n>=TRANSFER_AFTER&&C.modes(state).length>1)transferDue=true;}
function showTransfer(){if(!transferDue||state.pending||conflict||document.querySelector('dialog[open]'))return false;const n=streak.n;transferDue=false;streak={mode:null,n:0};transferTo=C.modes(state).filter(m=>m!==state.mode).sort((a,b)=>(usedAt[a]||0)-(usedAt[b]||0))[0];if(!transferTo)return false;const now=OP_LABELS[state.mode][1],to=OP_LABELS[transferTo][1];$('transfer-heading').innerHTML=`${esc(to)}せんに<br>のりかえて みよう！`;$('transfer-text').textContent=`${now}せんに ${n}かい つづけて のったね。`;$('transfer-go').textContent=`${OP_LABELS[transferTo][0]} ${to}せんに のりかえる`;$('transfer-stay').textContent=`このまま ${now}せん`;$('transfer').showModal();window.RailDrive?.norikae(`のりかえの ごあんない です。${to}せんに、のりかえて みよう！`);return true;}
function closeTransfer(go){if(go&&transferTo&&!conflict&&C.setMode(state,transferTo)){entry='';render();}transferTo=null;$('transfer').close();showNews();}
$('transfer-go').onclick=()=>closeTransfer(true);$('transfer-stay').onclick=()=>closeTransfer(false);$('transfer').addEventListener('cancel',e=>{e.preventDefault();closeTransfer(false);});
// きゅうけい (2026-09-29): after 30 minutes of play in a row (per person, set in おうちの方へ), the rest screen comes when a section ends and stays until the rest is over (15 minutes); a reload or another launch shows it again. A little note comes 5 minutes before. Time is counted between taps (core.js restTick) and kept apart from the record. ほかの 人に かわる lets someone else play; an adult can end the rest with a check sum. ?kyukei=1 makes a minute 2 seconds, for trying it out.
const REST_UNIT=/[?&]kyukei=1(&|$)/.test(location.search)?2000:60000;let rest=C.freshRest('guest'),restTimer=null,restAnswer=null;
function loadRest(who){rest=C.freshRest(who);try{const r=JSON.parse(localStorage.getItem(C.restKey(who)));if(C.validRest(r))rest=r;}catch(e){}C.restTick(rest,Date.now(),REST_UNIT);saveRest();renderRestNote();}
function saveRest(){if(!store.who)return;try{localStorage.setItem(C.restKey(store.who),JSON.stringify(rest));}catch(e){}}
function renderRestNote(){$('rest-note').hidden=!(store.who&&C.restSoon(rest,REST_UNIT));}
function restTap(){if(!store.who)return;C.restTick(rest,Date.now(),REST_UNIT);saveRest();renderRestNote();if($('rest').open)renderRest();}
document.addEventListener('pointerdown',restTap,true);document.addEventListener('keydown',restTap,true);
function renderRest(){const left=C.restLeft(rest,Date.now());$('rest-bar').style.width=`${left?Math.round((1-left/(rest.rest*REST_UNIT))*100):100}%`;$('rest-left').textContent=left?`あと ${Math.ceil(left/REST_UNIT)}ふん`:'やすめたね！ また しゅっぱつ できるよ';$('rest-go').hidden=!!left;}
function restAsk(){const a=12+Math.floor(Math.random()*8),b=3+Math.floor(Math.random()*7);restAnswer=a*b;$('rest-question').textContent=`${a} × ${b} =`;$('rest-answer').value='';}
// Only at the start of a section (the five answers of the last one are in), so a problem or drive is never cut off.
function showRest(){if(!store.who||conflict||state.pending||document.querySelector('dialog[open]'))return false;const now=Date.now();C.restTick(rest,now,REST_UNIT);const fresh=!rest.until&&C.paid(state)%5===0&&C.startRest(rest,now,REST_UNIT);saveRest();renderRestNote();if(!rest.until)return false;setQuiz(false);const stations=Object.values(state.stamps||{}).filter(d=>d===today()).length;$('rest-done').innerHTML=`${rest.n?`<span>こんかい せいかい <b>${rest.n}</b>もん</span>`:''}${stations?`<span>きょう あたらしい えき <b>${stations}</b>えき</span>`:''}`;restAsk();$('rest-status').textContent='';document.querySelector('.rest-adult').open=false;renderRest();clearInterval(restTimer);restTimer=setInterval(renderRest,1000);$('rest').showModal();if(fresh)window.RailDrive?.norikae('きゅうけいの ごあんない です。でんしゃも ひとやすみ。すこし やすもうね。');return true;}
function closeRest(){clearInterval(restTimer);restTimer=null;$('rest').close();}
function endRest(){C.endRest(rest,Date.now());saveRest();renderRestNote();closeRest();if(!showTransfer())showNews();}
$('rest-go').onclick=()=>{if(!C.restLeft(rest,Date.now()))endRest();};$('rest-who').onclick=()=>{closeRest();openWho();};$('rest').addEventListener('cancel',e=>e.preventDefault());
$('rest-unlock').onclick=()=>{if(!/^\d+$/.test($('rest-answer').value.trim())||Number($('rest-answer').value)!==restAnswer){$('rest-status').textContent='確認の答えがちがいます。';restAsk();return;}endRest();};
$('parents').querySelector('.rest-settings').onchange=()=>{C.setRest(rest,$('rest-on').checked,Number($('rest-play').value),Number($('rest-len').value),Date.now());saveRest();renderRestNote();renderPeople();};
// Newly turned-on kinds get a celebration once, then the first new button is chosen.
function showNews(){if(!store.who||!state.news?.length||state.pending||document.querySelector('dialog[open]'))return;$('news-list').innerHTML=state.news.map(k=>`<li><b>${OP_LABELS[C.KINDS[k]][0]}</b>${esc(KIND_NAMES[k])}</li>`).join('');$('news').showModal();window.RailDrive?.seikai();}
function closeNews(){const first=state.news?.[0];C.seeNews(state);if(first)C.setMode(state,C.KINDS[first]);entry='';$('news').close();render();}
$('news-close').onclick=closeNews;$('news').addEventListener('cancel',e=>{e.preventDefault();closeNews();});
$('app-version').textContent=document.querySelector('meta[name="app-version"]')?.content||'不明';
$('update-app').onclick=async()=>{
const button=$('update-app');button.disabled=true;$('update-status').textContent='最新版を確認しています…';
try{
const url=new URL('index.html',document.baseURI);url.searchParams.set('update',Date.now().toString());
const response=await fetch(url.href,{cache:'no-store'});
if(!response.ok)throw Error('通信エラー '+response.status);
const html=await response.text();
const version=new DOMParser().parseFromString(html,'text/html').querySelector('meta[name="app-version"]')?.content;
if(!version)throw Error('更新データを確認できませんでした');
$('update-status').textContent='最新版を開きます。記録はそのまま残ります。';
location.replace(url.href);
}catch(error){button.disabled=false;$('update-status').textContent='更新できませんでした：'+error.message+'。通信を確認して、もう一度お試しください。';}
};
let resetAnswer=null;
function resetQuiz(){const a=12+Math.floor(Math.random()*8),b=3+Math.floor(Math.random()*7);resetAnswer=a*b;$('reset-question').textContent=`${a} × ${b} =`;$('reset-answer').value='';let undo=false;try{undo=!!store.beforeReset();}catch(e){}$('reset-undo').hidden=!undo;$('reset-app').disabled=$('reset-undo').disabled=conflict;}
$('reset-app').onclick=()=>{if(conflict)return;if(Number($('reset-answer').value)!==resetAnswer||!/^\d+$/.test($('reset-answer').value.trim())){$('reset-status').textContent='確認の答えがちがいます。';resetQuiz();return;}if(!confirm(`${profiles.names[store.who]}の 正解数・開通した駅・車両カードを消して、玖波駅から最初にもどします。よろしいですか？`)){resetQuiz();return;}if(!restart()){$('reset-status').textContent='リセット前の記録を残せないため、リセットを中止しました。先にバックアップを保存してください。';return;}resetQuiz();$('reset-status').textContent='最初からに もどしました。';};
$('reset-undo').onclick=()=>{if(conflict)return;try{const data=store.beforeReset();if(!data)throw Error();C.upgradeCards(data);if(!confirm('リセット前の記録に戻しますか？ リセットのあとに進めた分は消えます。'))return;state=data;C.revive(state,Date.now());corrupt=false;entry='';selected=state.current;render();if(!conflict&&storageOK)store.dropBeforeReset();centerMap();$('parents').close();showReward();}catch(e){$('reset-status').textContent='リセット前の記録を読み込めませんでした。';}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=store.backupName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('ファイルが大きすぎます。');let data=JSON.parse(await f.text());if(data?.version===1)data=C.migrate(data);if(data?.version===2){data=C.fromV2(data,profiles.device);if(data){C.setKinds(data,state.kinds);data.news=[];}}if(!C.valid(data)||data.version!==3)throw Error('有効なバックアップではありません。');C.upgradeCards(data);if(!confirm(`${profiles.names[store.who]}の記録を、このバックアップの記録に置き換えますか？`))return;state=data;corrupt=false;conflict=false;lastSaved=store.read();entry='';selected=state.current;render();centerMap();$('parents').close();showReward();}catch(err){$('import-status').textContent='復元できませんでした。'+err.message;}finally{e.target.value='';}};
$('zoom-in').onclick=()=>zoom(.7);$('zoom-out').onclick=()=>zoom(1/.7);$('map-current').onclick=()=>centerMap();$('map-all').onclick=mapAll;
let normalCamera=null;
$('map-full').onclick=()=>{const world=document.querySelector('.world'),on=!world.classList.contains('map-expanded');if(on)normalCamera={...camera};world.classList.toggle('map-expanded',on);$('map-full').textContent=on?'もどす':'大きく見る';if(on)mapAll();else{camera={...normalCamera};normalCamera=null;camera.height=camera.width/mapAspect();updateCamera();}};
const pointers=new Map();let gesture=null,moved=false;
$('map').addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('map').setPointerCapture(e.pointerId);moved=false;gesture={x:e.clientX,y:e.clientY,camera:{...camera},distance:pointers.size===2?Math.hypot(...(()=>{const p=[...pointers.values()];return[p[0].x-p[1].x,p[0].y-p[1].y];})()):null};});
$('map').addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(gesture.distance){zoom(gesture.distance/d);gesture.distance=d;moved=true;}return;}const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;camera.x=gesture.camera.x-dx*camera.width/$('map').clientWidth;camera.y=gesture.camera.y-dy*camera.height/$('map').clientHeight;updateCamera();});
$('map').addEventListener('pointerup',e=>{if(!moved){const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-station]');if(node)showSelection(node.dataset.station);}pointers.delete(e.pointerId);gesture=null;});$('map').addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;});$('map').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.station){e.preventDefault();showSelection(e.target.dataset.station);}});
$('map').addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();zoom(e.deltaY>0?1.08:.92);}},{passive:false});
function resizeMap(){if(document.querySelector('.world').classList.contains('map-expanded'))mapAll();else{const cy=camera.y+camera.height/2;camera.height=camera.width/mapAspect();camera.y=cy-camera.height/2;updateCamera();}}
window.addEventListener('resize',resizeMap);
if(window.visualViewport)window.visualViewport.addEventListener('resize',resizeMap);
new ResizeObserver(resizeMap).observe($('map-wrap'));
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]')||e.target.closest('#map,button,input,a'))return;if(e.key==='Enter'&&state.solved){e.preventDefault();$('next').click();}else if(/^\d$/.test(e.key)){e.preventDefault();key(e.key);}else if(e.key==='Backspace'){e.preventDefault();key('clear');}else if(e.key==='Enter'){e.preventDefault();key('submit');}});
$('legend').innerHTML=R.lines.map(l=>`<span><i style="--line:${l.color}"></i>${l.name}</span>`).join('');centerMap();render();openWho();
