(function(r){const cards=[
  {
    "id": "redwing",
    "name": "227系0番台 Red Wing",
    "reading": "227けい レッドウィング",
    "category": "でんしゃ",
    "image": "assets/redwing.jpg",
    "fact": "ひろしまエリアの あかい でんしゃ。山陽本線・呉線・可部線で かつやくする 227けいだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2015/03/page_6919.html",
    "checked": "2026-09-19",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRW Series227-0 A48.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series227-0_A48.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "A rapid train \"City Liner\" bound for Hiroshima, led by the 227-0 series A48 formation, running between Itsukaichi Station and Shin-Inokuchi Station on the JR Sanyo Main Line.",
    "station": "玖波",
    "first": true
  },
  {
    "id": "mizukaze",
    "name": "TWILIGHT EXPRESS 瑞風",
    "reading": "トワイライトエクスプレス みずかぜ",
    "category": "かんこうれっしゃ",
    "image": "assets/mizukaze.jpg",
    "fact": "とまりがけで たびを する ごうかな れっしゃ。ときどき 山陽本線を はしって、宮島口や岩国にも とまるよ。",
    "factSource": "https://www.twilightexpress-mizukaze.jp/journey/course/sanyo_outbound.html",
    "checked": "2026-09-27",
    "credit": "khws4v1",
    "sourceTitle": "JRW Kiha 87 Twilight Express Mizukaze 2018-05-27.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Kiha_87_Twilight_Express_Mizukaze_2018-05-27.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR West Kiha 87 Twilight Express Mizukaze",
    "station": "宮島口"
  },
  {
    "id": "hanaakari",
    "name": "はなあかり",
    "reading": "はなあかり",
    "category": "かんこうれっしゃ",
    "image": "assets/hanaakari.jpg",
    "fact": "くろい しゃたいに きんいろの はなが えがかれた かんこうれっしゃ。2026ねんの はるに、広島から 宮島口を とおって 岩国まで はしったよ。",
    "factSource": "https://news.mynavi.jp/article/20260128-4050543/",
    "checked": "2026-09-27",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の はなあかり.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#hanaakari",
    "change": "撮影者提供の写真を長辺1280pxへ縮小し、写っている人（乗務員・乗客）にモザイク。撮影情報を削除。トリミング・AI補正・描き換えなし。",
    "photoDescription": "駅に停車中の観光列車「はなあかり」（キハ189系8005）の正面",
    "station": "五日市"
  },
  {
    "id": "ef210",
    "name": "JR貨物 EF210形（ECO-POWER 桃太郎）",
    "reading": "EF210がた　ももたろう",
    "category": "かもつれっしゃ",
    "image": "assets/ef210.jpg",
    "fact": "山陽本線で かもつれっしゃを ひく「ももたろう」。広島えきの ちかくには、かもつれっしゃの えきも あるよ。",
    "factSource": "https://www.jrfreight.co.jp/",
    "checked": "2026-09-27",
    "credit": "Mitsuki-2368",
    "sourceTitle": "JRF EF210-111 20211218.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRF_EF210-111_20211218.jpg",
    "change": "長辺1280pxへ縮小・JPEG再圧縮。トリミング・描き換えなし。",
    "photoDescription": "山陽本線 庭瀬〜中庄間を走行するEF210-111号機（キャラクターラッピング仕様）",
    "station": "広島"
  },
  {
    "id": "ef210-300",
    "name": "JR貨物 EF210形300番台",
    "reading": "EF210がた 300ばんだい",
    "category": "かもつれっしゃ",
    "image": "assets/ef210-300.jpg",
    "fact": "瀬野と 八本松の あいだは きゅうな さかみち。おもい かもつれっしゃを うしろから おして たすける きかんしゃだよ。「おしたろう」と よばれることも あるよ。",
    "factSource": "https://ja.wikipedia.org/wiki/JR%E8%B2%A8%E7%89%A9EF210%E5%BD%A2%E9%9B%BB%E6%B0%97%E6%A9%9F%E9%96%A2%E8%BB%8A",
    "checked": "2026-09-27",
    "credit": "kh ws",
    "sourceTitle": "EF210-306 Saijo 20151024.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:EF210-306_Saijo_20151024.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR Freight Class EF210-300 electric locomotive EF210-306 at the rear of a freight train at Saijo Station",
    "station": "瀬野"
  },
  {
    "id": "carp",
    "name": "227系0番台 カープ応援ラッピング（2026）",
    "reading": "227けい カープおうえん ラッピング",
    "category": "でんしゃ",
    "image": "assets/carp2026.jpg",
    "fact": "ひろしまの プロやきゅう チーム、カープを おうえんする でんしゃ。2026ねんは 山陽本線と 呉線を はしるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/260220_00_press_Carpouenwrappingtrain2026.pdf",
    "checked": "2026-09-27",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の カープ応援ラッピングトレイン（動画の1コマ）.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#carp",
    "change": "撮影者提供の動画から1コマを切り出し、電車のまわりをトリミング。撮影情報なし。AI補正・描き換えなし。",
    "photoDescription": "夜の駅に入ってくる227系のカープ応援ラッピングトレインの正面",
    "station": "西条"
  },
  {
    "id": "urara",
    "name": "227系500番台 Urara",
    "reading": "227けい Urara（うらら）",
    "category": "でんしゃ",
    "image": "assets/urara.jpg",
    "fact": "おかやま・びんごエリアの 227けい。三原まで くると、Uraraの はしる エリアに つながるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/230529_00_press_okatetsu.pdf",
    "checked": "2026-09-19",
    "credit": "Travelweb.au",
    "sourceTitle": "227-500 series \"Urara\" at Uno Station.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:227-500_series_%22Urara%22_at_Uno_Station.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "宇野駅に停車する227系500番台Urara",
    "station": "三原"
  },
  {
    "id": "greenmover",
    "name": "227系0番台 グリーンムーバーカラー",
    "reading": "227けい グリーンムーバーカラー",
    "category": "でんしゃ",
    "image": "assets/greenmover227.jpg",
    "fact": "ひろでんの ろめんでんしゃ「グリーンムーバーマックス」と いろを とりかえっこした 227けい。可部線も はしるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/240820_00_press_hiroshima_wrappingtrain.pdf",
    "checked": "2026-09-27",
    "credit": "KageroYukikaze",
    "sourceTitle": "JRW-Series227-0 A12 Green Mover Max.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW-Series227-0_A12_Green_Mover_Max.jpg",
    "change": "Wikimedia提供の縮小画像（1280×1920px）から、電車のまわりを横長（1280×900px）にトリミング。AI補正・描き換えなし。",
    "photoDescription": "JR West 227-0 Series 3-car set A12 in Hiroshima Electric Railway \"Green Mover Max\" livery, Kure Station.",
    "station": "可部"
  },
  {
    "id": "etsetora",
    "image": "assets/etsetora.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:%E8%A5%BF%E5%BA%83%E5%B3%B6%E9%A7%85%E3%82%92%E9%80%9A%E9%81%8E%E3%81%99%E3%82%8BetSETOra(2021%E5%B9%B4).jpg",
    "sourceTitle": "西広島駅を通過するetSETOra(2021年).jpg",
    "credit": "勇敢な夕刊",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "西広島駅を通過するetSETOra",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-22",
    "station": "呉",
    "name": "etSETOra（エトセトラ）",
    "fact": "呉線を とおって せとうちを たびする かんこうれっしゃ。うみの あおと、なみの しろを まとっているよ。",
    "factSource": "https://www.jr-odekake.net/railroad/kankoutrain/etsetora/"
  },
  {
    "id": "rose",
    "name": "227系0番台 ばらのラッピング",
    "reading": "227けい ばらの ラッピング",
    "category": "でんしゃ",
    "image": "assets/rose227.jpg",
    "fact": "「ばらの まち」福山を しょうかいする でんしゃ。おおきな ばらと 花びらが えがかれて、呉線を ぜんぶ はしるよ。",
    "factSource": "https://railf.jp/news/2026/05/16/002000.html",
    "checked": "2026-09-27",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の 227系 ばらのラッピングトレイン.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#rose",
    "change": "撮影者提供の写真を長辺1280pxへ縮小し、写っている人（乗客・ホームの人）にモザイク。撮影情報を削除。AI補正・描き換えなし。",
    "photoDescription": "広島駅に停車中の227系A46編成（ばらのラッピングトレイン）の正面と側面",
    "station": "竹原"
  },
  {
    "id": "kiha40",
    "name": "キハ40形（朱色）",
    "reading": "キハ40がた",
    "category": "ディーゼルしゃ",
    "image": "assets/kiha40-shuiro.jpg",
    "fact": "芸備線の 広島〜三次を はしる オレンジいろの ディーゼルしゃ。うんてんせきが りょうほうに あるから、1りょうでも はしれるよ。",
    "factSource": "https://www.city.miyoshi.hiroshima.jp/soshiki/8/1396.html",
    "checked": "2026-09-27",
    "credit": "Hisagi",
    "sourceTitle": "JR West Kiha40 2045.png",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JR_West_Kiha40_2045.png",
    "change": "Wikimedia提供画像をJPEGに変換。トリミング・AI補正なし。",
    "photoDescription": "JR西日本、キハ40 2045（首都圏色）",
    "station": "下深川"
  },
  {
    "id": "kiha47",
    "name": "キハ47形（朱色）",
    "reading": "キハ47がた",
    "category": "ディーゼルしゃ",
    "image": "assets/kiha40-gantoku.jpg",
    "fact": "岩国えきで あえる オレンジいろの ディーゼルしゃ。うんてんせきは かたほうだけ。しゃしんは 岩徳線で、にしきがわの てっきょうを わたるところだよ。",
    "factSource": "https://commons.wikimedia.org/wiki/File:JRW_Gantoku-line_Kiha47.jpg",
    "checked": "2026-09-27",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRW Gantoku-line Kiha47.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Gantoku-line_Kiha47.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "A local train of JR West's Kiha 40 series 47 and 40 that crosses the Nishiki River between Nishi-Iwakuni Station and Kawanishi Station on the Iwantoku Line.",
    "station": "岩国"
  },
  {
    "id": "115",
    "image": "assets/115.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series115-3000_N-16.jpg",
    "sourceTitle": "JRW Series115-3000 N-16.jpg",
    "credit": "MaedaAkihiko",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "A local train with the 115-3000 series N-16 formation that runs between Shin-Shimonoseki Station and Chofu Station on the Sanyo Main Line.",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-27",
    "station": "柳井",
    "name": "115系3000番台",
    "fact": "山陽本線で かつやくしてきた きいろい でんしゃ。しゃしんは やまぐちエリアの 115けい 3000ばんだいだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/160122_00_spring_hiroshima.pdf"
  },
  {
    "id": "ginga",
    "name": "WEST EXPRESS 銀河",
    "reading": "ウエストエクスプレス ぎんが",
    "category": "かんこうれっしゃ",
    "image": "assets/ginga.jpg",
    "fact": "よるも はしる かんこうれっしゃ。ときどき 山陽本線を とおって、しものせきまで いくよ。よぞらの ような こいあおいろ。",
    "factSource": "https://www.jr-odekake.net/railroad/westexginga/course_sanyo/",
    "checked": "2026-09-27",
    "credit": "交通大臣 鉄道チャンネル",
    "sourceTitle": "JRW West Express Ginga Hiroshima 2020-04-16.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_West_Express_Ginga_Hiroshima_2020-04-16.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "Luxury train West Express Ginga conducting staff training at Hiroshima Station, April 16, 2020.",
    "station": "光"
  },
  {
    "id": "kizashi",
    "name": "227系500番台 Kizashi",
    "reading": "227けい Kizashi（きざし）",
    "category": "でんしゃ",
    "image": "assets/kizashi.jpg",
    "fact": "やまぐちエリアの 227けい。山陽本線の 岩国〜しものせきを はしる、くろと きんいろの Kizashiだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2026/05/29/items/260529_00_press_Kizashi_shixyupatushiki.pdf",
    "checked": "2026-09-19",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の227系500番台 Kizashi.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#kizashi",
    "change": "撮影者提供の写真をそのまま使用。AI補正・描き換えなし。",
    "photoDescription": "線路上を走る227系500番台Kizashiを遠方から撮影した写真",
    "station": "徳山"
  },
  {
    "id": "nt3001",
    "name": "NT3000形 せせらぎ号",
    "reading": "NT3000がた せせらぎごう",
    "category": "ディーゼルしゃ",
    "image": "assets/nt3001.jpg",
    "fact": "錦川清流線を はしる 4りょうの ディーゼルカーの 1りょう。「清流の ブルー」の しゃたいに、川の さかなの 絵が かいてあるよ。",
    "factSource": "https://ja.wikipedia.org/wiki/%E9%8C%A6%E5%B7%9D%E9%89%84%E9%81%93NT3000%E5%BD%A2%E6%B0%97%E5%8B%95%E8%BB%8A",
    "checked": "2026-09-30",
    "credit": "そらみみ",
    "sourceTitle": "Train for Nishikicho Station at Seiryu-Shin-Iwakuni Station 2.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Train_for_Nishikicho_Station_at_Seiryu-Shin-Iwakuni_Station_2.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "清流新岩国駅に停車中の錦町行き錦川清流線列車",
    "station": "清流新岩国"
  },
  {
    "id": "nt3002",
    "name": "NT3000形 ひだまり号",
    "reading": "NT3000がた ひだまりごう",
    "category": "ディーゼルしゃ",
    "image": "assets/nt3002.jpg",
    "fact": "「桜の ピンク」の NT3000がた。しゃたいいっぱいに さくらの はなが さいているよ。",
    "factSource": "https://ja.wikipedia.org/wiki/%E9%8C%A6%E5%B7%9D%E9%89%84%E9%81%93NT3000%E5%BD%A2%E6%B0%97%E5%8B%95%E8%BB%8A",
    "checked": "2026-09-30",
    "credit": "Rsa",
    "sourceTitle": "Nishikigawa Railway DMU NT3002.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Nishikigawa_Railway_DMU_NT3002.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "錦川鉄道錦川清流線の所属車両：ひだまり号(NT-3000型)",
    "station": "北河内"
  },
  {
    "id": "nt3003",
    "name": "NT3000形 こもれび号",
    "reading": "NT3000がた こもれびごう",
    "category": "ディーゼルしゃ",
    "image": "assets/nt3003.jpg",
    "fact": "「森林の グリーン」の NT3000がた。はっぱと カワセミの 絵が かいてあるよ。",
    "factSource": "https://ja.wikipedia.org/wiki/%E9%8C%A6%E5%B7%9D%E9%89%84%E9%81%93NT3000%E5%BD%A2%E6%B0%97%E5%8B%95%E8%BB%8A",
    "checked": "2026-09-30",
    "credit": "MaedaAkihiko",
    "sourceTitle": "Nishikigawa NT3000-3003.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Nishikigawa_NT3000-3003.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "NT3000 series diesel railcar (NT-3003) of the Nishikigawa Seiryu Line, running between Nishi-Iwakuni Station and Iwakuni Station on the JR Gantoku Line.",
    "station": "根笠"
  },
  {
    "id": "nt3004",
    "name": "NT3000形 きらめき号",
    "reading": "NT3000がた きらめきごう",
    "category": "ディーゼルしゃ",
    "image": "assets/nt3004.jpg",
    "fact": "「蛍の ひかりの イエロー」の NT3000がた。ほたるが とんでいる 絵が かいてあるよ。",
    "factSource": "https://ja.wikipedia.org/wiki/%E9%8C%A6%E5%B7%9D%E9%89%84%E9%81%93NT3000%E5%BD%A2%E6%B0%97%E5%8B%95%E8%BB%8A",
    "checked": "2026-09-30",
    "credit": "TRJN",
    "sourceTitle": "Nishikigawa Railway DMU NT3004.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Nishikigawa_Railway_DMU_NT3004.JPG",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "NT-3004 きらめき号",
    "station": "錦町"
  },
  {
    "id": "c57",
    "name": "SLやまぐち号 C57形1号機",
    "reading": "SLやまぐちごう C57がた 1ごうき",
    "category": "じょうききかんしゃ",
    "image": "assets/c57.jpg",
    "fact": "けむりを はいて はしる じょうききかんしゃ（SL）。新山口から 山口線の 津和野まで、むかしふうの 客車を ひっぱって はしるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2026/05/29/items/260529_00_press_slyamaguchigou.pdf",
    "checked": "2026-10-02",
    "credit": "khws4v1",
    "sourceTitle": "SL Yamaguchi 2017 (26381048739).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:SL_Yamaguchi_2017_(26381048739).jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "C571 + 35系",
    "station": "新山口"
  },
  {
    "id": "redwing-fukuyama",
    "name": "ふくやまの Red Wing",
    "reading": "ふくやまの レッドウィング",
    "category": "でんしゃ",
    "image": "assets/redwing-fukuyama-crop.jpg",
    "fact": "ひろしまエリアの あかい 227けい Red Wing は、2016ねんから 福山まで くるように なったよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/151218_05_okayama.pdf",
    "checked": "2026-10-03",
    "credit": "ひかり500号",
    "sourceTitle": "227-0 普通福山行.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:227-0_%E6%99%AE%E9%80%9A%E7%A6%8F%E5%B1%B1%E8%A1%8C.jpg",
    "change": "Wikimedia提供の元画像（459×914px）の上下を切り抜き（459×450px、車両の前の部分）。引き伸ばし・AI補正なし。",
    "photoDescription": "Series 227 0 bound for Fukuyama",
    "station": "福山",
    "sameTrain": "redwing"
  },
  {
    "id": "lamalle",
    "name": "La Malle de Bois ラ・マル しまなみ",
    "reading": "ラ・マル・ド・ボァ ラ・マル しまなみ",
    "category": "かんこうれっしゃ",
    "image": "assets/lamalle.jpg",
    "fact": "「はしる たびの どうぐばこ（トランク）」が テーマの かんこうれっしゃ。じてんしゃも つめるよ。岡山から 倉敷・笠岡・福山・尾道に とまって 三原まで はしるよ。",
    "factSource": "https://www.jr-odekake.net/railroad/kankoutrain/lamalledebois/",
    "checked": "2026-10-03",
    "credit": "Rsa",
    "sourceTitle": "JRW 213-7000 La Malle de Bois 20160410.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_213-7000_La_Malle_de_Bois_20160410.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "The JR West 213 series La Malle de Bois tourist train at Okayama Station",
    "station": "倉敷"
  },
  {
    "id": "marineliner",
    "name": "快速マリンライナー 5000系",
    "reading": "かいそく マリンライナー 5000けい",
    "category": "でんしゃ",
    "image": "assets/marineliner.jpg",
    "fact": "岡山と 四国の 高松を むすぶ 快速。せんとうの 車両は 2かいだてで、2かいからは 瀬戸大橋から 瀬戸内海が みえるよ。",
    "factSource": "https://www.jr-shikoku.co.jp/01_trainbus/syaryou/marine.shtm",
    "checked": "2026-10-03",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRS Series5000-M5 Marine-liner-41.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:JRS_Series5000-M5_Marine-liner-41.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "Rapid \"Marine Liner\" No. 41 bound for Takamatsu, led by JR Shikoku 5000 Series M5 formation entering Kimi Station on JR West's Seto Ohashi Line.",
    "station": "岡山"
  },
  {
    "id": "n700a",
    "name": "N700A",
    "reading": "N700エー",
    "category": "しんかんせん",
    "image": "assets/n700a.jpg",
    "fact": "東海道新幹線と 山陽新幹線を はしる しんかんせん。山陽新幹線では さいこう 300km/hで はしるよ。写真は 2019年の F21編成。",
    "factSource": "https://railway.jr-central.co.jp/train/shinkansen/detail_01_01/index.html",
    "checked": "2026-10-04",
    "credit": "Cheng-en Cheng from Taichung City, Taiwan",
    "sourceTitle": "Shinkansen N700-4000 F21 (49766090912).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Shinkansen_N700-4000_F21_(49766090912).jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR West N700A (N700-4000 series) set F21, 2019-11-15",
    "first": "shinkansen",
    "track": "しんかんせん"
  },
  {
    "id": "mizuho",
    "name": "みずほ・さくら N700系8両",
    "reading": "みずほ さくら N700けい 8りょう",
    "category": "しんかんせん",
    "image": "assets/mizuho.jpg",
    "fact": "新大阪と 九州の 鹿児島中央を むすぶ みずほ・さくら。九州新幹線の きゅうな さかを のぼるため、8両 ぜんぶに モーターが ついているよ。写真は 姫路駅の S8編成。",
    "factSource": "https://www.jr-odekake.net/railroad/shinkansen/mizuho/",
    "checked": "2026-10-04",
    "credit": "Santetsu",
    "sourceTitle": "N700系S8編成.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:N700%E7%B3%BBS8%E7%B7%A8%E6%88%90.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "姫路駅にて（N700系S8編成、2024年5月3日）",
    "station": "博多",
    "track": "しんかんせん"
  },
  {
    "id": "railstar",
    "name": "ひかりレールスター 700系",
    "reading": "ひかりレールスター 700けい",
    "category": "しんかんせん",
    "image": "assets/railstar.jpg",
    "fact": "新大阪と 博多の あいだを、ひかりや こだまとして はしる 8両の 700系。ひかりレールスターの 8号車には 4人用の 個室が あるよ。",
    "factSource": "https://www.jr-odekake.net/railroad/train/700_8/",
    "checked": "2026-10-04",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRW Series700-7000-E9 Hikari592.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series700-7000-E9_Hikari592.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "\"Hikari Rail Star\" No. 592 bound for Shin-Osaka by JR West's 700-7000 series E9 formation running between Okayama Station and Aioi Station on the Sanyo Shinkansen.",
    "station": "姫路",
    "track": "しんかんせん"
  },
  {
    "id": "500",
    "name": "500系 こだま",
    "reading": "500けい こだま",
    "category": "しんかんせん",
    "image": "assets/500-v8.jpg",
    "fact": "1997年に デビューした ときは、300km/hで はしる 日本で いちばん はやい しんかんせん だったよ。いまは 8両の こだま。2027年1月13日に ふだんの うんてんを おえる よていだよ。写真は 姫路駅に とまる 新大阪ゆきの こだま。",
    "factSource": "https://www.westjr.co.jp/press/article/2026/06/22/items/260622_00_press_500kei_dryellow.pdf",
    "checked": "2026-10-04",
    "credit": "Santetsu",
    "sourceTitle": "500-V8.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:500-V8.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "A 500 series V formation stopping at Himeji Station as the Kodama train bound for Shin-Osaka.",
    "station": "新大阪",
    "track": "しんかんせん"
  },
  {
    "id": "zero",
    "name": "0系 新幹線",
    "reading": "0けい しんかんせん",
    "category": "しんかんせん",
    "image": "assets/zero.jpg",
    "fact": "1964年に 東海道新幹線が はじまったときに はしった、さいしょの 新幹線。まるい 鼻が 目じるしで、さいこう 210km/hで はしったよ。写真は 京都鉄道博物館の 21形1号車。",
    "factSource": "https://www.kyotorailwaymuseum.jp/enjoying/watching/vehicle/main-building/",
    "checked": "2026-10-05",
    "credit": "BWard 1997",
    "sourceTitle": "0 Series Shinkansen 21-1 Kyoto Railway Museum 20-09-2024.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:0_Series_Shinkansen_21-1_Kyoto_Railway_Museum_20-09-2024.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "Car 21-1 from the iconic 0 Series Shinkansen class, the original high speed Bullet Train, on display outside in the Promenade area at the Kyoto Railway Museum.",
    "station": "京都",
    "track": "しんかんせん"
  },
  {
    "id": "doctoryellow",
    "name": "ドクターイエロー 923形",
    "reading": "ドクターイエロー 923がた",
    "category": "しんかんせん",
    "image": "assets/doctoryellow.jpg",
    "fact": "きいろい「新幹線の おいしゃさん」。やく10日に 1ど、はしりながら 線路や 電気の せつびを しらべていたよ。2025年1月に 引退して、いまは 名古屋の リニア・鉄道館で 先頭車に 会えるよ。さいこう 270km/h。",
    "factSource": "https://jr-central.co.jp/news/release/_pdf/000044016.pdf",
    "checked": "2026-10-05",
    "credit": "MaedaAkihiko",
    "sourceTitle": "Type923-T4.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Type923-T4.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "Shinkansen electric track comprehensive test car, 923 type T4 formation (Doctor Yellow) running between Hamamatsu and Toyohashi on the Tokaido Shinkansen.",
    "station": "名古屋",
    "track": "しんかんせん"
  },
  {
    "id": "n700s",
    "name": "N700S",
    "reading": "N700エス",
    "category": "しんかんせん",
    "image": "assets/n700s.jpg",
    "fact": "2020年に デビューした あたらしい 新幹線。東海道新幹線では さいこう 285km/h、山陽新幹線では 300km/hで はしるよ。電気が とまっても、バッテリーで うごける しくみが あるんだ。写真は 浜名湖の そばを はしる J2編成。",
    "factSource": "https://railway.jr-central.co.jp/train/shinkansen/n700s/",
    "checked": "2026-10-05",
    "credit": "MaedaAkihiko",
    "sourceTitle": "Series-N700S-J2.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Series-N700S-J2.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "N700S series J2 set belonging to JR Tokai, running between Hamamatsu and Toyohashi on the Tokaido Shinkansen.",
    "station": "静岡",
    "track": "しんかんせん"
  },
  {
    "id": "e5",
    "name": "E5系 はやぶさ",
    "reading": "E5けい はやぶさ",
    "category": "しんかんせん",
    "image": "assets/e5.jpg",
    "fact": "東京と 東北・北海道を むすぶ はやぶさ。ながーい 鼻が 目じるしで、さいこう 320km/hで はしるよ。東京駅では 東海道新幹線の となりに やってくるんだ。写真は 大宮駅に 入る 東京ゆきの はやぶさ。",
    "factSource": "https://www.jreast.co.jp/train/shinkan/e5.html",
    "checked": "2026-10-05",
    "credit": "MaedaAkihiko",
    "sourceTitle": "Series-E5-U44 Hayabusa-2.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Series-E5-U44_Hayabusa-2.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "\"Hayabusa\" No. 2 bound for Tokyo by E5 series U44 organization entering Omiya station of Tohoku Shinkansen.",
    "station": "東京",
    "track": "しんかんせん"
  },
  {
    "id": "813",
    "name": "813系",
    "reading": "813けい",
    "category": "でんしゃ",
    "image": "assets/813.jpg",
    "fact": "博多や 北九州の 鹿児島本線などを はしる、あかい ふつう でんしゃ。1994ねんに とうじょうしたよ。写真は 2026ねんの 博多駅。",
    "factSource": "https://tetsudo-ch.com/12926937.html",
    "checked": "2026-10-07",
    "credit": "画像提供依頼をやりたいだけ",
    "sourceTitle": "813系R108編成(赤屋根).jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:813系R108編成(赤屋根).jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR Kyushu 813 series set R108 (red roof) at Hakata Station, 2026-03-08.",
    "first": "kagoshima"
  },
  {
    "id": "dencha",
    "name": "BEC819系 DENCHA",
    "reading": "BEC819けい デンチャ",
    "category": "でんしゃ",
    "image": "assets/dencha.jpg",
    "fact": "かせんの ある ところで バッテリーに でんきを ためて、かせんの ない 香椎線を はしる ちくでんち でんしゃ。2019ねんから 香椎線の れっしゃは ぜんぶ DENCHA だよ。",
    "factSource": "https://trafficnews.jp/post/82377",
    "checked": "2026-10-07",
    "credit": "Rsa",
    "sourceTitle": "JR Kyushu KumohaBEC819-106.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JR_Kyushu_KumohaBEC819-106.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR Kyushu BEC819 series (KumohaBEC819-106), 2021-05-31.",
    "station": "香椎"
  },
  {
    "id": "821",
    "name": "821系",
    "reading": "821けい",
    "category": "でんしゃ",
    "image": "assets/821.jpg",
    "fact": "2019ねんに 鹿児島本線で デビューした あたらしい ふつう でんしゃ。つかう でんきが まえの でんしゃより 7わりも すくないよ。写真の うしろは 811けい。",
    "factSource": "https://trafficnews.jp/post/83273",
    "checked": "2026-10-08",
    "credit": "こはるん",
    "sourceTitle": "JR Kyushu 821 Series & 811 Series.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:JR_Kyushu_821_Series_%26_811_Series.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "鹿児島本線竹下駅、821系と811系(リニューアル車)の併結（2019-10-20）",
    "station": "福間"
  },
  {
    "id": "ef510-300",
    "name": "JR貨物 EF510形300番台（ECO-POWER レッドサンダー）",
    "reading": "EF510がた 300ばんだい レッドサンダー",
    "category": "かもつれっしゃ",
    "image": "assets/ef510-300.jpg",
    "fact": "九州の かもつれっしゃを ひく ぎんいろの きかんしゃ「レッドサンダー」。2023ねんから 九州を はしりはじめた あたらしい きかんしゃだよ。",
    "factSource": "https://tetsudo-ch.com/11856098.html",
    "checked": "2026-10-08",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRF EF510-301 Nippo-main-Line.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRF_EF510-301_Nippo-main-Line.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "A container freight train pulled by JR Freight's EF510-301 running between Takajo Station and Tsurusaki Station on the Nippo Main Line (2024-01-07).",
    "station": "黒崎"
  },
  {
    "id": "883",
    "name": "883系 特急ソニック",
    "reading": "883けい とっきゅう ソニック",
    "category": "とっきゅう",
    "image": "assets/883.jpg",
    "fact": "小倉を とおって 博多と 大分を むすぶ とっきゅう「ソニック」。あおい からだの 883けいは、2027ねんの はるごろから なかも あたらしく なるよ。",
    "factSource": "https://www.jrkyushu.co.jp/trains/sonic/",
    "checked": "2026-10-08",
    "credit": "東風みるく",
    "sourceTitle": "L Kagoshima 883.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:L_Kagoshima_883.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR鹿児島本線枝光駅で撮影（2018-01-20）",
    "station": "小倉"
  }
];if(typeof module!=='undefined')module.exports=cards;else r.RailCards=cards;})(globalThis);
