(function(r){const cards=[
  {
    "id": "redwing",
    "name": "227系0番台 Red Wing",
    "reading": "227けい レッドウィング",
    "category": "でんしゃ",
    "image": "assets/redwing.jpg",
    "fact": "ひろしまエリアの あかい でんしゃ。山陽本線・呉線・可部線で かつやくする 227けいだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2015/03/page_6919.html",
    "checked": "2026-09-19",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRW Series227-0 A48.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series227-0_A48.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "A rapid train \"City Liner\" bound for Hiroshima, led by the 227-0 series A48 formation, running between Itsukaichi Station and Shin-Inokuchi Station on the JR Sanyo Main Line.",
    "station": "玖波",
    "first": true
  },
  {
    "id": "apex",
    "name": "広島電鉄5200形 Greenmover APEX",
    "reading": "ひろでん 5200がた グリーンムーバー エイペックス",
    "category": "ろめんでんしゃ",
    "image": "assets/apex.jpg",
    "fact": "2019ねん、ひろでん宮島口えきで しゅっぱつしきを して デビューした ろめんでんしゃ。5つの しゃたいが つながっているよ。",
    "factSource": "https://news.mynavi.jp/article/20190314-greenmoverapex/",
    "checked": "2026-09-24",
    "credit": "MaedaAkihiko",
    "sourceTitle": "Hiroden Series5200-5205B Ekimae-route-HM.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Hiroden_Series5200-5205B_Ekimae-route-HM.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "A train bound for Nishi-Hiroshima, operated by 5200 series 5205 set, runs between Takanobashi Station and Shiyakusho-mae Station on the Hiroshima Electric Railway Ujina Line.",
    "station": "宮島口"
  },
  {
    "id": "500",
    "name": "500系新幹線",
    "reading": "500けい しんかんせん",
    "category": "しんかんせん",
    "image": "assets/500.jpg",
    "fact": "広島えきには、さんよう しんかんせんも やってくるよ。これは しんかんせんの 500けい。ざいらいせんとは べつの せんろを はしるよ。",
    "factSource": "https://commons.wikimedia.org/wiki/File:JR_West_500_series_shinkansen_set_V8_at_Hakata_Station_20200115.jpg",
    "checked": "2026-09-19",
    "credit": "Rick888chen",
    "sourceTitle": "JR West 500 series shinkansen set V8 at Hakata Station 20200115.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JR_West_500_series_shinkansen_set_V8_at_Hakata_Station_20200115.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "JR West 500 series shinkansen set V8 at Hakata Station",
    "station": "広島"
  },
  {
    "id": "ef210",
    "name": "JR貨物 EF210形（ECO-POWER 桃太郎）",
    "reading": "EF210がた　ももたろう",
    "category": "かもつれっしゃ",
    "image": "assets/ef210.jpg",
    "fact": "山陽本線でも かもつれっしゃを ひく「ももたろう」。おもい にもつを はこぶ でんききかんしゃだよ。",
    "factSource": "https://www.jrfreight.co.jp/",
    "checked": "2026-09-20",
    "credit": "Mitsuki-2368",
    "sourceTitle": "JRF EF210-111 20211218.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRF_EF210-111_20211218.jpg",
    "change": "長辺1280pxへ縮小・JPEG再圧縮。トリミング・描き換えなし。",
    "photoDescription": "山陽本線 庭瀬〜中庄間を走行するEF210-111号機（キャラクターラッピング仕様）",
    "station": "西条"
  },
  {
    "id": "urara",
    "name": "227系500番台 Urara",
    "reading": "227けい Urara（うらら）",
    "category": "でんしゃ",
    "image": "assets/urara.jpg",
    "fact": "おかやま・びんごエリアの 227けい。三原まで くると、Uraraの はしる エリアに つながるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/230529_00_press_okatetsu.pdf",
    "checked": "2026-09-19",
    "credit": "Travelweb.au",
    "sourceTitle": "227-500 series \"Urara\" at Uno Station.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:227-500_series_%22Urara%22_at_Uno_Station.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "宇野駅に停車する227系500番台Urara",
    "station": "三原"
  },
  {
    "id": "kizashi",
    "name": "227系500番台 Kizashi",
    "reading": "227けい Kizashi（きざし）",
    "category": "でんしゃ",
    "image": "assets/kizashi.jpg",
    "fact": "やまぐちエリアの 227けい。山陽本線の 岩国〜しものせきを はしる、くろと きんいろの Kizashiだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2026/05/29/items/260529_00_press_Kizashi_shixyupatushiki.pdf",
    "checked": "2026-09-19",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の227系500番台 Kizashi.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#kizashi",
    "change": "撮影者提供の写真をそのまま使用。AI補正・描き換えなし。",
    "photoDescription": "線路上を走る227系500番台Kizashiを遠方から撮影した写真",
    "station": "徳山"
  },
  {
    "id": "kiha40-gantoku",
    "image": "assets/kiha40-gantoku.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Gantoku-line_Kiha47.jpg",
    "sourceTitle": "JRW Gantoku-line Kiha47.jpg",
    "credit": "MaedaAkihiko",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "A local train of JR West's Kiha 40 series 47 and 40 that crosses the Nishiki River between Nishi-Iwakuni Station and Kawanishi Station on the Iwantoku Line.",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "checked": "2026-09-24",
    "station": "岩国",
    "name": "キハ40系（岩徳線）",
    "reading": "キハ40けい がんとくせん",
    "category": "ディーゼルしゃ",
    "fact": "岩徳線を はしる オレンジいろの ディーゼルしゃ。しゃしんは 西岩国と 川西の あいだで、にしきがわの てっきょうを わたるところだよ。",
    "factSource": "https://commons.wikimedia.org/wiki/File:JRW_Gantoku-line_Kiha47.jpg"
  },
  {
    "id": "115",
    "image": "assets/115.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series115-3000_N-16.jpg",
    "sourceTitle": "JRW Series115-3000 N-16.jpg",
    "credit": "MaedaAkihiko",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "A local train with the 115-3000 series N-16 formation that runs between Shin-Shimonoseki Station and Chofu Station on the Sanyo Main Line.",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-22",
    "station": "南岩国",
    "name": "115系3000番台",
    "fact": "山陽本線で かつやくしてきた きいろい でんしゃ。しゃしんは やまぐちエリアの 115けい 3000ばんだいだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/160122_00_spring_hiroshima.pdf"
  },
  {
    "id": "kiha40",
    "image": "assets/kiha40.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Jrw-dc40-hiroshima.jpg",
    "sourceTitle": "Jrw-dc40-hiroshima.jpg",
    "credit": "Taisyo",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "photoDescription": "2004年6月本人撮影\n40系気動車",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-22",
    "station": "下深川",
    "name": "キハ40形（広島色）",
    "fact": "芸備線に ゆかりのある ディーゼルしゃ。しゃしんは 2004ねんの ひろしまいろ。むかしの すがたも あつめよう。",
    "factSource": "https://www.pref.hiroshima.lg.jp/site/hiroshimalocalline/geibisen-gaiyou.html"
  },
  {
    "id": "etsetora",
    "image": "assets/etsetora.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:%E8%A5%BF%E5%BA%83%E5%B3%B6%E9%A7%85%E3%82%92%E9%80%9A%E9%81%8E%E3%81%99%E3%82%8BetSETOra(2021%E5%B9%B4).jpg",
    "sourceTitle": "西広島駅を通過するetSETOra(2021年).jpg",
    "credit": "勇敢な夕刊",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "西広島駅を通過するetSETOra",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-22",
    "station": "呉",
    "name": "etSETOra（エトセトラ）",
    "fact": "呉線を とおって せとうちを たびする かんこうれっしゃ。うみの あおと、なみの しろを まとっているよ。",
    "factSource": "https://www.jr-odekake.net/railroad/kankoutrain/etsetora/"
  }
];if(typeof module!=='undefined')module.exports=cards;else r.RailCards=cards;})(globalThis);
