(function(r){const cards=[
  {
    "id": "redwing",
    "name": "227系0番台 Red Wing",
    "reading": "227けい レッドウィング",
    "category": "でんしゃ",
    "image": "assets/redwing.jpg",
    "fact": "ひろしまエリアの あかい でんしゃ。山陽本線・呉線・可部線で かつやくする 227けいだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2015/03/page_6919.html",
    "checked": "2026-09-19",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRW Series227-0 A48.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series227-0_A48.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "A rapid train \"City Liner\" bound for Hiroshima, led by the 227-0 series A48 formation, running between Itsukaichi Station and Shin-Inokuchi Station on the JR Sanyo Main Line.",
    "station": "玖波",
    "first": true
  },
  {
    "id": "mizukaze",
    "name": "TWILIGHT EXPRESS 瑞風",
    "reading": "トワイライトエクスプレス みずかぜ",
    "category": "かんこうれっしゃ",
    "image": "assets/mizukaze.jpg",
    "fact": "とまりがけで たびを する ごうかな れっしゃ。ときどき 山陽本線を はしって、宮島口や岩国にも とまるよ。",
    "factSource": "https://www.twilightexpress-mizukaze.jp/journey/course/sanyo_outbound.html",
    "checked": "2026-09-27",
    "credit": "khws4v1",
    "sourceTitle": "JRW Kiha 87 Twilight Express Mizukaze 2018-05-27.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Kiha_87_Twilight_Express_Mizukaze_2018-05-27.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR West Kiha 87 Twilight Express Mizukaze",
    "station": "宮島口"
  },
  {
    "id": "hanaakari",
    "name": "はなあかり",
    "reading": "はなあかり",
    "category": "かんこうれっしゃ",
    "image": "assets/hanaakari.jpg",
    "fact": "くろい しゃたいに きんいろの はなが えがかれた かんこうれっしゃ。2026ねんの はるに、広島から 宮島口を とおって 岩国まで はしったよ。",
    "factSource": "https://news.mynavi.jp/article/20260128-4050543/",
    "checked": "2026-09-27",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の はなあかり.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#hanaakari",
    "change": "撮影者提供の写真を長辺1280pxへ縮小し、写っている人（乗務員・乗客）にモザイク。撮影情報を削除。トリミング・AI補正・描き換えなし。",
    "photoDescription": "駅に停車中の観光列車「はなあかり」（キハ189系8005）の正面",
    "station": "五日市"
  },
  {
    "id": "ef210",
    "name": "JR貨物 EF210形（ECO-POWER 桃太郎）",
    "reading": "EF210がた　ももたろう",
    "category": "かもつれっしゃ",
    "image": "assets/ef210.jpg",
    "fact": "山陽本線で かもつれっしゃを ひく「ももたろう」。広島えきの ちかくには、かもつれっしゃの えきも あるよ。",
    "factSource": "https://www.jrfreight.co.jp/",
    "checked": "2026-09-27",
    "credit": "Mitsuki-2368",
    "sourceTitle": "JRF EF210-111 20211218.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRF_EF210-111_20211218.jpg",
    "change": "長辺1280pxへ縮小・JPEG再圧縮。トリミング・描き換えなし。",
    "photoDescription": "山陽本線 庭瀬〜中庄間を走行するEF210-111号機（キャラクターラッピング仕様）",
    "station": "広島"
  },
  {
    "id": "ef210-300",
    "name": "JR貨物 EF210形300番台",
    "reading": "EF210がた 300ばんだい",
    "category": "かもつれっしゃ",
    "image": "assets/ef210-300.jpg",
    "fact": "瀬野と 八本松の あいだは きゅうな さかみち。おもい かもつれっしゃを うしろから おして たすける きかんしゃだよ。「おしたろう」と よばれることも あるよ。",
    "factSource": "https://ja.wikipedia.org/wiki/JR%E8%B2%A8%E7%89%A9EF210%E5%BD%A2%E9%9B%BB%E6%B0%97%E6%A9%9F%E9%96%A2%E8%BB%8A",
    "checked": "2026-09-27",
    "credit": "kh ws",
    "sourceTitle": "EF210-306 Saijo 20151024.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:EF210-306_Saijo_20151024.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "JR Freight Class EF210-300 electric locomotive EF210-306 at the rear of a freight train at Saijo Station",
    "station": "瀬野"
  },
  {
    "id": "carp",
    "name": "227系0番台 カープ応援ラッピング（2026）",
    "reading": "227けい カープおうえん ラッピング",
    "category": "でんしゃ",
    "image": "assets/carp2026.jpg",
    "fact": "ひろしまの プロやきゅう チーム、カープを おうえんする でんしゃ。2026ねんは 山陽本線と 呉線を はしるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/260220_00_press_Carpouenwrappingtrain2026.pdf",
    "checked": "2026-09-27",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の カープ応援ラッピングトレイン（動画の1コマ）.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#carp",
    "change": "撮影者提供の動画から1コマを切り出し、電車のまわりをトリミング。撮影情報なし。AI補正・描き換えなし。",
    "photoDescription": "夜の駅に入ってくる227系のカープ応援ラッピングトレインの正面",
    "station": "西条"
  },
  {
    "id": "urara",
    "name": "227系500番台 Urara",
    "reading": "227けい Urara（うらら）",
    "category": "でんしゃ",
    "image": "assets/urara.jpg",
    "fact": "おかやま・びんごエリアの 227けい。三原まで くると、Uraraの はしる エリアに つながるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/230529_00_press_okatetsu.pdf",
    "checked": "2026-09-19",
    "credit": "Travelweb.au",
    "sourceTitle": "227-500 series \"Urara\" at Uno Station.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:227-500_series_%22Urara%22_at_Uno_Station.jpg",
    "change": "Wikimedia提供の縮小画像を使用。写真の描き換えなし。",
    "photoDescription": "宇野駅に停車する227系500番台Urara",
    "station": "三原"
  },
  {
    "id": "greenmover",
    "name": "227系0番台 グリーンムーバーカラー",
    "reading": "227けい グリーンムーバーカラー",
    "category": "でんしゃ",
    "image": "assets/greenmover227.jpg",
    "fact": "ひろでんの ろめんでんしゃ「グリーンムーバーマックス」と いろを とりかえっこした 227けい。可部線も はしるよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/240820_00_press_hiroshima_wrappingtrain.pdf",
    "checked": "2026-09-27",
    "credit": "KageroYukikaze",
    "sourceTitle": "JRW-Series227-0 A12 Green Mover Max.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW-Series227-0_A12_Green_Mover_Max.jpg",
    "change": "Wikimedia提供の縮小画像（1280×1920px）から、電車のまわりを横長（1280×900px）にトリミング。AI補正・描き換えなし。",
    "photoDescription": "JR West 227-0 Series 3-car set A12 in Hiroshima Electric Railway \"Green Mover Max\" livery, Kure Station.",
    "station": "可部"
  },
  {
    "id": "etsetora",
    "image": "assets/etsetora.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:%E8%A5%BF%E5%BA%83%E5%B3%B6%E9%A7%85%E3%82%92%E9%80%9A%E9%81%8E%E3%81%99%E3%82%8BetSETOra(2021%E5%B9%B4).jpg",
    "sourceTitle": "西広島駅を通過するetSETOra(2021年).jpg",
    "credit": "勇敢な夕刊",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "西広島駅を通過するetSETOra",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-22",
    "station": "呉",
    "name": "etSETOra（エトセトラ）",
    "fact": "呉線を とおって せとうちを たびする かんこうれっしゃ。うみの あおと、なみの しろを まとっているよ。",
    "factSource": "https://www.jr-odekake.net/railroad/kankoutrain/etsetora/"
  },
  {
    "id": "rose",
    "name": "227系0番台 ばらのラッピング",
    "reading": "227けい ばらの ラッピング",
    "category": "でんしゃ",
    "image": "assets/rose227.jpg",
    "fact": "「ばらの まち」福山を しょうかいする でんしゃ。おおきな ばらと 花びらが えがかれて、呉線を ぜんぶ はしるよ。",
    "factSource": "https://railf.jp/news/2026/05/16/002000.html",
    "checked": "2026-09-27",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の 227系 ばらのラッピングトレイン.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#rose",
    "change": "撮影者提供の写真を長辺1280pxへ縮小し、写っている人（乗客・ホームの人）にモザイク。撮影情報を削除。AI補正・描き換えなし。",
    "photoDescription": "広島駅に停車中の227系A46編成（ばらのラッピングトレイン）の正面と側面",
    "station": "竹原"
  },
  {
    "id": "kiha40",
    "name": "キハ40形（朱色）",
    "reading": "キハ40がた",
    "category": "ディーゼルしゃ",
    "image": "assets/kiha40-shuiro.jpg",
    "fact": "芸備線の 広島〜三次を はしる オレンジいろの ディーゼルしゃ。うんてんせきが りょうほうに あるから、1りょうでも はしれるよ。",
    "factSource": "https://www.city.miyoshi.hiroshima.jp/soshiki/8/1396.html",
    "checked": "2026-09-27",
    "credit": "Hisagi",
    "sourceTitle": "JR West Kiha40 2045.png",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JR_West_Kiha40_2045.png",
    "change": "Wikimedia提供画像をJPEGに変換。トリミング・AI補正なし。",
    "photoDescription": "JR西日本、キハ40 2045（首都圏色）",
    "station": "下深川"
  },
  {
    "id": "kiha47",
    "name": "キハ47形（朱色）",
    "reading": "キハ47がた",
    "category": "ディーゼルしゃ",
    "image": "assets/kiha40-gantoku.jpg",
    "fact": "岩国えきで あえる オレンジいろの ディーゼルしゃ。うんてんせきは かたほうだけ。しゃしんは 岩徳線で、にしきがわの てっきょうを わたるところだよ。",
    "factSource": "https://commons.wikimedia.org/wiki/File:JRW_Gantoku-line_Kiha47.jpg",
    "checked": "2026-09-27",
    "credit": "MaedaAkihiko",
    "sourceTitle": "JRW Gantoku-line Kiha47.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Gantoku-line_Kiha47.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "A local train of JR West's Kiha 40 series 47 and 40 that crosses the Nishiki River between Nishi-Iwakuni Station and Kawanishi Station on the Iwantoku Line.",
    "station": "岩国"
  },
  {
    "id": "115",
    "image": "assets/115.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_Series115-3000_N-16.jpg",
    "sourceTitle": "JRW Series115-3000 N-16.jpg",
    "credit": "MaedaAkihiko",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "photoDescription": "A local train with the 115-3000 series N-16 formation that runs between Shin-Shimonoseki Station and Chofu Station on the Sanyo Main Line.",
    "change": "Wikimedia提供画像を使用。トリミング・AI補正なし。",
    "checked": "2026-09-27",
    "station": "柳井",
    "name": "115系3000番台",
    "fact": "山陽本線で かつやくしてきた きいろい でんしゃ。しゃしんは やまぐちエリアの 115けい 3000ばんだいだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/items/160122_00_spring_hiroshima.pdf"
  },
  {
    "id": "ginga",
    "name": "WEST EXPRESS 銀河",
    "reading": "ウエストエクスプレス ぎんが",
    "category": "かんこうれっしゃ",
    "image": "assets/ginga.jpg",
    "fact": "よるも はしる かんこうれっしゃ。ときどき 山陽本線を とおって、しものせきまで いくよ。よぞらの ような こいあおいろ。",
    "factSource": "https://www.jr-odekake.net/railroad/westexginga/course_sanyo/",
    "checked": "2026-09-27",
    "credit": "交通大臣 鉄道チャンネル",
    "sourceTitle": "JRW West Express Ginga Hiroshima 2020-04-16.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:JRW_West_Express_Ginga_Hiroshima_2020-04-16.jpg",
    "change": "Wikimedia提供の縮小画像（長辺1280px）を使用。トリミング・AI補正なし。",
    "photoDescription": "Luxury train West Express Ginga conducting staff training at Hiroshima Station, April 16, 2020.",
    "station": "光"
  },
  {
    "id": "kizashi",
    "name": "227系500番台 Kizashi",
    "reading": "227けい Kizashi（きざし）",
    "category": "でんしゃ",
    "image": "assets/kizashi.jpg",
    "fact": "やまぐちエリアの 227けい。山陽本線の 岩国〜しものせきを はしる、くろと きんいろの Kizashiだよ。",
    "factSource": "https://www.westjr.co.jp/press/article/2026/05/29/items/260529_00_press_Kizashi_shixyupatushiki.pdf",
    "checked": "2026-09-19",
    "credit": "家族撮影",
    "sourceTitle": "家族撮影の227系500番台 Kizashi.jpg",
    "license": "家族提供写真",
    "licenseUrl": "sources.html#family-photo",
    "source": "sources.html#kizashi",
    "change": "撮影者提供の写真をそのまま使用。AI補正・描き換えなし。",
    "photoDescription": "線路上を走る227系500番台Kizashiを遠方から撮影した写真",
    "station": "徳山"
  }
];if(typeof module!=='undefined')module.exports=cards;else r.RailCards=cards;})(globalThis);
