(function(root){
'use strict';
const R=typeof module!=='undefined'?require('./routes.js'):root.RailRoutes;
const KEY='keisan-tetsudo-v2',LEGACY_KEY='keisan-tetsudo-v1',RESET_KEY='keisan-tetsudo-v2-before-reset',LEGACY_ORIGIN='大竹';
const stationIds=Object.keys(R.stations),edgeById=Object.fromEntries(R.edges.map(e=>[e.id,e]));
// Problem kinds: v2 has add and sub (10 and under). add5/sub5 (answers and numbers 1 to 5, no 0) are the first steps for a younger child; they are a part of add/sub, the only kinds that share problems. v3 lets each person's kinds be turned on one by one in おうちの方へ (e.g. 九九 in 2nd grade, わりざん in 3rd); the buttons are the operations (`mode`), and a button mixes that operation's kinds that are on. A kind is weighted groups: add20/sub20 mix in about 1 in 5 without carrying. div is the 九九 backwards, so there is never a remainder. Answers go up to 891 (3 digits).
// パッと見 (look5: 1 to 5, look: 6 to 9 mixed in) shows people on two 5-seat benches for a moment; a is the upper bench, b the lower one (filled after the upper), so 7 is 5 and 2. It comes as the first problem of each section (see pick). `lookButton` (optional v3, true only) also gives it a button of its own, so a person can keep watching and open sections with it; `lookStay` (optional, ms) shows the car longer than the usual 0.8 s for a child who is just starting.
const seen=(lo,hi)=>span(lo,hi).map(n=>({a:Math.min(n,5),b:Math.max(n-5,0),result:n})),span=(lo,hi)=>Array.from({length:hi-lo+1},(_,i)=>lo+i),pairs=(as,bs,f)=>as.flatMap(a=>bs.flatMap(b=>{const result=f(a,b);return result===null?[]:[{a,b,result}];}));
const GROUPS={add5:[[1,pairs(span(1,4),span(1,4),(a,b)=>a+b<=5?a+b:null)]],sub5:[[1,pairs(span(2,5),span(1,4),(a,b)=>b<a?a-b:null)]],add:[[1,pairs(span(0,10),span(0,10),(a,b)=>a+b<=10?a+b:null)]],sub:[[1,pairs(span(0,10),span(0,10),(a,b)=>b<=a?a-b:null)]],add20:[[4,pairs(span(2,9),span(2,9),(a,b)=>a+b>10?a+b:null)],[1,pairs(span(11,18),span(1,8),(a,b)=>a%10+b<=9?a+b:null)]],sub20:[[4,pairs(span(11,18),span(2,9),(a,b)=>a%10<b?a-b:null)],[1,pairs(span(11,19),span(1,9),(a,b)=>b<=a%10?a-b:null)]],add2:[[1,pairs(span(10,99),span(10,99),(a,b)=>a+b)]],sub2:[[1,pairs(span(11,99),span(10,99),(a,b)=>b<=a?a-b:null)]],mul:[[1,pairs(span(1,9),span(1,9),(a,b)=>a*b)]],mul21:[[1,pairs(span(10,99),span(2,9),(a,b)=>a*b)]],div:[[1,pairs(span(1,9),span(1,9),(q,b)=>q).map(p=>({a:p.a*p.b,b:p.b,result:p.a}))]],look5:[[1,seen(1,5)]],look:[[1,seen(1,5)],[2,seen(6,9)]]};
const KINDS={add5:'plus',sub5:'minus',add:'plus',sub:'minus',add20:'plus',sub20:'minus',add2:'plus',sub2:'minus',mul:'times',mul21:'times',div:'divide',look5:'look',look:'look'},OPS=['plus','minus','times','divide'],LOOK='look',LOOK_STAYS=[800,1200,2000];
function pool(mode){return Object.hasOwn(GROUPS,mode)?GROUPS[mode].flatMap(g=>g[1]):[];}
function problem(mode,previous,random=Math.random){const groups=GROUPS[mode];let list=groups[0][1];if(groups.length>1){let r=random()*groups.reduce((n,g)=>n+g[0],0);for(const [w,l] of groups){list=l;if((r-=w)<0)break;}}const choices=list.filter(p=>!previous||p.a!==previous.a||p.b!==previous.b);return choices[Math.floor(random()*choices.length)];}
function validKinds(k){return Array.isArray(k)&&k.length>0&&new Set(k).size===k.length&&k.every(x=>Object.hasOwn(KINDS,x))&&k.some(x=>OPS.includes(KINDS[x]));}
function modes(s){return s.version===3?(validKinds(s.kinds)?[...OPS,...(s.lookButton?[LOOK]:[])].filter(o=>s.kinds.some(k=>KINDS[k]===o)):[]):['add','sub'];}
// v3: a problem of the current operation from one of its kinds that are on; the kind goes with it so the answer is counted under it. The first problem of a section is a パッと見 when one is on.
function pick(s,previous,random=Math.random){const looks=s.kinds.filter(k=>KINDS[k]===LOOK),list=looks.length&&paid(s)%5===0?looks:s.kinds.filter(k=>KINDS[k]===s.mode),kind=list[Math.floor(random()*list.length)];return {kind,...problem(kind,previous,random)};}
// The problem still fits the kinds that are on and the button (a パッと見 fits any button).
function fits(s){const k=s.problem?.kind;return s.kinds.includes(k)&&(KINDS[k]===s.mode||KINDS[k]===LOOK);}
function adjacent(id){return R.edges.filter(e=>e.a===id||e.b===id).map(e=>({...e,to:e.a===id?e.b:e.a}));}
function start(s){return s.origin||LEGACY_ORIGIN;}
function opened(s){return [...new Set([start(s),...s.edges.flatMap(id=>[edgeById[id].a,edgeById[id].b])])];}
// v3 counts answers per device and mode (`counts: {device: {mode: n}}`), so two devices' records can later be merged without counting twice. v2 keeps `total` and `stats`.
const DEVICE=/^d[a-z0-9]{6,20}$/;
function stats(s){if(s.version!==3)return s.stats;const out={};for(const c of Object.values(s.counts))for(const [m,n] of Object.entries(c))out[m]=(out[m]||0)+n;return out;}
function total(s){return s.version===3?Object.values(stats(s)).reduce((a,b)=>a+b,0):s.total;}
// `gift` (optional, `{device: n}`) fills openings a merge would otherwise take back (see merge); it counts toward openings but not as answers.
function paid(s){return total(s)+Object.values(s.gift||{}).reduce((a,b)=>a+b,0);}
// `rides` (optional v3, `{device: n}`) counts trips on sections already opened; each one used five answers like an opening.
function ridden(s){return Object.values(s.rides||{}).reduce((a,b)=>a+b,0);}
function credits(s){return Math.floor(paid(s)/5)-s.edges.length-ridden(s);}
const allCards=()=>root.RailCards||(typeof module!=='undefined'?require('./cards.js'):[]);
// A `first` card comes with the first opened section. `keep` holds cards a save earned under an older card map (see upgradeCards).
function earned(s){const unlocked=opened(s),keep=Array.isArray(s.keep)?s.keep:[];return allCards().filter(c=>(c.first?s.edges.length>0:unlocked.includes(c.station))||keep.includes(c.id)).map(c=>c.id);}
// Card map 2 (2026-09-24): Red Wing moved from Miyajimaguchi to the first opening, 115 from Iwakuni to Minami-Iwakuni. Card map 3 (2026-09-27): cards spread along the lines; 500 and APEX wait for their own tracks, KiHa 47 replaced the Gantoku KiHa 40 at Iwakuni. Saves from before keep every card they had.
// `keep` may also hold a retired card: it is not shown, and comes back if the card returns.
const CARD_MAP=3,RETIRED_CARDS=['500','apex','kiha40-gantoku'],OLD_CARD_MAPS={1:{redwing:'宮島口','500':'広島',ef210:'西条',urara:'三原',kizashi:'徳山','115':'岩国',kiha40:'下深川',etsetora:'呉'},2:{apex:'宮島口','500':'広島',ef210:'西条',urara:'三原',kizashi:'徳山','kiha40-gantoku':'岩国','115':'南岩国',kiha40:'下深川',etsetora:'呉'}};
const cardIds=()=>[...allCards().map(c=>c.id),...RETIRED_CARDS],knownMap=m=>m===2||m===CARD_MAP;
function upgradeCards(s){if(s.cardMap===CARD_MAP)return false;const unlocked=opened(s),now=earned({...s,keep:[]}),had=Object.entries(OLD_CARD_MAPS[s.cardMap===2?2:1]).filter(([,st])=>unlocked.includes(st)).map(([id])=>id),keep=new Set([...(Array.isArray(s.keep)?s.keep:[]),...had.filter(id=>id!=='kiha40-gantoku')]);s.keep=cardIds().filter(id=>keep.has(id)&&!now.includes(id));s.cardMap=CARD_MAP;return true;}
// Red Wing is rideable from the start; other trains become rideable with their cards. `train` remembers the last choice (optional).
const STARTER_TRAIN='redwing';
function rideable(s){return [...new Set([STARTER_TRAIN,...earned(s)])];}
function train(s){return typeof s.train==='string'&&rideable(s).includes(s.train)?s.train:STARTER_TRAIN;}
// Station stamps: every opened station has one (worked out from the edges, so old saves get theirs). `stamps` (optional) keeps the day each new station's stamp was pressed; the child presses it after arriving, and `pending.stamped` stops a second press.
const DAY=/^\d{4}-\d{2}-\d{2}$/;
function newStation(s){return !!s.pending&&!s.pending.ride&&!opened({...s,edges:s.edges.filter(id=>id!==s.pending.edge)}).includes(s.pending.station);}
function needsStamp(s){return newStation(s)&&!s.pending.stamped;}
function stamp(s,day){if(!needsStamp(s)||!DAY.test(day))return false;s.stamps={...s.stamps,[s.pending.station]:day};s.pending.stamped=true;return true;}
function fresh(){return {version:2,cardMap:CARD_MAP,keep:[],stamps:{},origin:R.origin,mode:'sub',total:0,stats:{add:0,sub:0},edges:[],current:R.origin,target:'大野浦',problem:problem('sub'),solved:false,pending:null};}
const plain=o=>!!o&&typeof o==='object'&&!Array.isArray(o),TIME=n=>Number.isSafeInteger(n)&&n>=0,LIFE=/^(l[a-z0-9]{6,20})?$/;
// Optional v3 fields for merging: `life` ({id, at}; a reset starts a new id, and none means the first life), `at` (last played) and `kindsAt` (kinds last changed), in ms.
function extras(s){return (s.life===undefined||plain(s.life)&&Object.keys(s.life).length===2&&typeof s.life.id==='string'&&LIFE.test(s.life.id)&&TIME(s.life.at))&&(s.at===undefined||TIME(s.at))&&(s.kindsAt===undefined||TIME(s.kindsAt))&&(s.lookButton===undefined||s.lookButton===true)&&(s.lookStay===undefined||LOOK_STAYS.slice(1).includes(s.lookStay))&&[s.gift,s.rides].every(g=>g===undefined||plain(g)&&Object.entries(g).every(([d,n])=>DEVICE.test(d)&&Number.isSafeInteger(n)&&n>0&&n<=1000000));}
function counted(s){if(s.version===3)return plain(s.counts)&&Object.entries(s.counts).every(([d,c])=>DEVICE.test(d)&&plain(c)&&Object.entries(c).every(([m,n])=>Object.hasOwn(KINDS,m)&&Number.isSafeInteger(n)&&n>=0))&&total(s)<=1000000;return Number.isSafeInteger(s.total)&&s.total>=0&&s.total<=1000000&&s.stats&&['add','sub'].every(m=>Number.isSafeInteger(s.stats[m])&&s.stats[m]>=0)&&s.stats.add+s.stats.sub===s.total;}
function common(s){const kind=s?.version===3?s.problem?.kind:s?.mode;return plain(s)&&modes(s).includes(s.mode)&&counted(s)&&typeof s.solved==='boolean'&&(s.version!==3||fits(s))&&pool(kind).some(p=>p.a===s.problem?.a&&p.b===s.problem?.b&&p.result===s.problem?.result);}
function valid(s){if(!common(s)||!extras(s)||![2,3].includes(s.version)||(s.version===3&&(!knownMap(s.cardMap)||!Array.isArray(s.keep)||!s.stamps||!R.stations[s.origin]||(s.news!==undefined&&(!Array.isArray(s.news)||new Set(s.news).size!==s.news.length||s.news.some(k=>!s.kinds.includes(k))))))||(s.train!==undefined&&typeof s.train!=='string')||(s.cardMap!==undefined&&!knownMap(s.cardMap))||(s.keep!==undefined&&(!Array.isArray(s.keep)||new Set(s.keep).size!==s.keep.length||s.keep.some(id=>!cardIds().includes(id))))||!Array.isArray(s.edges)||new Set(s.edges).size!==s.edges.length||s.edges.some(id=>!edgeById[id])||credits(s)<0||(s.origin!==undefined&&!R.stations[s.origin])||(s.stamps!==undefined&&(!s.stamps||typeof s.stamps!=='object'||Array.isArray(s.stamps)||Object.values(s.stamps).some(d=>typeof d!=='string'||!DAY.test(d)))))return false;const reached=new Set([start(s)]);for(const id of s.edges){const e=edgeById[id];if(!reached.has(e.a)&&!reached.has(e.b))return false;reached.add(e.a);reached.add(e.b);}if(!reached.has(s.current)||(s.stamps&&Object.keys(s.stamps).some(id=>!reached.has(id))))return false;if(s.target!==null&&!adjacent(s.current).some(e=>e.to===s.target))return false;if(s.pending!==null){if(!s.pending||(s.pending.ride!==undefined&&(s.pending.ride!==true||s.version!==3))||!s.edges.includes(s.pending.edge)||s.pending.station!==s.current||![edgeById[s.pending.edge].a,edgeById[s.pending.edge].b].includes(s.pending.station))return false;}return true;}
function migrate(s){if(!common(s)||s.version!==1||!Array.isArray(s.stations)||s.stations.length!==Math.floor(s.total/15)||!s.stations.every(x=>['green','sea','sun'].includes(x))||typeof s.pending!=='boolean')return null;const next=fresh();for(const k of ['mode','total','stats','problem','solved'])next[k]=JSON.parse(JSON.stringify(s[k]));return next;}
// The target can be any next station: five answers open a new section, or drive an opened one (v3). aim picks the next target after arriving (from `from`) or a warp: an unopened next station first (straight on if there is one), else straight on along the line, else any way but back.
function choose(s,to){if(s.pending||!adjacent(s.current).some(e=>e.to===to))return false;s.target=to;return true;}
function aim(s,from){const all=adjacent(s.current),fresh=all.filter(x=>!s.edges.includes(x.id)),back=all.find(x=>x.to===from);let ahead=null;if(back){const line=R.lines.find(l=>l.id===back.line),i=line.stations.indexOf(s.current);ahead=line.stations[i+(i-line.stations.indexOf(from))];}const pick=list=>list.find(x=>x.to===ahead)||list[0];s.target=(pick(fresh)||pick(all.filter(x=>x.to!==from))||all[0])?.to||null;return true;}
function move(s,id){if(s.pending||!opened(s).includes(id))return false;s.current=id;aim(s,null);return true;}
// A trip on an opened section is counted in `rides` under this device, so it needs the device (v3); it brings no stamp or card.
function build(s,device){if(s.pending||credits(s)<1)return false;if(!s.target)aim(s,null);const e=adjacent(s.current).find(e=>e.to===s.target);if(!e)return false;const ride=s.edges.includes(e.id);if(ride&&(s.version!==3||!DEVICE.test(device||'')))return false;const from=s.current;if(ride)s.rides={...s.rides,[device]:(s.rides?.[device]||0)+1};else s.edges.push(e.id);s.current=e.to;s.pending={station:e.to,edge:e.id,...(ride?{ride:true}:{})};aim(s,from);return true;}
// `device` (v3 only) is this device's id from the profile list; the answer is counted under it.
function solve(s,value,device){if(s.solved||s.pending||value===''||!/^\d{1,3}$/.test(String(value))||Number(value)!==s.problem.result||(s.version===3&&!DEVICE.test(device||'')))return false;s.solved=true;if(s.version===3){const c=s.counts[device]={...s.counts[device]};c[s.problem.kind]=(c[s.problem.kind]||0)+1;}else{s.total++;s.stats[s.mode]++;}if(paid(s)%5===0)build(s,device);return true;}
function setMode(s,mode){if(s.pending||s.mode===mode||!modes(s).includes(mode))return false;s.mode=mode;if(s.version===3&&KINDS[s.problem.kind]===LOOK&&!s.solved&&paid(s)%5===0)return true;s.problem=s.version===3?pick(s):problem(mode);s.solved=false;return true;}
// Turning kinds on or off (おうちの方へ): at least one stays on; if the current button or problem goes away, the first button and a new problem take over. Newly turned-on kinds the person has never answered wait in `news` (optional) for the child's celebration; seeNews clears them.
function setKinds(s,kinds,now){if(s.version!==3||!validKinds(kinds))return false;if(TIME(now))s.kindsAt=now;const before=s.kinds;s.kinds=Object.keys(KINDS).filter(k=>kinds.includes(k));const done=stats(s);s.news=s.kinds.filter(k=>(s.news||[]).includes(k)||!before.includes(k)&&!done[k]);if(!modes(s).includes(s.mode))s.mode=modes(s)[0];if(!fits(s)||!s.solved&&!s.pending&&paid(s)%5===0&&s.kinds.some(k=>KINDS[k]===LOOK)&&KINDS[s.problem.kind]!==LOOK){s.problem=pick(s);s.solved=false;}return true;}
// How パッと見 comes for this person (おうちの方へ): with a button of its own or not, and how long the car stays. It counts as a change of kinds for merging.
function setLook(s,button,stay,now){if(s.version!==3||typeof button!=='boolean'||!LOOK_STAYS.includes(stay))return false;if(TIME(now))s.kindsAt=now;if(button)s.lookButton=true;else delete s.lookButton;if(stay===LOOK_STAYS[0])delete s.lookStay;else s.lookStay=stay;if(!modes(s).includes(s.mode))s.mode=modes(s)[0];if(!fits(s)){s.problem=pick(s);s.solved=false;}return true;}
function seeNews(s){if(!s.news?.length)return false;s.news=[];return true;}
// A v2 save (a backup, or v1 after migrate) becomes a v3 record: its answers count under this device, its start station stays (大竹 for the oldest saves), cards follow card map 2. The original is not changed.
function fromV2(v2,device){if(!valid(v2)||v2.version!==2||!DEVICE.test(device||''))return null;const s=JSON.parse(JSON.stringify(v2));upgradeCards(s);const counts=Object.fromEntries(['add','sub'].filter(m=>s.stats[m]>0).map(m=>[m,s.stats[m]]));const out={...s,version:3,kinds:['add','sub'],mode:s.mode==='add'?'plus':'minus',problem:{kind:s.mode,...s.problem},counts:Object.keys(counts).length?{[device]:counts}:{},stamps:s.stamps||{},origin:start(s)};delete out.total;delete out.stats;return valid(out)?out:null;}
// Profiles (v3): five fixed places, each with its own record key. Names are set in the app and stay on the device (the code only has なまえ1…), with the device id used for counting answers.
const PROFILES_KEY='keisan-tetsudo-profiles',FIRST_KINDS=['add','sub','look5'],EASY_KINDS=['add5','sub5','look5'],PROFILES=[{id:'p1',kinds:FIRST_KINDS},{id:'p2',kinds:FIRST_KINDS},{id:'p3',kinds:Object.keys(KINDS).filter(k=>!EASY_KINDS.includes(k))},{id:'p4',kinds:Object.keys(KINDS).filter(k=>!EASY_KINDS.includes(k))},{id:'guest',kinds:FIRST_KINDS}];
function recordKey(id){return 'keisan-tetsudo-v3:'+id;}
function resetKey(id){return recordKey(id)+'-before-reset';}
function newDevice(random=Math.random){let id='d';while(id.length<13)id+=Math.floor(random()*36).toString(36);return id;}
function freshProfiles(random){return {version:1,device:newDevice(random),names:Object.fromEntries(PROFILES.map((p,i)=>[p.id,p.id==='guest'?'ゲスト':'なまえ'+(i+1)]))};}
function validName(n){return typeof n==='string'&&n===n.trim()&&n.length>=1&&[...n].length<=10;}
function validProfiles(p){return plain(p)&&p.version===1&&DEVICE.test(p.device)&&plain(p.names)&&Object.keys(p.names).length===PROFILES.length&&PROFILES.every(x=>Object.hasOwn(p.names,x.id)&&validName(p.names[x.id]));}
function rename(p,id,name){name=typeof name==='string'?name.trim():'';if(!PROFILES.some(x=>x.id===id)||!validName(name))return false;p.names[id]=name;return true;}
function freshRecord(id){const s={version:3,kinds:[...(PROFILES.find(p=>p.id===id)?.kinds||FIRST_KINDS)],cardMap:CARD_MAP,keep:[],stamps:{},origin:R.origin,mode:null,counts:{},edges:[],current:R.origin,target:'大野浦',problem:null,solved:false,pending:null};s.mode=modes(s)[0];s.problem=pick(s);return s;}
// Starting over (リセット・ゲストを消す) begins a new life, so merging never brings the old record back. Taking back the copy from before a reset makes its life the newest again.
function newLife(s,now,random=Math.random){let id='l';while(id.length<13)id+=Math.floor(random()*36).toString(36);s.life={id,at:now};return true;}
function revive(s,now){s.life={id:s.life?.id||'',at:now};return true;}
// Merging one person's records from two devices (手渡し・同期). A copy from a newer life (a reset) replaces the other. Otherwise what only grows is joined: answers per device and kind by the larger count, sections (put in a fixed order from the start station), kept cards, stamps (the earlier day). Where the child is (station, target, reward on the way, problem, button, train) follows the copy played last (`at`); kinds (and how パッと見 comes) follow the last change in おうちの方へ (`kindsAt`). When both devices spent the same saved answers, the missing openings are filled with `gift` under this device, keeping the dots of the copy played last. The result does not depend on which copy comes first, and merging it again changes nothing.
function merge(a,b,device){if(!valid(a)||!valid(b)||a.version!==3||b.version!==3||a.origin!==b.origin||!DEVICE.test(device||''))return null;const copy=o=>JSON.parse(JSON.stringify(o)),life=s=>s.life||{id:'',at:0},later=(x,y,t)=>(t(x)!==t(y)?t(x)>t(y):JSON.stringify(x)>=JSON.stringify(y))?x:y,most=(x={},y={})=>{const r={...x};for(const [k,n] of Object.entries(y))r[k]=Math.max(r[k]||0,n);return r;},when=(k,out)=>{if(a[k]!==undefined||b[k]!==undefined)out[k]=Math.max(a[k]||0,b[k]||0);};
a=copy(a);b=copy(b);upgradeCards(a);upgradeCards(b);if(life(a).id!==life(b).id)return copy(later(a,b,s=>life(s).at));const p=later(a,b,s=>s.at||0),k=later(a,b,s=>s.kindsAt||0),out=copy(p);
if(a.life||b.life)out.life={id:life(a).id,at:Math.max(life(a).at,life(b).at)};when('at',out);when('kindsAt',out);out.counts=Object.fromEntries([...new Set([...Object.keys(a.counts),...Object.keys(b.counts)])].sort().map(d=>[d,most(a.counts[d],b.counts[d])]));if(a.gift||b.gift)out.gift=most(a.gift,b.gift);if(a.rides||b.rides)out.rides=most(a.rides,b.rides);
out.keep=cardIds().filter(id=>a.keep.includes(id)||b.keep.includes(id));out.stamps={...a.stamps};for(const [id,day] of Object.entries(b.stamps))if(!out.stamps[id]||day<out.stamps[id])out.stamps[id]=day;
const union=new Set([...a.edges,...b.edges]),reached=new Set([a.origin]);out.edges=[];while(out.edges.length<union.size){const e=R.edges.find(e=>union.has(e.id)&&!out.edges.includes(e.id)&&(reached.has(e.a)||reached.has(e.b)));out.edges.push(e.id);reached.add(e.a);reached.add(e.b);}
out.kinds=[...k.kinds];for(const x of ['lookButton','lookStay'])if(k[x]!==undefined)out[x]=k[x];else delete out[x];if(k.news!==undefined){const done=stats(out);out.news=k.news.filter(x=>!done[x]);}else delete out.news;if(!modes(out).includes(out.mode))out.mode=modes(out)[0];if(!fits(out)){out.problem=pick(out,null,()=>0);out.solved=false;}
if(out.target===null||!adjacent(out.current).some(e=>e.to===out.target))aim(out,null);const need=5*(out.edges.length+ridden(out));if(paid(out)<need)out.gift={...out.gift,[device]:(out.gift?.[device]||0)+need+paid(p)%5-paid(out)};return valid(out)?out:null;}
function next(s){if(s.pending||!s.solved)return false;s.problem=s.version===3?pick(s,s.problem):problem(s.mode,s.problem);s.solved=false;return true;}
function nearestReward(s,cards,directional=false){const unlocked=new Set(opened(s));const got=new Set(earned(s)),targets=cards.filter(c=>!c.first&&!got.has(c.id)&&!unlocked.has(c.station));const start=directional&&s.target?s.target:s.current;const initial=start===s.current||adjacent(s.current).some(e=>e.to===start&&s.edges.includes(e.id))?0:1;const queue=[{id:start,cost:initial}],dist={[start]:initial};while(queue.length){queue.sort((a,b)=>a.cost-b.cost);const item=queue.shift();if(item.cost!==dist[item.id])continue;for(const e of adjacent(item.id)){if(directional&&s.target&&e.to===s.current)continue;const cost=item.cost+(s.edges.includes(e.id)?0:1);if(dist[e.to]===undefined||cost<dist[e.to]){dist[e.to]=cost;queue.push({id:e.to,cost});}}}return targets.filter(c=>dist[c.station]!==undefined).map(c=>({...c,remaining:dist[c.station]})).sort((a,b)=>a.remaining-b.remaining)[0]||null;}
// きゅうけい (2026-09-29): per person on this device, kept apart from the record (not in backups or merges). Playing time is counted between taps: a gap under 5 minutes counts, 5 minutes or more does not (left alone), 10 minutes or more is a rest and starts over. After `play` minutes the child rests `rest` minutes (`until`, 0 when not resting); `n` counts answers in this stretch. `unit` is one minute in ms (shorter to try it out). The adults' places (p3, p4) start with it off.
const REST_PLAY=[20,30,45,60],REST_LEN=[5,10,15,20],IDLE=5,AWAY=10,SOON=5;
function restKey(id){return 'keisan-tetsudo-rest:'+id;}
function freshRest(id){return {version:1,on:!['p3','p4'].includes(id),play:30,rest:15,used:0,seen:0,until:0,n:0};}
function validRest(r){return plain(r)&&Object.keys(r).length===8&&r.version===1&&typeof r.on==='boolean'&&REST_PLAY.includes(r.play)&&REST_LEN.includes(r.rest)&&[r.used,r.seen,r.until,r.n].every(TIME);}
function endRest(r,now){r.until=0;r.used=0;r.n=0;r.seen=now;return true;}
// A clock set back cannot make the rest longer; once the rest is over, the next tap starts a new stretch.
function restTick(r,now,unit=60000){if(!TIME(now))return false;if(r.until&&r.until-now>r.rest*unit)r.until=now+r.rest*unit;if(r.until&&now>=r.until)endRest(r,now);const gap=now-r.seen;if(!r.until&&gap>=0){if(gap>=AWAY*unit){r.used=0;r.n=0;}else if(gap<IDLE*unit)r.used+=gap;}r.seen=now;return true;}
function restDue(r,unit=60000){return r.on&&!r.until&&r.used>=r.play*unit;}
function restSoon(r,unit=60000){return r.on&&!r.until&&r.used>=(r.play-SOON)*unit;}
function startRest(r,now,unit=60000){if(!restDue(r,unit)||!TIME(now))return false;r.until=now+r.rest*unit;return true;}
function restLeft(r,now){return r.until?Math.max(0,r.until-now):0;}
function setRest(r,on,play,rest,now){if(typeof on!=='boolean'||!REST_PLAY.includes(play)||!REST_LEN.includes(rest))return false;r.on=on;r.play=play;r.rest=rest;if(!on&&r.until)endRest(r,now);return true;}
const api={LOOK,LOOK_STAYS,setLook,REST_PLAY,REST_LEN,restKey,freshRest,validRest,endRest,restTick,restDue,restSoon,startRest,restLeft,setRest,paid,ridden,aim,newLife,revive,merge,FIRST_KINDS,KINDS,OPS,validKinds,modes,pick,stats,total,setMode,setKinds,seeNews,fromV2,PROFILES_KEY,PROFILES,recordKey,resetKey,newDevice,freshProfiles,validName,validProfiles,rename,freshRecord,newStation,needsStamp,stamp,KEY,LEGACY_KEY,RESET_KEY,STARTER_TRAIN,CARD_MAP,upgradeCards,rideable,train,pool,problem,fresh,valid,migrate,adjacent,opened,credits,earned,choose,move,build,solve,next,nearestReward,edgeById};if(typeof module!=='undefined')module.exports=api;else root.RailMath=api;
})(typeof window==='undefined'?globalThis:window);
